GoogleCloudPlatform/nodejs-docs-samples

- appengine/express/app.yaml
- appengine/express/bin/www
- appengine/express/routes/index.js
- appengine/geddy/app.yaml
- appengine/geddy/app/controllers/main.js
- appengine/geddy/server.js
- appengine/grunt/Gruntfile.js
- appengine/grunt/app.yaml
- appengine/grunt/src/app.js
- appengine/grunt/src/bin/www
- appengine/grunt/src/routes/index.js
- appengine/hapi/app.yaml
- appengine/hapi/index.js
- appengine/koa/app.js
- appengine/koa/app.yaml
- appengine/kraken/README.md
- appengine/kraken/app.yaml
- appengine/kraken/controllers/index.js
- appengine/kraken/server.js
- appengine/loopback/app.yaml
- appengine/loopback/server/server.js
- appengine/redis/app.yaml
- appengine/redis/server.js
- appengine/restify/app.yaml
- appengine/restify/server.js
- appengine/sails/README.md
- appengine/sails/app.js
- appengine/sails/app.yaml
- Added Geddy comments
- Added Hapi comments
- Added Koa comments
- Added Kraken comments
- Added loopback comments
- Added Restify comments
- Added Sails comments
- Added Grunt comments
- Fixed indentation
- Added Redis comments
- Added missing code fences
> Added comments so code can be included in our site docs.

- appengine/mailgun/README.md
- appengine/mailgun/app.js
- appengine/mailgun/app.yaml
- appengine/mailgun/package.json
- appengine/mailgun/views/index.jade
> Added mailgun example.

- README.md
- datastore/concepts.js
- datastore/package.json
- test/datastore/entity.test.js
- test/datastore/index.yaml
- test/datastore/indexes.test.js
- test/datastore/metadata.test.js
- test/datastore/query.test.js
- test/datastore/transaction.test.js
// @pcostell
This is some snippet code in preparation of the datastore v1beta3 release. It's a work in progress, so I wanted to get reviews and guidance on the structure to follow as early as possible.
Some questions:
- Do we have freedom to use `taskKey` (convention) vs `task_key` (snippet spreadsheet) - the linter caught this as an error, and I wasn't sure if either is a hard requirement.
- gcloud-node doesn't have an Entity type; data that goes or comes from an entity are just plain JavaScript objects, without special capabilities
- I assume this JavaScript snippet file is meant to be runnable-- as in, instead of dumping out a bunch of vars and function calls, I should box them inside of functions that can be called individually?
Any insight into how the docs are generated from this …
> add datastore v1beta3 snippets

- datastore/concepts.js
- datastore/tasks.js
- Fixes small typos in the region tags
- Rearranged the build_service snippet to include the correct region.
> Update gcloud-node datastore snippets

- datastore/concepts.js
- test/datastore/entity.test.js
- test/datastore/indexes.test.js
- test/datastore/metadata.test.js
- test/datastore/query.test.js
- test/datastore/transaction.test.js
- test/datastore/util.js
RE: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/32#issuecomment-158147119
> Delete all created Task entities after tests run

- package.json
- prediction/hostedmodels.js
- prediction/package.json
- test/prediction/hostedmodels.test.js
Adding missing Node.js sample for these docs: https://cloud.google.com/prediction/docs/developer-guide#predictionfromappengine
> Add Prediction API sample.

- .travis.yml
- README.md
- appengine/datastore/app.js
- appengine/pubsub/app.js
- appengine/storage/app.js
- datastore/README.md
- datastore/tasks.js
- logging/export.js
- logging/list.js
- logging/write.js
- package.json
- pubsub/README.md
- pubsub/iam.js
- pubsub/package.json
- pubsub/subscription.js
- test/appengine/all.test.js
- test/pubsub/iam.test.js
- test/pubsub/subscription.test.js
- test/storage/authSample.test.js
@jonparrott I messed up git in my last pubsub branch. This one addresses your comments on the last branch, including updating other samples to use the GOOGLE_APPLICATION_CREDENTIALS and GCLOUD_PROJECT env vars consistently.
> Added Pub/Sub samples.

- pubsub/iam.js
- pubsub/subscription.js
> Couple of pubsub fixes.

- .jshintignore
- README.md
- appengine/parse-server/README.md
- appengine/parse-server/app.yaml
- appengine/parse-server/cloud/main.js
- appengine/parse-server/package.json
- appengine/parse-server/server.js
- test/appengine/all.test.js
> Added Parse-server example.

- appengine/cloudsql/app.js
- appengine/datastore/app.js
- appengine/disk/app.js
- appengine/express-memcached-session/server.js
> Don't store ip addresses.

- monitoring/README.md
- monitoring/create_custom_metric.js
- monitoring/list_resources.js
- monitoring/package.json
Note: Need tests. I am working on a followup
commit to this and should have it ready by EOD.
You already reviewed this code, this is migration
from git-on-borg.
> Add Monitoring v3 Samples

- monitoring/README.md
- monitoring/create_custom_metric.js
- monitoring/list_resources.js
- test/monitoring/create_custom_metric.test.js
- test/monitoring/list_resources.test.js
@JustinBeckwith @jonparrott 
Unfortunately we have to code freeze these samples until GCP Next is over next week, but feel free to  review at your convenience. 
Had to refactor the main code a bit, since for my custom metric tests, I generate a new custom metric and write one value for it. I made CustomMetrics a class so I could attach the metric name to its state. Not sure if this the most idiomatic way to do it for this repo so let me know.
The tests aren't going to work until the API no longer requires a whitelist. That might be now or very soon (I'll double check), otherwise we can add your test project as an owner of mine.
> Add Monitoring Tests

- appengine/parse-server/README.md
- appengine/parse-server/app.yaml
- appengine/parse-server/config.json
- appengine/parse-server/package.json
- appengine/parse-server/server.js
I am at a event and a lot of people want to run Parse Server on App Engine. The env variables are very confusing when running locally. This patch makes it so the variables set in the app.yaml are applied to the local config as well.
It might make sense to have a "LOCAL_DATABASE_URI" as well in app.yaml, so you can run a local database.
> Env vars are parsed from app.yaml on local run. Added SERVER_URL to app.yaml

- containerengine/hello-world/Dockerfile
- containerengine/hello-world/server.js
- test/appengine/all.test.js
> Container Engine hello world sample

- datastore/package.json
> Bump gcloud requirement to version based on Datastore v1beta3.

- .travis.yml
- README.md
- appengine/datastore/app.js
- appengine/datastore/package.json
- appengine/pubsub/package.json
- appengine/storage/package.json
- bigquery/package.json
- computeengine/package.json
- datastore/concepts.js
- datastore/error.js
- datastore/tasks.js
- logging/package.json
- package.json
- pubsub/package.json
- test/appengine/all.test.js
- test/datastore/concepts.test.js
- No longer testing on Node v0.10
- Switched to Codecov
- Fixed some Datastore stuff related to upgrading to gcloud-node 0.30.3
> Upgraded dependencies

- appengine/endpoints/README.md
- appengine/endpoints/app.js
- appengine/endpoints/app.yaml
- appengine/endpoints/package.json
- appengine/endpoints/swagger.yaml
> Add basic Endpoints sample.

- README.md
- appengine/README.md
- bigquery/README.md
- computeengine/README.md
- computeengine/package.json
- containerengine/README.md
- containerengine/hello-world/README.md
- datastore/README.md
- functions/README.md
- functions/helloworld/README.md
- functions/log/README.md
- functions/message/README.md
- functions/module/README.md
- functions/uuid/README.md
- logging/README.md
- logging/package.json
- monitoring/README.md
- prediction/README.md
- prediction/package.json
- pubsub/README.md
- pubsub/package.json
- speech/README.md
- speech/package.json
- storage/README.md
- storage/package.json
- vision/README.md
See how the new READMEs look: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/readme
I only changed README.md and package.json files. Changes to package.json files were only to remove `"scripts"`, as per the new sample execution instructions in the README.md files.
> Re-organized readme files.

- appengine/express-memcached-session/app.yaml
This uses the correct memcache environment variable in the express-memcached-session example.
Please let me know if there's anything else I need to do.
> Use correct memcache environment variable. Fixes #123

- language/README.md
- language/analyze.js
- language/package.json
- package.json
- test/language/analyze.test.js
This sample makes a request to analyze the entities in text.
> Add Cloud Natural Language API sample.

- pubsub/system-test/subscriptions.test.js
- storage/README.md
- storage/buckets.js
- storage/encryption.js
- storage/files.js
- storage/system-test/encryption.test.js
- storage/test/buckets.test.js
- storage/test/encryption.test.js
- storage/test/files.test.js
> Add Cloud Storage encryption samples and tests.

- datastore/concepts.js
Uses 'category' instead of 'type' as a property name
> Changes property name

- storage/README.md
- storage/acl.js
- storage/package.json
- storage/system-test/acl.test.js
- storage/test/acl.test.js
> Storage ACL samples.

- CONTRIBUTING.md
- storage/README.md
- storage/acl.js
- storage/buckets.js
- storage/encryption.js
- storage/files.js
- storage/system-test/buckets.test.js
- storage/system-test/encryption.test.js
- storage/system-test/files.test.js
- storage/system-test/transfer.test.js
- storage/test/acl.test.js
- storage/test/buckets.test.js
- storage/test/encryption.test.js
- storage/test/files.test.js
- storage/test/transfer.test.js
- storage/transfer.js
> All Storage samples are now up to standard.

- README.md
This updates the main README to group products the same way their grouped here: https://cloud.google.com/products/
> Organize samples by product group.

- bigquery/test/queries.test.js
- bigquery/test/tables.test.js
- logging/test/logs.test.js
- logging/test/sinks.test.js
- pubsub/test/iam.test.js
- pubsub/test/subscriptions.test.js
- pubsub/test/topics.test.js
- storage/test/acl.test.js
- storage/test/buckets.test.js
- storage/test/encryption.test.js
- storage/test/files.test.js
- translate/test/translate.test.js
> Use real Error in tests.

- monitoring/create_custom_metric.js
- monitoring/list_resources.js
Renaming some APIs to Stackdriver brand
> Stackdriver product rename

- bigquery/system-test/quickstart.test.js
- bigquery/test/quickstart.test.js
- datastore/system-test/quickstart.test.js
- datastore/test/quickstart.test.js
- logging/test/quickstart.test.js
- pubsub/test/quickstart.test.js
- storage/test/quickstart.test.js
- translate/system-test/quickstart.test.js
- translate/test/quickstart.test.js
> Add quickstart tests

- bigquery/quickstart.js
- datastore/quickstart.js
- logging/quickstart.js
- pubsub/package.json
- pubsub/quickstart.js
- pubsub/subscriptions.js
- pubsub/system-test/subscriptions.test.js
- pubsub/system-test/topics.test.js
- pubsub/test/subscriptions.test.js
- pubsub/test/topics.test.js
- pubsub/topics.js
- storage/quickstart.js
- translate/quickstart.js
Also, moved client library instantiation back into the sample functions.
I went back on that after feedback received in my python and ruby pubsub-sample-style PRs.
> Add message ordering samples

- datastore/concepts.js
- datastore/system-test/concepts.test.js
> Fix pagination

- pubsub/topics.js
- storage/README.md
- storage/acl.js
- storage/buckets.js
- storage/encryption.js
- storage/files.js
- storage/package.json
- storage/system-test/acl.test.js
- storage/system-test/buckets.test.js
- storage/system-test/encryption.test.js
- storage/system-test/files.test.js
- storage/system-test/transfer.test.js
- storage/test/acl.test.js
- storage/test/buckets.test.js
- storage/test/encryption.test.js
- storage/test/files.test.js
- storage/test/transfer.test.js
- storage/transfer.js
- utils/index.js
I left the Storage Transfer API samples alone. I don't want to mess with them until the google-cloud-node has support for the Storage Transfer API.
> Simplify Storage samples and their tests.

- appengine/storage/app.js
There is no "inMemory" options for multer.
> Fix multer options

- endpoints/getting-started/Dockerfile.custom
- endpoints/getting-started/container-engine.yaml
Switch ports and name on docker image for Endpoints GKE sample to align with other languages.
`gcr.io/google-samples/echo-node:1.0` is updated and pushed.
> Update ports for endpoints sample.

- appengine/storage/app.js
There is no `fileSize` option for multer. (https://github.com/expressjs/multer#multeropts)
`fileSize` option is member of `limits`. (https://github.com/expressjs/multer#limits)
> (fix) Multer options

- appengine/cloudsql/app.yaml
We're moving towards using instance connection name everywhere. It's also available from gcloud now.
> Update app.yaml to use instance connection name

- functions/sendgrid/index.js
`autoCreate` is consumed in `dataset.get` and `table.get` is called with empty option. This behaviour prevents me to create table on the fly.
The log(project/dataset name is masked):
```
E      sendgridLoad     49181714454430  2016-11-25 07:27:35.826  ApiError: Not found: Table the-project-name:the-dataset.events
at new util.ApiError (/user_code/node_modules/@google-cloud/common/src/util.js:107:10)
at Object.parseHttpRespBody (/user_code/node_modules/@google-cloud/common/src/util.js:185:30)
at Object.handleResp (/user_code/node_modules/@google-cloud/common/src/util.js:125:18)
at /user_code/node_modules/@google-cloud/common/src/util.js:448:12
at Request.onResponse [as _callback] (/user_code/node_modules/retry-request/index.js:120:7)
at Request.self.callback …
```
> Enable auto table creation in Google Cloud Functions SendGrid tutorial

- language/slackbot/README.md
- language/slackbot/demo_bot.js
- language/slackbot/generate-dep.sh
For the NL API slackbot: add support for optionally using a PD for the db in the k8s app; better error handling. Also changed db query to get the top entities from only the last 7 days.
> support for optionally using a PD for the db; better error handling

- endpoints/getting-started/app.yaml
vm: true is no longer accepted. It is now env: flex
> Removed deprecated flag from app.yaml

- spanner/transaction.js
Documentation at https://cloud.google.com/spanner/docs/transactions#rw_transaction_example says that second budget should be at least $300,000 for the transaction to proceed. I'm fixing this for Python / Node. Addresses bug #35360945.
> Updated readWriteTransaction to fix bug

- spanner/transaction.js
Adding a missing `{readOnly: true}` option in `runTransaction()`
> Fix issue with read-only transaction

- bigquery/tables.js
Looks like these comments were supposed to reference tables instead of datasets.
> Fixed some typos in tables.js

- language/slackbot/demo_bot.js
It looks like the sentiment score range changed since this example was written; updating the `SENTIMENT_THRESHOLD` to reflect that.  Also changed some of the comment wording to avoid the word 'magnitude' in ref to score, which was probably confusing.  
Fixed a typo in some commented-out logging code.
> update the sentiment threshold; fix a typo in some commented-out code.

- functions/datastore/README.md
Replaced gcloud alpha functions with gcloud beta functions.
> Update README.md to use gcloud beta functions

- functions/spanner/index.js
- functions/spanner/package.json
- functions/spanner/test/index.test.js
FYI @WalterHub - this is the sample you wanted me to add.
@jmdobry: the sample code itself has (presumably) already been reviewed (given that it was pasted directly into a docs page). The test code, however, is new and _has **not_** been reviewed yet.
> Add Spanner + Cloud Functions sample

- speech/recognize.js
> Fixes typo

- functions/spanner/index.js
Results in less steps for the user.
> Changes IDs of instance and database to be consistent with other topics.

- appengine/errorreporting/app.js
- appengine/errorreporting/package.json
- appengine/errorreporting/test/app.test.js
- appengine/errorreporting/yarn.lock
Updates the sample to start using [@google-cloud/error-reporting](https://www.npmjs.com/package/@google-cloud/error-reporting)
> update sample to use @google-cloud/error-reporting

- appengine/cloudsql/README.md
- appengine/cloudsql/app.yaml
- appengine/cloudsql/createTables.js
- appengine/cloudsql/package.json
- appengine/cloudsql/server.js
- appengine/cloudsql/test/createTables.test.js
- appengine/cloudsql/test/server.test.js
- appengine/cloudsql/yarn.lock
- circle.yml
Don't merge this (yet): some region tags have changed, and the docs have not been updated accordingly.
> Add postgres samples

- functions/ocr/README.md
Fix wrong clickable link on README
> Fix wrong link

- dlp/README.md
- dlp/package.json
> Update DLP README

- dlp/inspect.js
- dlp/quickstart.js
- dlp/redact.js
- dlp/system-test/quickstart.test.js
@bshaffer - adding you as a reviewer to make sure this matches the PHP sample's style. Thanks!
> Add DLP quickstart + fix incorrect comments

- README.md
> Add prerequisite to install semistandard (required for `npm test`)

- kms/README.md
- kms/keys.js
- kms/system-test/keys.test.js
This change, in particular:
* Consistently names variables with the API (locationId, keyRingId,
cryptoKeyId).
* Displays the function name in the region tag.
* Correctly writes decoded base64 to disk  and encodes file contents
before calling KMS.
* Correctly loads decoded base64 from disk.
* Labels parameters as plaintextFileName and ciphertextFileName, rather
than inFile and outFile where applicable.
* Makes test failure messages more readable.
> KMS: Makes samples consistent across languages. by @white0ut

- iot/manager/manager.js
Making a few changes to ensure the snippets are consistent for including in documentation soon.
> Snippet consistency

- speech/recognize.js
> Speech: Use all results, instead of just the first.

- endpoints/getting-started/container-engine.yaml
The container registry b.gcr.io has been deprecated. In this bug fix, the deprecated
container registry has been updated to the correct container registry.
> Fix for the bug: pod error ImagePullBackOff

- iot/manager/manager.js
correct commandline parameters example
> wrong name of commandline parameters in example

- appengine/cloudtasks/README.md
- appengine/cloudtasks/app.yaml
- appengine/cloudtasks/createTask.js
- appengine/cloudtasks/package.json
- appengine/cloudtasks/server.js
- appengine/cloudtasks/test/createTask.test.js
- circle.yml
- cloudtasks/README.md
- cloudtasks/package.json
- cloudtasks/system-test/tasks.test.js
- cloudtasks/tasks.js
Created based on:
https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/appengine/flexible/tasks
and
https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/tasks
> Cloud Tasks samples.

- appengine/hello-world/app.yaml
We've gotten reports of unexpected costs from users that left the hello world running and had two standard instances running for a month. This keeps the costs to a minimum to kick the tires.
> Keeping user costs low

- iot/manager/README.md
service account mandatory (no ADC)
apiKey no longer needed or in code
s/snake_case/camelCase for service account param
> a couple fixes to readme examples

- endpoints/getting-started/deployment.yaml
For better readability, let's use the long name options for the ESP config.
> Use long options for the ESP config

- endpoints/getting-started/deployment.yaml
To be consistent with the docs and the version of this file in the other language repos, use SERVICE_CONFIG_ID.
> Use SERVICE_CONFIG_ID

- functions/background/index.js
- functions/datastore/index.js
- functions/errorreporting/index.js
- functions/gcs/index.js
- functions/helloworld/index.js
- functions/http/index.js
- functions/log/index.js
- functions/ocr/app/index.js
- functions/pubsub/index.js
- functions/sendgrid/index.js
- functions/sendgrid/test/index.test.js
- functions/slack/index.js
- functions/uuid/index.js
As discussed in the email thread.
@ace-n
> Updates the function snippet syntax to ES6 standards.

- endpoints/getting-started-grpc/README.md
- endpoints/getting-started-grpc/http_deployment.yaml
- endpoints/getting-started-grpc/protos/http_helloworld.proto
- Add `http_helloworld.proto` gRPC definition with HTTP transcoding.
- Add `http_deployment.yaml` kubernetes deployment with HTTP1.1 port
enabled for transcoding.
- Update README accordingly.
- Update README with long-flags everywhere.
> Update sample to include an example of gRPC HTTP/JSON transcoding setup.

- iot/mqtt_example/README.md
@gguuss PTAL - looks like a copy paste from python sample perhaps
> Update arg format in readme from snake-case to camelCase

- appengine/hello-world/app.yaml
> app.yaml s/python/nodejs in comment

- auth/auth.js
This fixes https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/574 by replacing the URL with what I believe it should be.
> Fix comment URL 404

- endpoints/getting-started-grpc/README.md
- endpoints/getting-started-grpc/deployment.yaml
- endpoints/getting-started-grpc/http_deployment.yaml
- endpoints/getting-started/app.yaml
- endpoints/getting-started/deployment.yaml
We introduce a new feature where we can specify in YAML that service configuration for Endpoints is going to be managed. This means that the service will pull latest deployed service configuration automatically, rather than requiring customer to specify specific version of service configuration.
New flag:
**--rollout_strategy=managed**
Previously the only way to specify a version was using the following flag:
**--version=SERVICE_CONFIG_ID**
> Change to endpoints managed rollout

- functions/imagemagick/index.js
- functions/imagemagick/package.json
- functions/imagemagick/test/index.test.js
> Update functions/imagemagick sample

- kms/quickstart.js
- kms/system-test/quickstart.test.js
As title.
**Note that the test assumes that your project has at least 1 keyring.** @jmdobry let me know if this should be changed.
> Update KMS sample

- endpoints/getting-started/openapi.yaml
I'm updating all the openapi files in the getting-started sample in all the sample repos to remove basePath: "/"
Here's the reason from simonz130:
From the OpenAPI 2 spec:
* basePath: "If it is not included, the API is served directly under the host. The value MUST start with a leading slash (/). "
* Paths for methods: "A relative path to an individual endpoint. The field name MUST begin with a slash. The path is appended to the basePath in order to construct the full URL."
This OpenAPI getting-started sample have basePath: "/", which (per strict spec interpretation) means all the paths start with double-slashes. (e.g "//v1/shelves" rather than "/v1/shelves"). Removing basepath="/" fixes that.
> Remove basePath: "/"

- circle.yml
- functions/concepts/index.js
- functions/concepts/loadable.js
- functions/concepts/package.json
- functions/concepts/test/index.test.js
- functions/helloworld/.gcloudignore
- functions/helloworld/index.js
- functions/http/index.js
- functions/tips/.gcloudignore
- functions/tips/index.js
- functions/tips/package.json
- functions/tips/test/index.test.js
~**Do not merge** until we figure out what our testing plan for these is.~
cc @jasonpolites @emesx
> Move GCF samples from docs into Github

- functions/http/index.js
~**Do not merge** until the docs have been updated accordingly.~
cc @marekbiskup
> Clarify comments + add field handler to multipart sample

- appengine/analytics/package.json
- appengine/datastore/package.json
`npm test`, which runs the linter, needs this dependency explicitly. 
We install `semistandard` manually on CircleCi. But since it's required in a sample's `run test`, it should be in the `package.json`.
> Add missing lint dependency

- circle.yml
- functions/datastore/test/index.test.js
Run the second function emulator test only on PRs from this repo, not from forks. It needs access to multiple environment variables. They are not available on CircleCi for forks. Instead of having the test fail, don't run it.
> Add function emulator back in

- appengine/headless-chrome/app.js
Awaiting for the headless browser to be closed add a certain amount of time to the duration of the request, although the image is already ready to be sent back to the user.
/cc @steren
> No need to await for the browser to be closed to send back the screenshot

- appengine/headless-chrome/app.js
It seems the --disable-setuid-sandbox flag is becoming deprecating and is being removed from the Chrome codebase.
I tried running the sample without this flag, and the screenshots are properly generated.
/cc @steren
> No need for the --disable-setuid-sandbox flag

- .kokoro/appengine/test-deployment/common.cfg
- .kokoro/appengine/test-deployment/hello-world-flex.cfg
- .kokoro/appengine/test-deployment/hello-world-standard.cfg
- .kokoro/appengine/test-deployment/metadata-flex.cfg
- .kokoro/appengine/test-deployment/metadata-standard.cfg
- .kokoro/appengine/test-deployment/storage-flex.cfg
- .kokoro/appengine/test-deployment/storage-standard.cfg
- .kokoro/build-with-appengine.sh
Allowed values are standard and flexible. Use them for the version string.
Always deploy app.yaml, so don't specify it.
> Fix kokoro config

- .kokoro/appengine/test-deployment/hello-world-flex.cfg
- .kokoro/appengine/test-deployment/hello-world-standard.cfg
- .kokoro/appengine/test-deployment/metadata-flex.cfg
- .kokoro/appengine/test-deployment/metadata-standard.cfg
- .kokoro/appengine/test-deployment/storage-flex.cfg
- .kokoro/appengine/test-deployment/storage-standard.cfg
- .kokoro/build-with-appengine.sh
argument --version/-v: Bad value
[doc-sample-appengine/hello-world/standard-standard]: May only contain
lowercase letters, digits, and hyphens. Must begin and end with a
letter or digit. Must not exceed 63 characters.
I'll delete `APPENGINE_ENVIRONMENT` from the list of allowed environment variables in the matching job configs.
> Use valid format for App Engine version string

- .kokoro/build-with-appengine.sh
Use a shorter version string. 
Do not check for `worker.yaml`, as no sample has one.
> Simplify build script

- .kokoro/appengine/cloudsql-postgresql.cfg
- .kokoro/appengine/cloudsql.cfg
- .kokoro/appengine/endpoints.cfg
- .kokoro/appengine/errorreporting.cfg
- .kokoro/appengine/pubsub.cfg
- .kokoro/appengine/static-files.cfg
- .kokoro/cloudtasks.cfg
- .kokoro/containerengine-hello-world.cfg
- .kokoro/endpoints-getting-started.cfg
- .kokoro/error-reporting.cfg
- .kokoro/iot-manager.cfg
- .kokoro/kms.cfg
- .kokoro/language-slackbot.cfg
- .kokoro/storage-transfer.cfg
Add remaining CircleCi tests that are not yet on Kokoro.
> Migrate tests to Kokoro

- .kokoro/appengine/cloudsql-postgresql.cfg
- .kokoro/appengine/pubsub.cfg
- .kokoro/cloudtasks.cfg
- appengine/cloudsql/package.json
- containerengine/hello-world/package.json
- endpoints/getting-started/package.json
- language/slackbot/package.json
These are blocking other PRs from being merged.
> Fix failing tests

- functions/node8/package.json
- functions/node8/test/sample.unit.pubsub.test.js
- functions/node8/test/sample.unit.storage.test.js
FYI @carieshmarie - existing integration/system tests should work with both Node versions
> Add (missing) Node 8 unit tests

- functions/tips/index.js
**Do not merge** until the docs have been updated accordingly.
> Remove ephemeral agent sample + update region tag

- functions/http/index.js
**Note:** this change breaks the `uploadFile` sample in the Emulator (where `req.pipe(busboy)` is correct). @jmdobry can you investigate?
**Do not merge** until we've resolved this issue in both GCF itself and the Emulator.
> Fix busboy sample not working on GCF

- memorystore/redis/gce_deployment/deploy.sh
- memorystore/redis/gce_deployment/startup-script.sh
Removing inconsistency in setting $GCS_APP_LOCATION across languages
https://cloud.google.com/memorystore/docs/redis/connect-redis-instance-gce
> Fixing GCE deployment script for Cloud Memorystore

- kms/keys.js
Hi, 
I'm removing global location mention to generalize sample for GCS CMEK documentation. The sample is used to show developers how to set an IAM policy on a KMS key, but global location aren't supported so I' want to generalize that part of the sample.
PTAL, thank you!
> [KMS] Generalizing KMS samples for GCS docs

- README.md
This example relies on the Cloud Prediction API, which is [deprecated](https://cloud.google.com/prediction/).
**Do not merge** until [this repo](https://github.com/GoogleCloudPlatform/LabelCat) is moved to `googlearchive`.
> Remove LabelCat example

- functions/http/index.js
_Note:_ I wanted this to be Node `6.x` compliant, so I avoided using `async`/`await` in favor of Promises.
> Fix busboy + GCF race condition

- functions/sql/index.js
- functions/sql/package.json
- functions/sql/test/index.test.js
> Add GCF SQL samples

- functions/node8/index.js
- functions/node8/package.json
- functions/node8/test/index.test.js
> Add node8 firebase snippets

- functions/composer-storage-trigger/index.js
- functions/composer-storage-trigger/package.json
Sample was originally hard-coded in HTML at
https://cloud.google.com/composer/docs/how-to/using/triggering-with-gcf
Python code for target DAG is also being moved to GitHub in https://github.com/GoogleCloudPlatform/python-docs-samples/pull/1645
@TrevorEdwards Please review.
> Composer: Move 'triggering DAGs' sample to GitHub.

- functions/sql/index.js
~~**DO NOT MERGE** until the docs have been updated accordingly.~~
This merges the ["best practices" samples](https://cloud.google.com/functions/docs/sql#best_practices_for_cloud_sql_in_cloud_functions) into the existing samples.
> GCF MySQL samples: use pools instead of connections

- appengine/cloudsql/README.md
Incorrect bracket was used in the appengine/cloudsql README.
> Fix link to cloudsql

- functions/imagemagick/index.js
- functions/imagemagick/package.json
- functions/imagemagick/test/index.test.js
For consistency with the [Python samples](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/1684#discussion_r216853665)
> Use library in GCF ImageMagick tutorial

- functions/log/.gcloudignore
- functions/log/index.js
- functions/log/test/index.test.js
@stew-r FYI
This sample is designed for BigQuery, but I can make it more generic if people would like.
> GCF: Add Stackdriver trigger sample

- functions/firebase/index.js
- functions/node8/index.js
> Make firestore function work for all trigger types

- .kokoro/build.sh
- .kokoro/functions/common.cfg
- functions/helloworld/test/sample.integration.pubsub.test.js
**Do not merge** until `functions/helloworld` tests pass.
> Fix helloworld GCF test

- functions/firebase/index.js
- functions/firebase/test/index.test.js
**Note**: the corresponding Node 8 samples have not been removed. (Perhaps we should do that? Ultimately, it's optional.)
> Make functions version-agnostic

- functions/sql/index.js
It's not well documented, but the correct option for using node-postgres with a Unix socket is `host`, not `socketPath`: https://github.com/brianc/node-postgres/issues/16#issuecomment-327626885
> Fix docs — config.socketPath should be config.host

- functions/composer-storage-trigger/index.js
- functions/composer-storage-trigger/test/index.test.js
[Fix #775].
This also removes a useless POST request to the webserver and fully promisifies the function so that a callback does not need to be passed in.
> Fix promises and surface IAP errors in Composer GCF Dag triggering

- functions/node8/test/index.test.js
(Failing to pull in the latest version of `master` caused CI to pass instead of fail.)
> Fix test failure due to merge issue

- functions/ocr/app/index.js
- functions/ocr/app/package.json
- functions/ocr/app/test/index.test.js
**Question to reviewers:** this is a pretty complex sample, and the `event.data.data` vs `event.data` logic may be confusing to some readers. _Does this PR address this issue adequately?_
~~**TODO:** add comments to the sample calling out the Node 6-vs-8+ difference.~~
> OCR sample: add cross-version support

- jobs/cjd_sample/package.json
- jobs/cjd_sample/quickstart.js
Update `googleapis`, use current auth.
Refs: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/878
> Update jobs sample

- functions/slack/.gcloudignore
(To prevent `.gitignore` from being imported by the default `.gcloudignore`.)
> Add .gcloudignore file

- functions/http/.gcloudignore
- functions/http/index.js
- functions/http/package.json
- functions/http/test/index.test.js
1) Update `@google-cloud/storage` library
2) Add (system) test for `getSignedUrl`
3) Fix lint (`semistandard`)
> GCF Hello World: GCS sample tweaks

- iot/manager/manager.js
new version of `google.auth.getClient` reads from environment variables so specifying a file isn't necessary anymore. However, for backwards compatibility, we'll keep the option to pass in the JSON file but make it optional
ref: internal bug b/120968399
> iot: mark serviceAccountJson optional in getClient

- iot/beta-features/gateway/gateway.js
- iot/beta-features/gateway/gateway.test.js
- iot/manager/manager.js
Add 3 functions to gateway management
1. `unbindDeviceFromAllGateways` unbinds a single device from all gateways
2. `unbindAllDevices` unbinds all devices in a given registry (calls the above function on all devices in a registry)
3. `listGatewaysForDevice` lists all the gateways a device is bound to
1 and 2 do not have corresponding region tags since they will not be included in the docs (mostly for debugging purposes), but 3 is and has a corresponding test
> iot: update gateway association management samples

- appengine/analytics/package.json
- appengine/cloudsql_postgresql/package.json
- appengine/loopback/package.json
- appengine/metadata/flexible/package.json
- appengine/metadata/standard/package.json
- appengine/mongodb/package.json
- appengine/twilio/package.json
- endpoints/getting-started-grpc/package.json
- endpoints/getting-started/package.json
- storage-transfer/package.json
Changing a few hand-picke dependencies where we trust the minor and
patch updates. If dependency versions are fixed, we are drowning in
RenovateBot PRs.
> Auto-update minor and patch for some dependencies

- .kokoro/opencensus.cfg
- opencensus/README.md
- opencensus/metrics-quickstart.js
- opencensus/package.json
- opencensus/system-test/metrics-quickstart.test.js
Node version of https://github.com/GoogleCloudPlatform/golang-samples/pull/646/files.
> Add OpenCensus sample code

- opencensus/metrics-quickstart.js
Putting region tags ("monitoring_opencensus_metrics_dependencies") to highlight dependencies section on Stackdriver page (https://cloud-dot-devsite.googleplex.com/monitoring/custom-metrics/open-census) .
> OpenCensus sample: Add region tags

- appengine/headless-chrome/package.json
- appengine/headless-chrome/test/app.test.js
> refactor(appengine-headless-chrome):ava to mocha

- CONTRIBUTING.md
Make it clear what the purpose of the repository is and which samples
we accept.
Delete the part about the contributor agreement, as every PR has a bot
that checks for it and provides instructions as needed.
Add instructions for Kokoro config files.
Delete outdated style sample.
Refs: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1220
Stage https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/contribGuide/CONTRIBUTING.md
> Update Contributor guide

- package.json
Tests are run in individual subfolders, but we have a global
lint job.
Follow up PR that deletes the coverage output, as it's at 55% and not tracking correctly 😞
> Clean up package.json in root directory

- functions/billing/test/index.test.js
Tests were passing due to incorrectly named json data. Calling the function with an empty data message will disable billing every time
> Fix billing tests always passing

- appengine/pubsub/package.json
- appengine/pubsub/test/app.test.js
Towards #1080 
Taking over PR #1181
> refactor(appengine-pubsub):ava to mocha

- healthcare/datasets/createDataset.js
- healthcare/datasets/datasets.js
- healthcare/datasets/system-test/datasets.test.js
Dipping my toes into the water.  This is the first change for moving the healthcare samples over to the v1alpha2 version of the API.  At the same time, I'm trying to convert these to match the new style we want for samples.  Let me know what you think!
> refactor: move createDataset sample to own file

- functions/helloworld/index.js
- functions/helloworld/package.json
- functions/helloworld/shim.js
- functions/helloworld/test/index.test.js
- functions/helloworld/test/sample.integration.http.test.js
- functions/helloworld/test/sample.integration.pubsub.test.js
- functions/helloworld/test/sample.integration.storage.test.js
- functions/helloworld/test/sample.system.http.test.js
- functions/helloworld/test/sample.system.pubsub.test.js
- functions/helloworld/test/sample.system.storage.test.js
- functions/helloworld/test/sample.unit.http.test.js
- functions/helloworld/test/sample.unit.pubsub.test.js
- functions/helloworld/test/sample.unit.storage.test.js
- functions/helloworld/test/shim.test.js
Towards #1080 
refactor functions/helloworld ava to mocha
> refactor(functions/helloworld):ava to mocha

- cloud-sql/postgres/knex/package.json
- cloud-sql/postgres/knex/test/createTable.test.js
- cloud-sql/postgres/knex/test/server.test.js
Towards #1080 
refactor cloud-sql/postgres tests to mocha
> refactor(cloud-sql/postgres):ava to mocha

- functions/sql/package.json
- functions/sql/test/index.test.js
Towards #1080
refactor functions/sql ava to mocha
> refactor(functions/sql): ava to mocha

- functions/tips/package.json
- functions/tips/test/index.test.js
Towards #1080 
- refactor functions/tips tests ava to mocha
- add script to run tests
> refactor(functions/tips): ava to mocha

- opencensus/package.json
- opencensus/system-test/metrics-quickstart.test.js
Towards #1080 
refactor opencensus tests from ava to mocha.
These tests are not automatically run.
> refactor(opencensus): ava to mocha

- endpoints/getting-started/package.json
- endpoints/getting-started/test/app.test.js
towards #1080
refactor endpoints/getting-started from ava to mocha
> refactor(endpoints/getting-started): ava to mocha

- endpoints/getting-started-grpc/package.json
- endpoints/getting-started-grpc/system-test/endpoints.test.js
towards #1080 
refactor endpoints/getting-started-grpc tests from ava to mocha.
> refactor(endpoints/getting-started-grpc): ava to mocha

- functions/http/index.js
The following line is duplicate in the sample. The response header is already set on [line 247](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/compare/master...grant-functions-cors?quick_pull=1#diff-cb29a8c8153c2a5c55203eccfa98361cR247).
```js
res.set('Access-Control-Allow-Origin', '*');
```
Like the other sample, it should not be in the
```js
if (req.method === 'OPTIONS') {
```
conditional block.
Doc: https://cloud.google.com/functions/docs/writing/http#handling_cors_requests
> refactor: Remove duplicate CORS header

- functions/tips/index.js
These two snippets are reused in Cloud Run. Adding dedicated region tags for separate tracking.
x-ref: https://github.com/GoogleCloudPlatform/golang-samples/pull/831
> functions/tips: add run region tags

- functions/node8/index.js
Improve var name.
See: b/131773884
> refactor: Improve var name. b/131773884

- appengine/twilio/app.js
- appengine/twilio/package.json
- appengine/twilio/test/app.test.js
**Note:** @fhinkel I added ESLint dependencies as `devDependencies` to `package.json` - let me know if I shouldn't do that.
> Update Twilio sample + add (unit) tests

- appengine/sendgrid/app.js
- appengine/sendgrid/package.json
- appengine/sendgrid/test/app.test.js
- appengine/sendgrid/views/index.pug
**Note:** this does not include any additional Kokoro configs. @fhinkel happy to add one if you'd like.
(The other option that I think would be cleaner: we update the samples + add tests now, and fix Kokoro in another PR.)
> Update Sendgrid sample + add tests

- .kokoro/build.sh
> Add env vars for twilio tests

- .kokoro/build.sh
- appengine/memcached/.cloud-repo-tools.json
- appengine/memcached/package.json
- appengine/sendgrid/.cloud-repo-tools.json
- appengine/sendgrid/package.json
- appengine/sendgrid/test/app.test.js
The sample _wasn't actually running_ in the testing environment - `nodejs-repo-tools` should fix that. 🙂
Fixes b/132694066
> Use nodejs-repo-tools for testing Sendgrid sample

- .eslintrc.yml
- package.json
**Do not merge** until samples have been updated to conform to these standards.
> Add Node 8 standards to linter

- .eslintrc.yml
- appengine/analytics/app.js
- appengine/cloudsql/createTables.js
- appengine/cloudsql/server.js
- appengine/cloudsql/test/createTables.test.js
- appengine/cloudsql/test/server.test.js
- appengine/cloudsql_postgresql/createTables.js
- appengine/cloudsql_postgresql/server.js
- appengine/cloudsql_postgresql/test/createTables.test.js
- appengine/cloudsql_postgresql/test/server.test.js
- appengine/datastore/app.js
- appengine/endpoints/app.js
- appengine/endpoints/test/app.test.js
- appengine/mailjet/app.js
- appengine/metadata/flexible/server.js
- appengine/metadata/standard/server.js
- appengine/pubsub/app.js
- appengine/pubsub/test/app.test.js
- appengine/twilio/test/app.test.js
**Note:** this change adds a rule preferring function expressions (as a `warning`).
(As an example: `func baz(quux) { ... }` --> `const baz = (quux) => { ... }`)
> More GAE lintfixes + prefer function expressions

- appengine/headless-chrome/app.js
- appengine/headless-chrome/app.yaml
Fixes https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/834.
See cl/252516607
> fix: Fixes GAE headless chrome region tags. See #834

- memorystore/redis/README.md
> Update Redis README

- appengine/building-an-app/update/package.json
mocha v4 no longer ends itself when all the tests are finished; with HTTP samples continuing to listen at 8080 the tests will run forever.
> Force mocha to exit after running all tests

- functions/http/index.js
Inline function handlers like in Go and Python. It looks weird (and is unnecessary) having standalone functions.
See:
https://cloud.google.com/functions/docs/writing/http#handling_http_methods
> fix: Make functions_http_method consistent with other samples

- .kokoro/functions/datastore.cfg
- functions/datastore/index.js
- functions/datastore/package.json
- functions/datastore/test/index.test.js
- functions/datastore/test/updateFunctions.sh
As title.
@fhinkel (and @grant) please review _no sooner than Friday morning_. 🙂
> functions/datastore Node 8 upgrade

- .kokoro/build-with-run.sh
Cloud Run release testing does not rely on a PR. The `.kokoro/build-with-run.sh` script names a service with a hard dependency on a PR-specific environment variable. As a result, end-to-end tests attempt to deploy with an invalid name (e.g., `sample-name-`).
This PR adjusts the construction of the service name to fall back to the first 12 characters of the commit hash of the change if the PR environment variable is not available.
> kokoro/run: fallback from PR # to commit in service name

- appengine/hello-world/standard/app.js
- appengine/hello-world/standard/package.json
- appengine/hello-world/standard/test/app.test.js
Trying to remove `repo-tools`. Will send a follow up PR that removes `repo-tools test deploy`. 
Ref: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1247
> Use supertest instead of repo-tools test app

- functions/imagemagick/index.js
The reassignment of the event parameter to const object seems superfluous without realizing its meant to help the developer read the following lines as an interaction with a Cloud Storage object. Adding a comment to establish this.
> Cloud Functions: ImageMagick: Explain object var

- functions/scheduleinstance/index.js
Functions documentation are not up-to-date and doesn't reflect the functions behaviors.
I tried to fix it.
> Update scheduleinstance functions doc

- appengine/endpoints/app.js
- appengine/endpoints/package.json
- appengine/endpoints/test/app.test.js
- appengine/pubsub/app.js
- appengine/pubsub/package.json
- endpoints/getting-started/app.js
- endpoints/getting-started/package.json
- endpoints/getting-started/test/app.test.js
- functions/helloworld/index.js
- functions/helloworld/package.json
- functions/helloworld/test/index.test.js
- functions/http/package.json
- functions/http/test/index.test.js
- functions/ocr/app/index.js
- functions/ocr/app/package.json
- functions/ocr/app/test/index.test.js
- functions/pubsub/index.js
- functions/pubsub/package.json
- functions/pubsub/test/index.test.js
- functions/scheduleinstance/index.js
- functions/scheduleinstance/package.json
- functions/scheduleinstance/test/index.test.js
- functions/sendgrid/index.js
- functions/sendgrid/package.json
- functions/tips/package.json
- jobs/v3/package.json
`safe-buffer` is not needed in Node 8 anymore, we can safely use native
Buffer.from(). See
https://nodejs.org/fr/docs/guides/buffer-constructor-deprecation/
> Use native Buffer.from()

- functions/README.md
Remove list of samples. It doesn't add any value in addition to the directories listed above and it's easily out of date. 
Remove comment about Node 6 as many samples need Node 8 to run now.
> Update README.md for functions/

- functions/imagemagick/index.js
When I run the index.js code from the Functions imagemagick sample in Cloud Run on a Node 10 container, I get the following error:
```
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function 
at makeCallback (fs.js:136:11) 
at Object.unlink (fs.js:943:14) 
at blurImage (/usr/src/app/image.js:106:23) 
at process._tickCallback (internal/process/next_tick.js:68:7) 
```
Looking at the current promisify implementation around fs.unlink, it differs from what I've read in trying to return the result of the promisify. Taking a note from https://dev.to/mrm8488/from-callbacks-to-fspromises-to-handle-the-file-system-in-nodejs-56p2, with this change I do not see any errors.
> functions/imagemagick: fix "callback must be a function" error

- .kokoro/datacatalog/cloud-client/lookup-entry.cfg
- datacatalog/cloud-client/README.md
- datacatalog/cloud-client/lookupEntry.js
- datacatalog/cloud-client/package.json
- datacatalog/cloud-client/system-test/datacatalog.test.js
Adding samples to Data Catalog lookup_entry, according to #1447
> Add samples for Data Catalog lookupEntry

- iot/manager/manager.js
- iot/manager/package.json
- iot/manager/system-test/manager.test.js
This fixes some issues with upgrading to yargs v14.0.0:
1. Positional arguments were removed from `createGateway` sample. This is more in line with other samples, and will require migrating other samples to a similar format. For the sake of unblocking #1454, this is the only sample changed for now.
2. Use a single non-whitespaced string for `sendCommand` sample, such that yargs does not interpret the command sting as multiple arguments.
This change also updates the gateway samples + tests such that includes specifying [gateway auth method] (https://cloud.google.com/iot/docs/reference/cloudiot/rest/v1/projects.locations.registries.devices#gatewayauthmethod) which was previously missing.
> iot: update samples for yargs v14.0.0

- run/image-processing/Dockerfile
- run/image-processing/README.md
- run/logging-manual/Dockerfile
- run/logging-manual/package.json
- run/pubsub/.envrc
- run/pubsub/Dockerfile
- run/pubsub/README.md
To minimize size and number of security vulnerability in Cloud Run samples, we're switching to the slim version.
This PR also removes node-repo-tools from the logging sample, standardizes the use of --production, and standardizes the note about when to use `npm ci`.
> run: use node:10-slim

- functions/log/index.js
- functions/log/test/index.test.js
Node 6 is deprecated.
Remove hacks.
> refactor: No more data.data.data

- functions/node8/index.js
Remove unused and non-unique sample 1373.
> refactor: Remove functions_tips_terminate_node8

- run/pubsub/README.md
> Fix link to the Node.js Cloud Run sample readme

- appengine/cloudsql/test/createTables.test.js
- appengine/cloudsql/test/server.test.js
- appengine/cloudsql_postgresql/test/createTables.test.js
- appengine/cloudsql_postgresql/test/server.test.js
- appengine/hello-world/flexible/test/app.test.js
- appengine/hello-world/standard/test/app.test.js
- appengine/pubsub/test/app.test.js
- appengine/sendgrid/test/app.test.js
- appengine/twilio/test/app.test.js
- appengine/websockets/test/index.test.js
**Note:** some of these samples don't have _region tags_ and/or _test files_. (In the latter case, they sometimes use [`repo-tools test app`](https://github.com/GoogleCloudPlatform/nodejs-repo-tools).)
Those files were **excluded** from this PR.
> Region tags -> tests: AppEngine

- functions/helloworld/README.md
Package.json uses functions framework now.
Ref https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1333
> Update hello-world Readme

- run/hello-broken/README.md
- run/image-processing/README.md
- run/logging-manual/README.md
- run/system-package/README.md
> Fix links to Google cloud run main readme in all examples

- functions/speech-to-speech/.nvmrc
- functions/speech-to-speech/README.md
Updates README of the speech-to-speech sample with instructions that use the Functions Framework instead of the Functions emulator.
The speech-to-speech sample was updated to replace the Functions emulator in #1255.
This fixes #1500.
> Replaces outdated instructions that reference the Functions emulator.

- functions/scheduleinstance/README.md
I found a broken link in the README .
This is when the link is deleted .
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/commit/66dcad86a4e910c937f9161a385d111a651c405b#diff-04c6e90faac2675aa89e2176d2eec7d8
As a result of checking the contents, you may delete the wording of README
> Delete dead link on README

- cloud-sql/mysql/mysql/Dockerfile
- cloud-sql/mysql/mysql/README.md
- cloud-sql/mysql/mysql/server.js
- run/README.md
This PR originally intended just the following:
* Adds a Dockerfile to the MySQL sample for use with Cloud Run, based on the Dockerfiles used in the Cloud Run samples.
* Adds README instructions on deployment to Cloud Run.
* Adds the sample to the list of [Node.js Cloud Run samples](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/run/README.md).
In the course of the Cloud Run work, I found the current state of the sample is broken. This PR includes fixes for those problems:
1. promise-mysql in v4 returns a promise from `mysql.createPool()`. pool instantiation in the master implementation cannot have worked since the library update. Fix: Hacky top-level async.
2. The code executed in `app.on('listening', async () => {`... is not being fired (express 4, node 10), …
> Cloud SQL (MySQL): Add Cloud Run support and fix broken implementation

- .kokoro/run/hello-broken.cfg
- run/hello-broken/package.json
- run/hello-broken/test/deploy.sh
- run/hello-broken/test/system.test.js
run/hello-broken is consistently failing with nothing in the invocation log. This PR is intended to evolve until the test is passing.
> run: fix hello-broken testing

- functions/concepts/index.js
- functions/concepts/package.json
[`request` is being deprecated](https://github.com/request/request/issues/3143) - so let's use `node-fetch` instead.
> Fix HTTP package being deprecated

- functions/ocr/app/index.js
- functions/ocr/app/package.json
- functions/speech-to-speech/functions/index.js
- functions/speech-to-speech/functions/package.json
* Updates [google-cloud/translate][1] dependency to version `5.0.0`.
* Updates declaration of clients to specify the version 2 of the API instead of
the version 3, which is the default in the Translate library.
Note: The google-cloud/translate library made v3 the default in https://github.com/googleapis/nodejs-translate/pull/355
[1]: https://github.com/googleapis/nodejs-translate
> Updates speech-to-speech and ocr-app samples.

- functions/ci_cd/cloudbuild.yaml
Adds a region tag to the cicd yaml.
b/144764433
Page:
https://cloud.google.com/functions/docs/testing/test-cicd
> feat: add functions_ci_cd_cloud_build_nodejs region tag

- cloud-sql/mysql/mysql/app.standard.yaml
- cloud-sql/mysql/mysql/package.json
- cloud-sql/mysql/mysql/test/server.test.js
* Update Node version to 10 for GAE Standard.
* Delete repo-tools.
* Clean up package.json
> Update cloud-sql/mysql sample

- appengine/storage/flexible/system-test/app.test.js
- appengine/storage/standard/system-test/app.test.js
- auth/system-test/auth.test.js
- functions/helloworld/test/index.test.js
- healthcare/datasets/system-test/datasets.test.js
- healthcare/dicom/system-test/dicom_stores.test.js
- healthcare/dicom/system-test/dicomweb.test.js
- healthcare/fhir/system-test/fhir_resources.test.js
- healthcare/fhir/system-test/fhir_stores.test.js
- healthcare/hl7v2/system-test/hl7v2_messages.test.js
- healthcare/hl7v2/system-test/hl7v2_stores.test.js
- iot/http_example/system-test/cloudiot_http_example.test.js
- iot/manager/system-test/manager.test.js
- iot/mqtt_example/system-test/cloudiot_mqtt_example.test.js
We want to remove the nodejs-repo-tools dependency. Doing so step by step.
Drive-by fix: Rename `utils` to `tools` for consistency.
> Remove tools.checkCredentials()

- cloud-sql/postgres/knex/server.js
- iot/manager/manager.js
Migrates the create / delete device snippets to Cloud Client library
> Cloud client library migration part 2: Device creation / deletion

- .kokoro/appengine/common.cfg
- .kokoro/functions/common.cfg
Export XUnit results now that `functions` (#1499) and `appengine` (#1504) have been labeled for the test tracker.
> functions + appengine: export XUnit results

- datastore/functions/README.md
- functions/helloworld/README.md
- functions/imagemagick/README.md
- functions/pubsub/README.md
gcloud requires a `--runtime` argument when deploying new functions, otherwise the user sees:
`ERROR: (gcloud.functions.deploy) Missing required argument [runtime]: Flag `--runtime` is required for new functions.`
This addition is consistent with the tutorial (https://cloud.google.com/functions/docs/tutorials/http).
> Add --runtime argument to gcloud deploy in README.

- functions/background/index.js
- functions/background/package.json
- functions/background/test/index.test.js
Request is now [deprecated](https://www.npmjs.com/package/request).  This moves the sample over to using `gaxios`, along with other cleanup.
> fix: reduce request usage

- functions/helloworld/test/sample.integration.http.test.js
**N.B:** this causes the unit test block itself to be indented. @labtopia we should fix that in the docs (using the `adjust_indentation` parameter - see my comment on the bug).
Or if we can't (e.g. because indentation is not consistent throughout the file), we may have to add a `describe` statement anyway. If it comes to that, we should try to exclude the region tag labeling. 🙂
> Remove extra parenthesis from region tag

- README.md
Please do not merge manually, we are trying out the auto-merge bot. 
@sofisl would the bot respect the `do-not-merge` label?
> Update Node.js version in Readme

- .kokoro/build-with-appengine.sh
- .kokoro/build-with-run.sh
- .kokoro/build.sh
Fixes: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1615
> chore: configure buildcopbot

- .kokoro/build-with-appengine.sh
- .kokoro/build-with-run.sh
- .kokoro/build.sh
`KOKORO_BUILD_ARTIFACTS_SUBDIR` is based on the job name.
> fix: publish to Build Cop for release jobs

- run/logging-manual/README.md
- run/logging-manual/test/system.test.js
Fixes #1637
run/logging-manual tests started failing due to a compatibility break in upgrading to `got v10` #1557. This was not caught because the broken `got` feature is only used in system tests.
> fix(tests): run/logging-manual test failures (#1637)

- .kokoro/build-with-appengine.sh
- .kokoro/build-with-run.sh
Fixes #1682. Follow-up to #1634 
Integration with buildcop bot clobbered existing test cleanup process for Cloud Run and App Engine.
> fix(testing): ensure resource cleanup happens on GAE and Cloud Run tests

- .kokoro/functions/security.cfg
- functions/security/index.js
- functions/security/package.json
- functions/security/test/index.test.js
✅Tested manually
~**TODO** add automated [smoke] test~
(_Properly_ testing this would require deploying it 😢)
> GCF: add bearer-auth sample

- functions/http/index.js
Given that we added this note in the [Java sample](https://github.com/GoogleCloudPlatform/java-docs-samples/pull/2688), I thought it was worth adding here.
> Add "gcf filesystem is not persistent" note

- healthcare/fhir/createFhirStore.js
- healthcare/fhir/deleteFhirResource.js
- healthcare/fhir/deleteFhirResourcePurge.js
- healthcare/fhir/deleteFhirStore.js
- healthcare/fhir/exportFhirResources.js
- healthcare/fhir/fhir_resources.js
- healthcare/fhir/getFhirResource.js
- healthcare/fhir/getFhirResourceHistory.js
- healthcare/fhir/getFhirStore.js
- healthcare/fhir/getFhirStoreCapabilities.js
- healthcare/fhir/getFhirStoreIamPolicy.js
- healthcare/fhir/getPatientEverything.js
- healthcare/fhir/importFhirResources.js
- healthcare/fhir/listFhirResourceHistory.js
- healthcare/fhir/listFhirStores.js
- healthcare/fhir/package.json
- healthcare/fhir/patchFhirStore.js
- healthcare/fhir/searchFhirResourcesGet.js
- healthcare/fhir/searchFhirResourcesPost.js
- healthcare/fhir/setFhirStoreIamPolicy.js
- healthcare/fhir/system-test/fhir_resources.test.js
- healthcare/fhir/system-test/fhir_stores.test.js
- healthcare/fhir/updateFhirResource.js
- healthcare/hl7v2/package.json
> healthcare API: update FHIR samples from v1beta1 to v1

- functions/log/index.js
- functions/log/test/index.test.js
Not used in the docs any more.
> GCF: delete extraneous getmetrics sample

- healthcare/hl7v2/patchHl7v2Store.js
notificationConfig{} was deprecated in favor of notificationConfigs[].
> healthcare API: use new request body for notificationConfigs when patching HL7v2 store

- functions/http/index.js
At the busboy.on('finish') event, looping the uploads object with for...of will throw a "uploads is not iterable" error because for...of does not work on objects. The correct for-loop to use here will be for...in
> Change for...of to for...in

- appengine/storage/standard/README.md
- appengine/storage/standard/system-test/app.test.js
GOOGLE_APPLICATION_CREDENTIALS are not needed, and should not be downloaded unless absolutely necessary.
> Reference how to test, and remove unneeded step

- functions/slack/index.js
> Use correct GCF URL in Slack sample

- .kokoro/cloudsql-sqlserver.cfg
- cloud-sql/sqlserver/mssql/README.md
- cloud-sql/sqlserver/mssql/app.yaml
- cloud-sql/sqlserver/mssql/package.json
- cloud-sql/sqlserver/mssql/server.js
- cloud-sql/sqlserver/mssql/test/server.test.js
- cloud-sql/sqlserver/mssql/views/index.pug
> feat(cloud-sql): Add connection sample for SQL Server/node-mssql

- run/pubsub/app.js
By adding this into the snippet the tutorial facilitates copy-and-paste to assemble the working node.js service. While not the intent in the structure of the tutorial this has been asked for and is a minor change.
> run: Include `module.exports = app;` in snippet

- .kokoro/build.sh
For integration testing of connectivity samples. This PR is blocking #1745 from being merged.
> feat: Update .kokoro/build.sh to run proxy when testing Cloud SQL samples

- endpoints/getting-started-grpc/package.json
- endpoints/getting-started-grpc/system-test/endpoints.test.js
Fix: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1684
> chore: fix endpoints-grpc system test

- storage-transfer/system-test/transfer.test.js
- storage-transfer/test/transfer.test.js
- storage-transfer/transfer.js
> storagetransfer: update to use latest auth.getClient

- functions/speech-to-speech/functions/package.json
The Cloud Speech library version 4 requires Node.js version 10 or greater.
This PR updates the speech-to-speech sample to use Node version 10.
> Specify Node.js engine 10 or greater

- .kokoro/functions/speech-to-speech.cfg
- functions/speech-to-speech/functions/package.json
This PR includes the following changes:
* Updates the `google-cloud/speech` dependency to version `4.0.0`.
* Updates the Kokoro configuration to use the Node.js 10 Docker image.
> Update speech sample to use Cloud Speech dependency v4.0.0

- run/events-pubsub/index.js
Region tag specified run_pubsub_server but the tag should actually specify run_events_pubsub_server
> Fixed region tag in run/events-pubsub/index.js

- memorystore/redis/.gcloudignore
- memorystore/redis/cloud_run_deployment/Dockerfile
I'm working on a tutorial for connecting to Memorystore from Cloud Run via Serverless VPC Access. The existing sample app still works, we just need a Dockerfile to deploy it. Also adding a `.gcloudignore`.
> Memorystore: Add Dockerfile for Cloud Run deployment

- run/markdown-preview/editor/test/system.test.js
> Update retry number for test request

- run/markdown-preview/editor/render.js
The region tag placement is excluding the import statements, which are very important. Also, unlike the other languages this is hiding that it's wrapped in a function, which the language in the tutorial implies.
> fix(run/markdown-preview): region tags should encompass imports

- run/README.md
A little housekeeping here:
* Reorder samples to move events down
* Remove "external repo" marker from helloworld
* Switch helloworld run-button to use this repo
* Switch events repo links to not use run-button link
> docs(run): Reflow index and remove knative reference

- README.md
The Slack button on this repo has been broken for months. Reported here:
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1820
We should just link to the GCP slack group.
> docs: update slack url. fixes #1820

- functions/helloworld/package.json
Removes supertest from a sample's deps (`functions/helloworld/package.json`). Should be dev deps.
Related: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1983
> feat: remove supertest from deps

- functions/pubsub/README.md
Improving documentation on checking logs of running google cloud function called subscribe.
> chore(functions/pubsub): update gcloud command

- eventarc/generic/.dockerignore
- eventarc/generic/Dockerfile
- eventarc/generic/app.js
- eventarc/generic/index.js
- eventarc/generic/package.json
- eventarc/generic/test/app.test.js
- eventarc/generic/test/deploy.sh
- eventarc/generic/test/runner.sh
- eventarc/generic/test/system.test.js
- eventarc/generic/test/url.sh
- Adds a generic Eventarc sample
- Re-uses same setup as other Eventarc samples
- Logs and returns request headers and body. Deletes auth header (if present).
- Tests that: headers and body are logged except auth header
- Tested locally
Fixes https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1989
> feat: add eventarc generic sample

- .eslintrc.json
- cloud-sql/sqlserver/mssql/server.js
- functions/http/package.json
- functions/http/test/index.test.js
- healthcare/datasets/system-test/datasets.test.js
- healthcare/fhir/patchFhirResource.js
- jobs/v4/job_search_create_client_event.js
Turn on the rule and fix lint problems.
see https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/2030
> chore: activate no-unused-vars eslint rule

- .eslintrc.json
- cloud-sql/mysql/mysql/server.js
- cloud-sql/sqlserver/mssql/server.js
- eventarc/audit-storage/test/system.test.js
- eventarc/generic/test/system.test.js
- eventarc/pubsub/test/system.test.js
- run/hello-broken/package.json
- run/hello-broken/test/system.test.js
- run/helloworld/package.json
- run/helloworld/test/system.test.js
- run/image-processing/test/system.test.js
- run/markdown-preview/renderer/test/system.test.js
- run/pubsub/test/system.test.js
- run/system-package/package.json
- run/system-package/test/system.test.js
activate `no-process-exit lint` rule
activate `no-process-exit` rule
See https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/2030
> chore: activate more eslint rules

- functions/security/test/index.test.js
Fixes https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/2027
> chore: replace strictEqual with deepStrictEqual

- eventarc/pubsub/package.json
Fixes error in releasing the library. We shouldn't be using the head library anyways.
> fix: pin events library to specific version

- .kokoro/build-with-run.sh
- run/idp-sql/static/firebase.js
- run/logging-manual/package.json
- run/markdown-preview/editor/test/system.test.js
Also extends timeout for another flaky test and removes unneeded container build from Kokoro.
Fixes #2139
> Extend retries for Run tests

- .kokoro/build-with-run.sh
cleanup function no longer used. Run's system tests clean up after themselves.
> fix: remove cleanup call

- functions/security/index.js
Due to differences in implementation, there can be issues if
the metadata server isn't fully qualified in code. This
minor fix resolves that issue.
Related b/154412754.
> fix(functions): add fully qualified domain name for metadata sample

- functions/slack/index.js
The relevant Slack API client library method directly throws an exception anyway. (See b/171900608 for details.)
> chore(functions): remove unused exception handler

- eventarc/audit-storage/app.js
- eventarc/audit-storage/test/app.test.js
Uses "Cloud Storage" instead of "GCS" for Eventarc Audit quickstart per branding guidelines.
See internal b/180109929
> fix: update eventarc storage name

- CODEOWNERS
Missed this folder when I added the team for Codeowners.
> Add owners to cloud-sql folder

- appengine/building-an-app/update/package.json
- appengine/building-an-app/update/server.js
- appengine/endpoints/app.js
- appengine/endpoints/package.json
- appengine/endpoints/test/app.test.js
- appengine/pubsub/app.js
- appengine/pubsub/package.json
- appengine/storage/flexible/app.js
- appengine/storage/flexible/package.json
- appengine/storage/standard/app.js
- appengine/storage/standard/package.json
- appengine/twilio/app.js
- appengine/twilio/package.json
- cloud-sql/mysql/mysql/package.json
- cloud-sql/mysql/mysql/server.js
- cloud-sql/postgres/knex/package.json
- cloud-sql/postgres/knex/server.js
- cloud-sql/sqlserver/mssql/package.json
- cloud-sql/sqlserver/mssql/server.js
- endpoints/getting-started/app.js
- endpoints/getting-started/package.json
- run/image-processing/README.md
- run/image-processing/app.js
- run/image-processing/package.json
Removed body-parser from all samples and used internal express.json functionality as this middleware is available in Express v4.16.0 onwards
> Replaced all occurrences of body-parser from the samples

- appengine/pubsub/app.js
This snippet is used in the Cloud Pub/Sub docs (https://cloud.google.com/pubsub/docs/push#validating_tokens) and many users are not aware that signature verification of the token is not enough, the claim needs to be validated also.
> Add comment about authenticated push JWT token validation.

- .github/blunderbuss.yml
- CODEOWNERS
Updates the CODEOWNERs file and Blunderbuss config for new teamsync managed groups
Before merging, please make sure the follow teams have write access for this repo:
> Update CODEOWNERS / Blunderbuss for SoDA teams

- functions/slack/index.js
- functions/slack/package.json
- functions/slack/test/index.test.js
We've split the `googleapis` module so individual services are now installable.  This should drastically reduce the number of PRs we get for renovate updates, and make things faster.
> fix(functions/slack): use @googleapis/kgsearch module

- functions/pubsub/test/index.test.js
Band-aid fix for #2257
(If this doesn't fix the issue, we'll have to dig a bit deeper.)
> chore(functions/pubsub): increase test timeout

- functions/billing/index.js
- functions/billing/package.json
This replaces the usage of the `googleapis` module for billing with the newer `@google-cloud/billing` module.  There will be followup PRs to a.) remove the usage of `googleapis` for compute and b.) to remove the usage of `request` in this sample.
> fix(functions/billing): use @google-cloud/billing module

- functions/billing/package.json
- functions/billing/test/index.test.js
- functions/billing/test/periodic.test.js
The `request` module is fully deprecated, and we shouldn't be using it.  This transitions us to `gaxios` for tests, which we actively support.
> fix(functions/billing): remove usage of request module

- monitoring/opencensus/package.json
In pursuit of removing `request` dependencies, I ran across these samples that weren't using most of the dependencies.  There are no material code changes here.
> fix(opencensus): remove unused dependencies

- run/markdown-preview/editor/templates/index.html
* Pin material to v11
* Use new fullwidth guide "width: 100%"
This is a fix propagating from https://github.com/GoogleCloudPlatform/golang-samples/pull/2149
> fix(run/markdown-preview): full width input form

- run/websockets/public/index.html
To reduce user confusion, this minor change ensures the compute platform being used for this sample matches the title of the sample app. 
cc @averikitsch
> minor: Update title to reflect compute platform

- endpoints/getting-started/deployment.yaml
kind "Deployment" no longer exists in "extensions/v1beta1", a change in version to "apps/v1" would have fixed the issue.
Fixes #2334 🦕
> fix: replace extensions/v1beta1 with apps/v1

- functions/v2/index.js
- functions/v2/package.json
- functions/v2/test/autoLabelInstance.test.js
- functions/v2/test/system.test.js
Notes:
1. This sample has an E2E test _only_. This is currently disabled, as I don't think the testing project is configured for V2. (We should enable it once GCF V2 is available within that project, **provided** we're OK with a non-GA platform being tested.)
2. This uses an alpha version of the GCE Client Library. We'll need to replace that once the library goes GA.
> feat(functions/v2): add GCE + CAL sample

- cloud-sql/mysql/mysql/README.md
- cloud-sql/mysql/mysql/package.json
- cloud-sql/mysql/mysql/server.js
- cloud-sql/postgres/knex/README.md
- cloud-sql/postgres/knex/package.json
- cloud-sql/postgres/knex/server.js
- cloud-sql/sqlserver/mssql/README.md
- cloud-sql/sqlserver/mssql/package.json
- cloud-sql/sqlserver/mssql/server.js
This PR adds the option to retrieve the Cloud SQL database password from Secret Manager.
If a secret version is defined in an environmental variable (`CLOUD_SQL_CREDENTIALS_SECRET`), the secret value is retrieved from Secret Manager and then used in the Cloud SQL connection.
The sample can continue to work as-is for testing / non-production use by defining the password in an environment variable.
An upcoming tutorial in the [Cloud Architecture Center](https://cloud.google.com/architecture) will show a complete example of creating a Secret Manager secret, deploying Cloud SQL, and then running this sample app with the proposed changes to tie it all together.
> Add Secret Manager integration to Cloud SQL sample apps

- eventarc/audit-storage/package.json
- eventarc/generic/package.json
- eventarc/pubsub/package.json
- run/hello-broken/package.json
- run/helloworld/package.json
- run/idp-sql/package.json
- run/image-processing/package.json
- run/logging-manual/package.json
- run/markdown-preview/editor/package.json
- run/markdown-preview/renderer/package.json
- run/pubsub/package.json
- run/system-package/package.json
- run/websockets/package.json
Reverts GoogleCloudPlatform/nodejs-docs-samples#2460
This requires ESM, which we're not quite ready to move to.
> Revert "chore(deps): update dependency got to v12"

- functions/v2/cloud-event-logging/index.js
- functions/v2/cloud-event-logging/package.json
- functions/v2/cloud-event-logging/test/index.test.js
Structured logging http for GCFv2
**To run sample:**
1)  You will need to create a pubsub topic to test this sample. 
`gcloud pubsub topics create YOUR_TOPIC_NAME `
1) Execute below commands in either local terminal or cloud shell.
```
npm i
gcloud beta functions deploy nodejs-pubsub-function --gen2 --runtime nodejs16 --trigger-topic YOUR_TOPIC_NAME --entry-point structuredLoggingEvent --source . --project YOUR_PROJ
```
2) After successful deployment, trigger the function w/ empty message.
`gcloud pubsub topics publish my-logging-topic --message=""`
3) Open up logs and verify `Hello, world!` has logged and that you are able to see something similar to below.
4) Run unit test via `npm run test`
> feat: adding cloud event structured logging sample

- functions/v2/cloudEventLogging/test/index.test.js
- functions/v2/http-logging/test/index.test.js
This should fix the `ci-region-tags` failures.
> chore(functions/v2): fix failing region tag check

- functions/memorystore/redis/index.js
**Issue:** Resolves following issue in sample.
`Error: The client is closed at Commander._RedisClient_sendCommand `
Breaking change introduced in [node-redis](https://github.com/redis/node-redis) v4. 
Changelog: https://github.com/redis/node-redis/blob/master/CHANGELOG.md#v400---24-nov-2021
Related: https://github.com/redis/node-redis/issues/1780
**Resolution:** Updating config and calling `.connect()` as described in updated [specs](https://github.com/redis/node-redis/blob/master/docs/client-configuration.md).
**To reproduce error:**
* Follow the sample directions here (https://cloud.google.com/memorystore/docs/redis/connect-redis-instance-functions#node.js)
* Calling the final function's URL `https://[REGION]-[PROJECT_ID].cloudfunctions.net/visitCount` and you will see the the client …
> fix(redis): update object passed to createClient to match node-redis v4 specs

- appengine/hello-world/flexible/package.json
update node version to LTS because app engine flex does not support >= 18.
> fix: Update node version to LTS because app-engine flex does not support node >= 18

- monitoring/prometheus/README.md
**Issue:** Should resolve the `JustinBeckwith/linkinator` github doc action. Updating broken svg link.
> fix: github action doc failures for missing prometheus svg

- CODEOWNERS
@GoogleCloudPlatform/nodejs-samples-reviewers should be reviewing PRs @GoogleCloudPlatform/nodejs-docs-samples-owners is responsible for repo ownership
Elimination of some individual ownership that should be team ownership migration of aap-dpes to torus-dpe 
adding TORuS DPE responsible repos.
> fix: codeowners needs to be based on teams

- cloud-sql/mysql/mysql/README.md
- cloud-sql/mysql/mysql/app.standard.yaml
- cloud-sql/postgres/knex/README.md
- cloud-sql/postgres/knex/app.standard.yaml
- cloud-sql/sqlserver/mssql/README.md
- Changes Cloud SQL MySQL sample's `app.standard.yaml` file to use nodejs16 runtime due to `gcloud.app.deploy` INVALID_ARGUMENT: Invalid runtime error. 
- Remove unnecessary `beta_settings` element from Cloud SQL Postgres sample's `app.standard.yaml` file.
- Link to yaml files from README files.
> Update Cloud SQL sample App Engine yaml and README

- CONTRIBUTING.md
This PR adds instructions for creating new GitHub Actions workflows, which are currently not included in CONTRIBUTING.md.
> docs: Add GitHub Actions instructions to CONTRIBUTING.md

- .github/workflows/generate.js
- CONTRIBUTING.md
The workflow generation script currently creates all workflows, every time it is run.
This minor change enables an extra optional parameter with the workflow title, e.g. `cloud-tasks`.
A workflow will only be generated if it matches that parameter. If the parameter is not specified, the behavior remains the same, generating all workflows.
> ci: add option to generate one workflow

- .github/workflows/workflows.json
- .github/workflows/workflows.yaml
- workflows/README.md
- workflows/create-execution.js
- workflows/package.json
- workflows/quickstart.js
- workflows/test/create-execution.js
- workflows/test/quickstart.js
- feat!: initial library generation (#8)
- chore: release 1.0.0 (#11)
- chore: release 1.0.1 (#21)
- chore: release 1.0.2 (#24)
- chore: release 1.1.0 (#31)
- chore: release 1.2.0 (#53)
- chore: release 1.2.1 (#62)
- chore: release 1.2.2 (#70)
- chore: release 1.2.3 (#76)
- chore: release 1.2.4 (#79)
- chore: release 1.2.5 (#81)
- chore: release 1.2.6 (#88)
- chore: release 1.3.0 (#90)
- fix(build): migrate to using main branch (#92)
- chore: release 1.3.1 (#93)
- chore: release 1.4.0 (#107)
- build!: update library to use Node 12 (#140)
- chore(main): release 2.0.0 (#142)
- chore(main): release 2.1.0 (#147)
- chore(main): release 2.1.1 (#157)
> migrate code from googleapis/nodejs-workflows

- CODEOWNERS
> chore(container-analysis): add DEEPO to CODEOWNERS

- .github/workflows/ci.yaml.njk
This issue updates the template for #2796, #2814, and an internal issue.
This PR does not re-generate existing workflows using this template, as there are currently many outstanding PRs. It will ensure that future PRs have these changes. We can keep #2796 open until we've re-generated workflows.
> ci: update workflow template

- profiler/app.js
- profiler/package.json
- profiler/snippets.js
- Add samples with snippets for documentation (#333)
- build: add lint script (#362)
- chore: update license headers
- build!: require node.js 10.x and up (#623)
- chore: release 4.0.0 (#586)
- chore: release 4.0.1 (#635)
- chore: release 4.0.2 (#667)
- chore: release 4.0.3 (#672)
- chore: release 4.1.0 (#711)
- chore: release 4.1.1 (#723)
- chore: release 4.1.2 (#734)
- chore: release 4.1.3 (#755)
- chore: release 4.1.4 (#764)
- chore: release 4.1.5 (#774)
- chore: release 4.1.6 (#785)
- chore: release 4.1.7 (#786)
- chore(main): release 4.2.0 (#834)
- build!: update library to use Node 12 (#835)
- chore(main): release 5.0.0 (#839)
- chore(main): release 5.0.1 (#848)
- chore(main): release 5.0.2 (#850)
- chore(main): release 5.0.3 (#853)
> migrate code from googleapis/cloud-profiler-nodejs

- .github/workflows/datacatalog-snippets.yaml
- .github/workflows/workflows.json
- datacatalog/snippets/.eslintrc.yml
- datacatalog/snippets/createCustomEntry.js
- datacatalog/snippets/createFileset.js
- datacatalog/snippets/grantTagTemplateUserRole.js
- datacatalog/snippets/package.json
- datacatalog/snippets/policyTagManager/createPolicyTag.js
- datacatalog/snippets/policyTagManager/createTaxonomy.js
- datacatalog/snippets/policyTagManager/deleteTaxonomy.js
- datacatalog/snippets/policyTagManager/getTaxonomy.js
- datacatalog/snippets/policyTagManager/listTaxonomies.js
- datacatalog/snippets/quickstart.js
- datacatalog/snippets/searchAssets.js
- datacatalog/snippets/test/.eslintrc.yml
- datacatalog/snippets/test/quickstart.test.js
- datacatalog/snippets/test/samples.test.js
- repo setups
- feat!: first release of client library (#8)
- chore: release 1.0.0 (#9)
- chore: release 1.0.1 (#11)
- chore(deps): update dependency execa to v2 (#16)
- chore: release 1.0.2 (#23)
- chore: release 1.1.0 (#30)
- chore(deps): update dependency execa to v3 (#47)
- chore: release 1.3.0 (#49)
- chore: release 1.4.0 (#63)
- chore: release 1.4.1 (#66)
- chore: release 1.5.0 (#70)
- chore(deps): update dependency execa to v4 (#77)
- chore: release 1.5.1 (#73)
- refactor: use explicit mocha imports (#83)
- chore: release 1.6.0 (#84)
- chore(deps): update dependency mocha to v7 (#89)
- chore: release 1.6.1
- chore: release 1.6.2 (#92)
- chore: release 1.6.3 (#94)
- chore: release 1.7.0 (#111)
- chore: release 1.8.0 (#125)
- chore: release 2.0.0 (#141)
- chore(deps): update …
> migrate code from googleapis/nodejs-datacatalog

- .github/workflows/dataproc.yaml
- .github/workflows/workflows.json
- dataproc/.eslintrc.yml
- dataproc/createCluster.js
- dataproc/instantiateInlineWorkflowTemplate.js
- dataproc/package.json
- dataproc/quickstart.js
- dataproc/submitJob.js
- dataproc/system-test/createCluster.test.js
- dataproc/system-test/instantiateInlineWorkflowTemplate.test.js
- dataproc/system-test/quickstart.test.js
- dataproc/system-test/submitJob.test.js
- dataproc/system-test/util.js
- enabling test and CI
- Upgrade repo-tools and regenerate scaffolding.
- make lint task work in circleci
- update lock files
- chore: make samples depend on the current version
- chore: make samples depend on the current version
- regen package-lock
- chore: lock files maintenance (#19)
- chore: lock files maintenance (#21)
- chore: lock files maintenance (#24)
- fix: update all dependencies
- chore: update sample lockfiles (#33)
- chore(deps): lock file maintenance (#36)
- chore(deps): lock file maintenance (#39)
- fix: drop support for node.js 4.x and 9.x (#38)
- chore(deps): lock file maintenance (#40)
- chore(deps): lock file maintenance (#41)
- chore(deps): update dependency @google-cloud/nodejs-repo-tools to v2.3.1 (#45)
- chore(deps): lock file maintenance (#46)
- chore(deps): …
> migrate code from googleapis/nodejs-dataproc

- container-analysis/snippets/occurrencesForImage.js
This example should filter by image digest (@sha256:123), similar to the samples for Python, Ruby, and others on this page: https://cloud.google.com/container-analysis/docs/automated-scanning-howto#container-analysis-discovery-python
> Filter by image digest rather than image tag

- appengine/endpoints/package.json
- appengine/typescript/package.json
- asset/snippets/package.json
- cloud-language/package.json
- cloud-sql/mysql/mysql/package.json
- cloud-sql/sqlserver/mssql/package.json
- container/snippets/package.json
- datacatalog/snippets/package.json
- dialogflow-cx/package.json
- dialogflow/package.json
- document-ai/package.json
- healthcare/datasets/package.json
- healthcare/dicom/package.json
- healthcare/fhir/package.json
- healthcare/hl7v2/package.json
- kms/package.json
- monitoring/prometheus/package.json
- service-directory/snippets/package.json
- talent/package.json
#2901 contains a dependency update for `eslint`. This is being included unnecessarily. CI is currently running `npm run lint` with pre-installed lint dependencies on the Docker image.
This PR:
* Removes any unused dependencies. Confirmed with inspecting code, running tests, and using `depcheck`.
* Moves any dependencies that are only used for tests our of `dependencies` into `devDependencies`.
> ci: Cleanup dependencies

- run/logging-manual/package.json
- run/logging-manual/test/system.test.js
> fix(run/logging): make tests more robust

- functions/http/parseXML/index.js
- functions/http/parseXML/package.json
Tested using the following commands:
```
gcloud functions deploy $USER-http-function \
--allow-unauthenticated \
--entry-point parseXML \
--runtime nodejs16 \
--gen2 \
--trigger-http \
--source . \
--region us-central1
curl -i $(gcloud functions describe --gen2 $USER-http-function --format "value(serviceConfig.uri)")
```
> chore(functions/v2): Migrate parseXML sample to gen2

- functions/http/corsEnabledFunction/index.js
- functions/http/corsEnabledFunction/package.json
- functions/http/corsEnabledFunction/test/index.test.js
Migrate https://cloud.google.com/functions/docs/samples/functions-http-cors example to gen2 signature using functions framework. 
Tested, executes successfully with the command:
```
curl -m 70 -X POST https://garethgeorge-http-function-sehddnhvmq-uc.a.run.app -H "Authorization: bearer $(gcloud auth print-identity-token)" -H "Content-Type: application/json" -d '{  "name": "Hello World" }'
```
> chore(functions/v2): migrate CORS enabled function sample to gen2

- functions/tips/connectionPools/index.js
- functions/tips/connectionPools/package.json
Update https://cloud.google.com/functions/docs/samples/functions-tips-connection-pooling to use gen2 signature with functions framework.
Had to modify the result of fetch since I was getting an error as though data was undefined.
Used https://www.npmjs.com/package/node-fetch for reference.
Tested by:
* Running locally using functions framework
```npx functions-framework --target=connectionPooling --signature-type=http```
* Deploying and invoking with curl
stdout:
```
Data: <!doctype html>
<html>
<head>
<title>Example Domain</title>
<meta charset="utf-8" />
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<style type="text/css">
body {
background-color: #f0f0f2;
margin: 0;
padding: 0;
font-family: …
```
> chore(functions/connectionPooling): Update connectionPooling sample to use gen 2 signature

- functions/http/httpContent/index.js
- functions/http/httpContent/package.json
- functions/http/httpContent/test/index.test.js
Update [HTTP request body](https://cloud.google.com/functions/docs/samples/functions-http-content) to use gen2 signature with functions framework.
> chore(functions/httpContent): using gen2 declarative signature

- run/logging-manual/test/system.test.js
The `run/logging-manual` sample may occasionally fail to retrieve the underlying Cloud Run service's URL ([example](https://source.cloud.google.com/results/invocations/9cb9b126-dffa-4e29-8b45-cbfd0bd59ac2/targets/github%2Fnodejs-docs-samples%2Frun%2Flogging-manual%2Frun/tests)). _(The URL read from `gcloud run services describe` appears to be the empty string.)_
I'm _guessing_ we can fix this by retrying the command if its `stdout` is empty. To ensure we log `stderr` (in case an actual error occurs) during each try, we can _raise an error_ containing the command's `stderr`.
--------
_Fixes #2915_
> fix(run/logging): throw error if stdout is empty

- datacatalog/snippets/searchAssets.js
- datacatalog/snippets/test/samples.test.js
The search assets query can timeout due to a large number of `dataset` assets being searched. The fix in `java-docs-samples` was to use an asset type with a much smaller number of assets: `lake`.
This PR updates the sample asset type, and enables the test. 
Fixes #2884
> test: fix skipped datacatalog test

- functions/http/corsEnabledFunctionAuth/index.js
- functions/http/corsEnabledFunctionAuth/package.json
- functions/http/corsEnabledFunctionAuth/test/index.test.js
Migrate https://cloud.google.com/functions/docs/samples/functions-http-cors-auth#functions_http_cors_auth-nodejs example to gen2 signature using functions framework.
Tested, executes successfully with the command:
```
curl -m 70 -X POST https://garethgeorge-http-function-sehddnhvmq-uc.a.run.app -H "Authorization: bearer $(gcloud auth print-identity-token)" -H "Content-Type: application/json" -d '{  "name": "Hello World" }'
```
> chore(functions/http): migrate HTTP Auth with CORS sample to gen2

- functions/tips/scopeDemo/computations.js
- functions/tips/scopeDemo/index.js
- functions/tips/scopeDemo/package.json
- functions/tips/scopeDemo/test/index.test.js
Using gen2 declarative signature in the [Global versus function scope](https://cloud.google.com/functions/docs/samples/functions-tips-scopes) docs.
Added unit-tests. From my inspection of [.github/workflows/functions-tips.yaml](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/.github/workflows/functions-tips.yaml), this will likely/possibly "just work". (But honestly, I'm not sure why it was "working" before -- without any tests to begin with.)
> chore(functions/tips/scopeDemo): use gen2 declarative signature, add tests

- .github/workflows/functions-tips.yaml
- functions/tips/gcpApiCall/index.js
- functions/tips/gcpApiCall/package.json
- functions/tips/gcpApiCall/test/index.test.js
Updating [this doc sample](https://cloud.google.com/functions/docs/samples/functions-tips-gcp-apis) to gen2 declarative signature.
Added unit-tests and enabled github workflow.
Tested on GCP.
> chore(functions/tips/gcpApiCalls): update gen2 declarative signature

- .github/auto-label.yaml
Adding a handful of initial services to test auto-labeling in this monorepo. This will fill out missing metadata and improve visibility in our internal dashboard.
If this is successful, we can expand the configuration. I just picked 5 services including one that should apply to an open PR for testing.
For more info, see:
https://github.com/googleapis/repo-automation-bots/tree/main/packages/auto-label
> ci: test auto-label configuration

- functions/concepts/afterResponse/index.js
- functions/concepts/afterResponse/package.json
Updated afterResponse sample using gen2 signature. 
Successfully tested on GCP.
> chore(functions/concepts): Migrate afterResponse sample to gen2

- datastore/functions/package.json
- datastore/functions/test/index.test.js
Fixes #2755 + reverts #2761
This swaps a homebrew `waitForReady` function (that was continuously stalling) with the `wait-port` NPM module.
> Fix datastore/functions test timing out

- .github/header-checker-lint.yml
- .github/workflows/ci.yaml.njk
Adds the [License Header bot](https://github.com/googleapis/repo-automation-bots/tree/main/packages/header-checker-lint) configuration based on [Google Cloud Node](https://github.com/googleapis/google-cloud-node/blob/main/.github/header-checker-lint.yml) and [Python Docs Samples](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/header-checker-lint.yml).
Also, added a header to the workflow generation template, so new workflows are compliant. We can address adding missing headers as we go or in a separate PR.
> ci: Add header checker

- recaptcha/demosite/app/recaptcha/createAssessment.js
The frontend code truncates the score which can cause a value of 0.899999999 to become 0.8
> Convert the score to a string with one decimal

- functions/helloworld/helloError/index.js
- functions/helloworld/helloError/test/index.test.js
**Issue:** b/266020023.
Switching to unique region tags vs single region tag.
> fix: making unique region tags for helloerror samples for functions

- recaptcha/demosite/app/static/scripts/component.js
- recaptcha/demosite/docker-compose.yaml
- Specify a container_name to simplify docker operations
- Remove unhelpful invalidReason from the response. null is not a valid value.
> Demosite app recaptcha

- dlp/categoricalRiskAnalysis.js
- dlp/kAnonymityAnalysis.js
- dlp/kMapEstimationAnalysis.js
- dlp/lDiversityAnalysis.js
- dlp/numericalRiskAnalysis.js
- dlp/system-test/inspect.test.js
- dlp/system-test/risk.test.js
Few DLP jobs were undeleted in snippets hence causing resource leakage in the projects. Fixed the issue by deleting the jobs in tests.
> fix: delete test DLP jobs created in snippets

- functions/helloworld/helloworldHttp/test/sample.system.http.test.js
Without this closing bracket, the tag creates an invalid sample. b/271558999
> fix: add closing bracket in functions_http_system_test

- appengine/typescript/package.json
Adds script removed in #3029 that is referenced by: https://cloud.google.com/appengine/docs/standard/nodejs/running-custom-build-step#example
> fix: add back gcp-build script

- appengine/hello-world/flexible_nodejs16_and_earlier/test/app.test.js
- appengine/metadata/flexible_nodejs16_and_earlier/test/server.test.js
- appengine/storage/flexible_nodejs16_and_earlier/system-test/app.test.js
**Issue:** Resolving `region-tags` workflow failures in appengine that is popping up in PRs
Example: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/actions/runs/4623711080/jobs/8177808534?pr=3104
**Resolution:** Expects any written tests to match names with region tags of samples
https://github.com/GoogleCloudPlatform/repo-automation-playground/tree/master/xunit-ci-enforcer
> fix: matching test names with region tags per enforcer requirements

- vision/system-test/detect.test.js
Updated to case-insensitive regex, to be more resilient to service updates. (Now returns "The palace..." instead of "Palace...")
Fixes #3120 
Fixes #3119 
Fixes #3116 
Fixes #3115
> fix: vision landmark test failures

- dlp/deIdentifyWithSimpleWordList.js
- dlp/system-test/deid.test.js
Added sample for DeIdentify using a custom simple word list
Added unit test cases for the same
Reference: https://cloud.google.com/dlp/docs/samples/dlp-deidentify-simple-word-list
> DLP: Added sample for deidentify using simple word list

- dlp/inspectWithCustomRegex.js
- dlp/system-test/inspect.test.js
Added sample for inspect string with custom regex
Added unit test cases for the same
Reference: https://cloud.google.com/dlp/docs/samples/dlp-inspect-custom-regex
> DLP: Added sample for inspect string with custom regex

- dlp/deIdentifyWithExceptionList.js
- dlp/system-test/deid.test.js
Added sample for de-identification with an exception list
Added test cases for the same
Reference: https://cloud.google.com/dlp/docs/creating-custom-infotypes-dictionary#exception_list
> DLP: Added sample for de-identification with an exception list

- .github/PULL_REQUEST_TEMPLATE.md
[Per discussion](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3143#issuecomment-1515336096) we should make sure that users don't miss workflow generation when creating a new folder. Moreover a missing CODEOWNERS step was added here as well.
> chore(docs): Update PR template with missing steps

- dlp/deIdentifyTableInfoTypes.js
- dlp/system-test/deid.test.js
added Unit test cases for same
Reference:- https://cloud.google.com/dlp/docs/examples-deid-tables.md#transform_findings_found_in_columns
> DLP: Added sample for deidentify table with info types

- dlp/redactImageFileListedInfoTypes.js
- dlp/system-test/redact.test.js
Reference:- https://cloud.google.com/dlp/docs/redacting-sensitive-data-images#dlp-redact-image-listed-infotypes-java
> DLP: Added sample for redact image with info types

- dlp/inspectStringCustomOmitOverlap.js
- dlp/system-test/inspect.test.js
Reference:- https://cloud.google.com/dlp/docs/creating-custom-infotypes-rules#omit_scan_matches_from_a_person_name_detector_scan_that_overlap_with_a_custom_detector
> DLP: Added sample for inspect string with omitting custom matches

- dlp/deIdentifyTableConditionMasking.js
- dlp/system-test/deid.test.js
Added sample for transform table using conditional logic
Added test cases for the same
Reference:- https://cloud.google.com/dlp/docs/examples-deid-tables.md#transform_a_column_based_on_the_value_of_another_column
> DLP: Added sample for transform table using conditional logic

- appengine/websockets/package.json
> chore: update timeout for gae websocket test

- dlp/deIdentifyTableConditionInfoTypes.js
- dlp/system-test/deid.test.js
Added sample for deidentify table using conditional logic
Reference:- https://cloud.google.com/dlp/docs/examples-deid-tables.md#transform_findings_only_when_specific_conditions_are_met_on_another_field
> DLP: Added sample for deidentify table using conditional logic

- dlp/inspectStringWithExclusionDict.js
- dlp/system-test/inspect.test.js
Added test cases for same
Reference:- https://cloud.google.com/dlp/docs/creating-custom-infotypes-rules#omit_specific_email_address_from_email_address_detector_scan
> DLP: Added sample for inspect string with exclusion dict

- dlp/inspectStringWithExclusionDictSubstring.js
- dlp/system-test/inspect.test.js
Added sample for inspect string with substring exclusions
Reference:- https://cloud.google.com/dlp/docs/creating-custom-infotypes-rules#dlp_inspect_string_with_exclusion_dict_substring-java
> DLP: Added sample for inspect string with substring exclusions

- dlp/deIdentifyTableBucketing.js
- dlp/system-test/deid.test.js
Added sample for de-identify with table bucketing
Reference:- https://cloud.google.com/dlp/docs/examples-deid-tables.md#transform_a_column_without_inspection
> DLP: Added sample for de-identify with table bucketing

- functions/v2/responseStreaming/index.js
- functions/v2/responseStreaming/package.json
- functions/v2/responseStreaming/test/index.test.js
Add response streaming sample in nodejs
> DLP: Add response streaming sample in nodejs

- ai-platform/snippets/predict-chat-prompt.js
- ai-platform/snippets/test/predict-chat-prompt.test.js
Fixes b281562687
Added a chat prompt sample for Vertex LLMs.
> feat: chat prompt sample for Vertex LLMs

- ai-platform/snippets/predict-text-sentiment.js
- ai-platform/snippets/test/predict-text-sentiment.test.js
Fixes b/281562687
Add a sentiment analysis sample for Vertex LLMs.
> feat: sentiment analysis sample for Vertex LLMs

- ai-platform/snippets/predict-text-extraction.js
- ai-platform/snippets/test/predict-text-extraction.test.js
Fixes b/281562687
Add a text extraction sample for Vertex LLMs.
> feat: text extraction sample for Vertex LLMs

- ai-platform/snippets/predict-text-summarization.js
- ai-platform/snippets/test/predict-text-summarization.test.js
Fixes b/281562687
Add a text summarization sample for Vertex LLMs.
> feat: text summarization sample for Vertex LLMs

- ai-platform/snippets/predict-text-news-classification.js
- ai-platform/snippets/test/predict-text-news-classification.test.js
Fixes b/281562687
Add a text classification sample for Vertex LLMs.
> feat: text classification sample for Vertex LLMs

- ai-platform/snippets/predict-code-generation-unittest.js
- ai-platform/snippets/test/predict-code-generation-unittest.test.js
Add a sample for the code generation unit test for Vertex LLMs.
> feat(aiplatform): code generation unit test sample for Vertex LLMs

- ai-platform/snippets/predict-code-completion-test-function.js
- ai-platform/snippets/test/predict-code-completion-test-function.test.js
Add a sample for code completion test function for Vertex LLMs.
> feat(aiplatform): code completion test function for Vertex LLMs

- ai-platform/snippets/predict-code-chat.js
- ai-platform/snippets/test/predict-code-chat.test.js
Add a code chat sample for Vertex LLMs.
> feat(aiplatform): code chat sample for Vertex LLMs

- dlp/inspectStringMultipleRules.js
- dlp/system-test/inspect.test.js
DLP: Added sample for inspect string using multiple rules
Added Unit test cases for same
Reference:- https://cloud.google.com/dlp/docs/creating-custom-infotypes-rules#multiple_inspection_rules_scenario
> DLP: Added sample for inspect string using multiple rules

- dlp/createStoredInfoType.js
- dlp/system-test/metadata.test.js
DLP: Added sample for create stored infotype
Added unit test cases for the same
PS:- I have marked the test cases to skip as the required resources are not available. I have verified locally and the test cases seem to be working fine if resources are provided.
Reference:- https://cloud.google.com/dlp/docs/creating-stored-infotypes#create-storedinfotye
> DLP: Added sample for create stored infotype

- dlp/deidentifyWithTimeExtraction.js
- dlp/system-test/deid.test.js
DLP: Added sample for de-identify using time extract
Added unit test cases for the same
Reference:- https://cloud.google.com/dlp/docs/transformations-reference#time-extract
> DLP: Added sample for de-identify using time extract

- dlp/deIdentifyTableWithFpe.js
- dlp/system-test/deid.test.js
- dlp/system-test/mockdata.js
DLP: Added sample for de-identify table with FPE
PS:- I have marked the test cases to skip as the required resources are not available. I have verified locally and the test cases seem to be working fine if resources are provided.
Reference:- https://cloud.google.com/dlp/docs/samples/dlp-deidentify-table-fpe
> DLP: Added sample for de-identify table with FPE

- .kokoro/appengine/test-deployment/common.cfg
Fixes long running kokoro failure, which was referencing deprecated cloud doc samples repo.
For example see: https://fusion2.corp.google.com/ci/kokoro/prod:cloud-devrel%2Fnodejs-docs-samples%2Frelease%2Fappengine%2Ftest-deployment%2Fstorage-flex/activity/2b3554f5-618f-431f-8b1e-6de79b777bf1/summary
> fix: replace deprecated repo with active docker repo for trampoline image

- dlp/deidentifyWithFpeSurrogate.js
- dlp/reidentifyWithFpeSurrogate.js
- dlp/system-test/deid.test.js
-Added sample for reidentify with FPE surrogate
-Added unit test cases for the same
Reference:- https://cloud.google.com/dlp/docs/samples/dlp-deidentify-free-text-with-fpe-using-surrogate
https://cloud.google.com/dlp/docs/samples/dlp-reidentify-free-text-with-fpe-using-surrogate
> DLP: Added sample for deidentify with FPE surrogate

- cloud-sql/postgres/knex/connect-connector-with-iam-authn.js
- cloud-sql/postgres/knex/index.js
Just cleaning up a couple of the sample comments to make sure it propertly mentions the `INSTANCE_CONNECTION_NAME` environment variable name and uses an IAM username in examples that is similar to the usernames used by Posgtres Cloud SQL Instances.
Ref: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3266
cc @jackwotherspoon
> chore(cloud-sql): cleanup pg/knex example comments

- ai-platform/snippets/test/create-featurestore-fixed-nodes-sample.test.js
- ai-platform/snippets/test/create-featurestore-sample.test.js
Fixes #3300 
Temporarily skip featurestore tests as there may be a service stability issue that causes CI tests to stall.
Tracking bug #3302
> chore(aiplatform): temporarily skip featurestore tests

- dlp/inspectGcsFileWithSampling.js
- dlp/inspectImageFileAllInfoTypes.js
- dlp/system-test/inspect.test.js
- dlp/system-test/mockdata.js
-Added sample for inspect image file
-Added unit test cases for same
References:- https://cloud.google.com/dlp/docs/inspecting-images.md#dlp-inspect-image-all-infotypes-java
https://cloud.google.com/dlp/docs/inspecting-storage.md#dlp_inspect_gcs_with_sampling-java
> DLP: Added sample for inspect GCS file

- .github/workflows/ai-platform-snippets.yaml
Fixes #3302
Temporarily increase the timeout for the CI tests for aiplatform as an attempt to fix #3302.
> fix(aiplatform): Temporarily increase the CI tests timeout

- dlp/inspectStringCustomExcludingSubstring.js
- dlp/inspectStringCustomHotword.js
- dlp/system-test/inspect.test.js
Added sample for inspect string with custom substring exclusion Added unit test cases for same
References:- https://cloud.google.com/dlp/docs/creating-custom-infotypes-rules#omit_scan_matches_that_include_the_substring_jimmy_from_a_custom_infotype_detector_scan
https://cloud.google.com/dlp/docs/creating-custom-infotypes-rules#increase_the_likelihood_of_a_person_name_match_if_there_is_the_hotword_patient_nearby
> DLP: Added sample for inspect string with custom hotword

- ai-platform/snippets/predict-image-from-text.js
- ai-platform/snippets/test/predict-image-from-text.test.js
Fixes b/288243718
Add a code sample to generate image from text prompt.
Docs: https://cloud.google.com/vertex-ai/docs/generative-ai/image/generate-images
> feat(aiplatform): add sample to generate image from text prompt

- ai-platform/snippets/predict-image-from-image-and-text.js
- ai-platform/snippets/test/predict-image-from-image-and-text.test.js
Fixes b/288243718
Add a code sample to generate image from a base image and text prompt.
Docs: https://cloud.google.com/vertex-ai/docs/generative-ai/image/edit-images
> feat(aiplatform): add sample to generate image from base image and text prompt

- .github/workflows/ai-platform-snippets.yaml
- ai-platform/snippets/test/deploy-model-custom-trained-model.test.js
Fixes #3302 
Reset timeout back to 120m as increasing timeout didn't work.
Temporarily skip the deploy model test to see if the test is the cause of the test run stalling.
> fix(aiplatform): reset timeout and skip deploy model test

- cloud-sql/mysql/mysql2/Dockerfile
- cloud-sql/mysql/mysql2/README.md
- cloud-sql/mysql/mysql2/app.flexible.yaml
- cloud-sql/mysql/mysql2/app.standard.yaml
- cloud-sql/mysql/mysql2/connect-connector-auto-iam-authn.js
- cloud-sql/mysql/mysql2/connect-connector.js
- cloud-sql/mysql/mysql2/connect-tcp.js
- cloud-sql/mysql/mysql2/connect-unix.js
- cloud-sql/mysql/mysql2/deployment.yaml
- cloud-sql/mysql/mysql2/functions.js
- cloud-sql/mysql/mysql2/index.js
- cloud-sql/mysql/mysql2/package.json
- cloud-sql/mysql/mysql2/server/server.js
- cloud-sql/mysql/mysql2/service-account.yaml
- cloud-sql/mysql/mysql2/service.yaml
- cloud-sql/mysql/mysql2/test/server.test.js
- cloud-sql/mysql/mysql2/views/index.pug
This new sample uses the Cloud SQL Node.js Connector to connect to Cloud SQL instances instead of relying on the standalone Cloud SQL Proxy.
The original example from `cloud-sql/mysql/mysql` has been used as a starting point but uses the `mysql2` driver instead thus residing in a new location: `cloud-sql/mysql/mysql2`.
Ref: https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector
> feat(cloud-sql): add mysql2 connector sample

- ai-platform/snippets/package.json
Fixes #3302
Temporarily increase mocha test timeout to diagnose flaky tests.
> fix(aiplatform): temporarily increase test timeout to diagnose flaky tests

- dlp/deidentifyWithDeterministic.js
- dlp/reidentifyWithDeterministic.js
- dlp/system-test/deid.test.js
- dlp/system-test/mockdata.js
References:-https://cloud.google.com/dlp/docs/inspect-sensitive-text-de-identify#deidentify
https://cloud.google.com/dlp/docs/inspect-sensitive-text-de-identify#reidentify
- [] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
> DLP: Added sample for de-identify and re-identify with deterministic encryption

- mediatranslation/README.md
- mediatranslation/test/quickstart.test.js
- mediatranslation/test/translate_from_file.test.js
Adds README with the deprecation message.
Removes tests.
Fixes #3323
> chore(cleanup): retire media translate samples

- cloud-sql/sqlserver/tedious/Dockerfile
- cloud-sql/sqlserver/tedious/README.md
- cloud-sql/sqlserver/tedious/app.flexible.yaml
- cloud-sql/sqlserver/tedious/app.standard.yaml
- cloud-sql/sqlserver/tedious/connect-connector.js
- cloud-sql/sqlserver/tedious/connect-tcp.js
- cloud-sql/sqlserver/tedious/deployment.yaml
- cloud-sql/sqlserver/tedious/index.js
- cloud-sql/sqlserver/tedious/package.json
- cloud-sql/sqlserver/tedious/server/server.js
- cloud-sql/sqlserver/tedious/service-account.yaml
- cloud-sql/sqlserver/tedious/service.yaml
- cloud-sql/sqlserver/tedious/tedious-helper.js
- cloud-sql/sqlserver/tedious/test/server.test.js
- cloud-sql/sqlserver/tedious/views/index.pug
This new sample uses the **Cloud SQL Node.js Connector** to connect to Cloud SQL instances instead of relying on the standalone Cloud SQL Proxy.
The original SQL Server sample from `cloud-sql/sqlserver/mssql` does not support the Cloud SQL Node.js Connector so this PR adds a new example residing in a new location: `cloud-sql/sqlserver/tedious`.
Ref: https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector
Ref: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3264
Ref: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3266
> feat(cloud-sql): add tedious connector sample

- dlp/package.json
- dlp/system-test/metadata.test.js
- dlp/system-test/resources/test.txt
- dlp/system-test/triggers.test.js
- dlp/updateStoredInfoType.js
Reference:- https://cloud.google.com/dlp/docs/creating-stored-infotypes#rebuild
> DLP: Added sample for update stored infotype

- dlp/inspectStringWithExclusionRegex.js
- dlp/system-test/inspect.test.js
Reference:- https://cloud.google.com/dlp/docs/creating-custom-infotypes-rules#omit_email_addresses_ending_with_a_specific_domain_from_email_address_detector_scan
> DLP: Added sample for inspect string using exclusion regex

- dlp/inspectImageFile.js
- dlp/inspectImageFileListedInfoTypes.js
- dlp/system-test/inspect.test.js
References:- https://cloud.google.com/dlp/docs/samples/dlp-inspect-image-file
https://cloud.google.com/dlp/docs/samples/dlp-inspect-image-listed-infotypes
> DLP: Added samples for inspect image file

- dlp/reidentifyTableWithFpe.js
- dlp/reidentifyTextWithFpe.js
- dlp/system-test/deid.test.js
- dlp/system-test/mockdata.js
References:- https://cloud.google.com/dlp/docs/samples/dlp-reidentify-text-fpe
https://cloud.google.com/dlp/docs/samples/dlp-reidentify-table-fpe
> DLP: Added sample for reidentify text and table using FPE

- dlp/inspectBigquerySendToScc.js
- dlp/inspectDatastoreSendToScc.js
- dlp/inspectGcsSendToScc.js
- dlp/system-test/inspect.test.js
- dlp/system-test/mockdata.js
References:- https://cloud.google.com/dlp/docs/sending-results-to-scc.md#bigquery-data
https://cloud.google.com/dlp/docs/sending-results-to-scc.md#cloud-storage-data
https://cloud.google.com/dlp/docs/sending-results-to-scc.md?g=0&l=416#datastore-data
> Added sample for inspect GCS file, bigquery and datastore with SCC action

- run/filesystem/gcsfuse.Dockerfile
- run/filesystem/gcsfuse.run.sh
This PR will add an additional Dockerfile and shell script to the filesystem sample for inclusion on the [Using Cloud Storage FUSE with Cloud Run tutorial](https://cloud.google.com/run/docs/tutorials/network-filesystems-fuse) page.
> feat(run): add GCSFuse files to filesystem sample

- .github/workflows/remove-label.yaml
The remove label job now fails on every execution. In #3279 the workflow was scoped to permissions that did not include updating the PR.
More info: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
> test: update permissions on remove_label jobs

- .github/workflows/ai-platform-snippets.yaml
- .github/workflows/automl.yaml
- .github/workflows/dialogflow-cx.yaml
- .github/workflows/functions-slack.yaml
- .github/workflows/iam-deny.yaml
- .github/workflows/security-center-snippets.yaml
- .github/workflows/storagetransfer.yaml
- .github/workflows/test.yaml
- .github/workflows/utils/ci-secrets.yaml.njk
- .github/workflows/vision.yaml
- ai-platform/snippets/package.json
FlakyBot issues aren't being uploaded regularly. I believe this is because the upload action is referencing an OS environment variable with the log, and needs to access the GHA env var.
> test: update GHA flakybot upload action

- .github/workflows/ai-platform-snippets.yaml
- .github/workflows/automl.yaml
- .github/workflows/dialogflow-cx.yaml
- .github/workflows/functions-slack.yaml
- .github/workflows/iam-deny.yaml
- .github/workflows/security-center-snippets.yaml
- .github/workflows/storagetransfer.yaml
- .github/workflows/test.yaml
- .github/workflows/utils/ci-secrets.yaml.njk
- .github/workflows/vision.yaml
Currently GHA workflows allow an error on `npm run build`, as not all samples have this command in `package.json`. This change uses the `--if-present` flag to avoid throwing and catching the error in the first place.
> test: use --if-present rather than failing on build

- .github/workflows/remove-label.yaml
Reverts GoogleCloudPlatform/nodejs-docs-samples#3374
Workflow is failing because the `pull-requests: 'write'` isn't allowed if the calling workflow doesn't have it. Will need to look at potentially adding it there.
> Revert "test: update permissions on remove_label jobs"

- workflows/quickstart/index.js
- workflows/quickstart/index.ts
This PR adds an optional `searchTerm` argument to the WorkFlows Quickstart sample. This will illustrate how to pass runtime arguments to a workflow via JavaScript on [Execute a Workflow documentation page](https://cloud.google.com/workflows/docs/executing-workflow).  
> feat(workflows): add runtime arguments to workflows TS sample

- recaptcha_enterprise/snippets/package.json
- recaptcha_enterprise/snippets/test/test.passwordleak.ts
> fix: fix npm run build in recaptcha

- renovate.json
**Issue:** Allow renovate-bot to add dependency updates every 2 weeks.
> chore: update renovate bot to run every couple of weeks

- dlp/deIdentifyTableWithBucketingConfig.js
- dlp/deidentifyWithDictionaryReplacement.js
- dlp/system-test/deid.test.js
References:- https://cloud.google.com/dlp/docs/concepts-bucketing
https://cloud.google.com/dlp/docs/transformations-reference#dictionary-replacement
> DLP: Added sample for deidentify table with bucketing and dictionary replacement

- workflows/quickstart/package.json
- workflows/quickstart/tsconfig.json
This PR will:
- will redefine `npm start` to run the JavaScript variant of the sample
- add an option to `tsconfig` to allow `npm start` to run the generated JS file after compiling
With this change, you can run the js sample with:
1. `npm install`
2. `npm start`
Run the ts sample with:
1. `npm install && npm run build`
2. `npm start`
[Documentation](https://cloud.google.com/workflows/docs/executing-workflow#workflows_install-typescript) will be updated to reflect changes to these steps.
> refactor(workflows): use `npm start` to run JS variant 

- dlp/inspectWithCustomHotwords.js
- dlp/inspectWithStoredInfotype.js
- dlp/system-test/inspect.test.js
- dlp/system-test/mockdata.js
References:- https://cloud.google.com/dlp/docs/creating-custom-infotypes-likelihood.md#match-column-values
https://cloud.google.com/dlp/docs/creating-stored-infotypes#scan-with-large-custom-infotype
> DLP: Added sample for inspect with stored infotype and inspect with custom hotword

- dlp/deIdentifyCloudStorage.js
- dlp/kAnonymityWithEntityIds.js
- dlp/system-test/deid.test.js
- dlp/system-test/mockdata.js
- dlp/system-test/risk.test.js
References:- https://cloud.google.com/dlp/docs/deidentify-storage#code-example
https://cloud.google.com/dlp/docs/visualizing_re-id_risk.md?g=0&l=119#step_1_calculate_k-anonymity_on_the_dataset
> DLP: Added sample for k anonymity with entity ID and deidentify cloud storage

- renovate.json
Updating renovate-bot to only update on major releases and changing cadence when issues get created.
> refactor: only allow for major releases to be aired, no minor updates

- cloud-tasks/snippets/server.js
> chore(issue-295372912): small cloud-tasks PORT change

- dlp/createStoredInfoType.js
- dlp/system-test/metadata.test.js
- dlp/system-test/mockdata.js
- dlp/updateStoredInfoType.js
Tests for following region tag samples have been updated
-dlp_create_stored_infotype
-dlp_update_stored_infotype
References:- https://cloud.google.com/dlp/docs/creating-stored-infotypes#create-storedinfotye
https://cloud.google.com/dlp/docs/creating-stored-infotypes#rebuild
> DLP: Updated test cases for storedInfoType related samples to use mock approach

- discoveryengine/search.js
By default NodeJS has autoPaginate turned on, this will result in us iterate through all pages of search results, instead of just a single page restricted by pageSize.
> chore(discoveryengine): update search sample to disable auto paginate

- .github/workflows/ci.yaml
While this is a useful action (validates links in the README and markdown files), it's pulling from a previous Googlers personal actions which is against the current policy. We can revisit doing this in the future and unblock current CI by removing it for now.
> fix: Remove the docs step in CI

- run/filesystem/gcsfuse.Dockerfile
The URL for packages.cloud.google.com should be https instead of http.
> fix: update URL for Cloud Run GCS fuse example.

- .github/workflows/utils/ci-secrets.yaml.njk
Additional to #3560, renovate doesn't update .yaml.nkj (nunjuck templates). Manually update. 
> chore(deps): update actions/checkout, setup-node in template

- .github/workflows/functions-slack.yaml
- functions/slack/test/integration.test.js
- functions/slack/test/unit.test.js
Fixes Functions Slack testing. 
> fix(functions): Functions Slack sample test errors

- owlbot.py
- renovate.json
- run/logging-manual/app.js
Fixes the following:
* Updating renovate-bot to preserve semver ranges and update monthly rather than pinning. (#3522)
* Current `ci lint` error see in other PRs is being caused by collision from owlbot + `gts fix` (credit to: @muncus) 
> refactor: preserving semver ranges 

- kms/checkStateImportJob.js
- kms/checkStateImportedKey.js
- kms/createImportJob.js
- kms/createKeyForImport.js
- kms/importManuallyWrappedKey.js
- kms/test/kms.test.js
- run/logging-manual/app.js
> feat(kms): add import sample

- ai-platform/snippets/tuning.js
Fixes b/306723063
New optional accelerator_type = "GPU/TPU" parameter for the text model tuning pipeline job.
Public docs: https://cloud.devsite.corp.google.com/vertex-ai/docs/generative-ai/models/tune-text-models-supervised#generative-ai-tune-model-nodejs
> feat: add new optional accelerator_type parameter

- run/filesystem/index.js
Fixes #3583 
Cloud Run provides it's own proxy, so for rate limiting purposes, the actual IP of the user (not the proxy itself) is required. From suggestions in https://github.com/express-rate-limit/express-rate-limit/wiki/Troubleshooting-Proxy-Issues, using `1` for "1 layer of proxies" should ensure the rate limiting code works.
> fix: configure express to know about Cloud Run's proxy

- generative-ai/snippets/countTokens.js
- generative-ai/snippets/nonStreamingChat.js
- generative-ai/snippets/nonStreamingContent.js
- generative-ai/snippets/nonStreamingMultipartContent.js
- generative-ai/snippets/safetySettings.js
- generative-ai/snippets/sendMultiModalPromptWithImage.js
- generative-ai/snippets/sendMultiModalPromptWithVideo.js
- generative-ai/snippets/streamChat.js
- generative-ai/snippets/streamContent.js
- generative-ai/snippets/streamMultipartContent.js
> add model to each function

- ai-platform/snippets/predict-image-from-image-and-text.js
- ai-platform/snippets/predict-image-from-text.js
- ai-platform/snippets/test/predict-image-from-image-and-text.test.js
- ai-platform/snippets/test/predict-image-from-text.test.js
Fixes #3320
Re-add code samples for GenAI embeddings. These samples were published but later removed because of the launch schedule change.
- Generate image from image
- Generate image from text
> feat: re-add GenAI embedding code samples

- run/helloworld/package.docs.json
Reflect change to from csm to esm in https://cloud.google.com/run/docs/quickstarts/build-and-deploy/deploy-nodejs-service.
> fix(run-helloworld): updating type in package.docs.json

- generative-ai/snippets/countTokens.js
- generative-ai/snippets/functionCallingStreamChat.js
- generative-ai/snippets/functionCallingStreamContent.js
- generative-ai/snippets/nonStreamingChat.js
- generative-ai/snippets/nonStreamingContent.js
- generative-ai/snippets/nonStreamingMultipartContent.js
- generative-ai/snippets/safetySettings.js
- generative-ai/snippets/sendMultiModalPromptWithImage.js
- generative-ai/snippets/sendMultiModalPromptWithVideo.js
- generative-ai/snippets/streamChat.js
- generative-ai/snippets/streamContent.js
- generative-ai/snippets/streamMultipartContent.js
- generative-ai/snippets/test/countTokens.test.js
- generative-ai/snippets/test/functionCallingStreamChat.test.js
- generative-ai/snippets/test/functionCallingStreamContent.test.js
- generative-ai/snippets/test/nonStreamingChat.test.js
- generative-ai/snippets/test/nonStreamingContent.test.js
- generative-ai/snippets/test/nonStreamingMultipartContent.test.js
- generative-ai/snippets/test/safetySettings.test.js
- generative-ai/snippets/test/sendMultiModalPromptWithImage.test.js
- generative-ai/snippets/test/sendMultiModalPromptWithVideo.test.js
- generative-ai/snippets/test/streamChat.test.js
- generative-ai/snippets/test/streamContent.test.js
- generative-ai/snippets/test/streamMultipartContent.test.js
Update Gemini model names to the GA version:
- gemini-pro > gemini-1.0-pro
- gemini-pro-vision > gemini-1.0-pro-vision
> fix(aiplatform): update Gemini model names

- cloud-sql/mysql/mysql/README.md
This PR just removes "2nd gen" from the Cloud SQL README. This is because 1st gen has been [decommissioned as of March 2020](https://cloud.google.com/sql/docs/mysql/deprecation-notice) and 2nd gen is the default and only option.
> chore(docs): update mysql readme

- run/logging-manual/test/system.test.js
> fix(issue-3534): increasing maxattempts to wait for metadata in entries to populate

- ai-platform/snippets/predict-text-embeddings-preview.js
- ai-platform/snippets/test/predict-text-embeddings.test.js
> feat: Elastic Text-Embedding Model demo.

- ai-platform/snippets/embedding-model-tuning.js
- ai-platform/snippets/test/embedding-model-tuning.test.js
> fix: Typos in samples for tuning text embedding models.

- cloud-sql/mysql/mysql/README.md
- cloud-sql/mysql/mysql2/README.md
- cloud-sql/postgres/knex/README.md
- cloud-sql/sqlserver/mssql/README.md
- cloud-sql/sqlserver/tedious/README.md
Also, remove all reference to service account keys in favor of Application Default Credentials.
Fixes #3634
Fixes #3635
> chore: use Cloud SQL Proxy v2 in README

- renovate.json
App Engine flex environment samples that are intentionally Node.js 16 and earlier should not have auto updates from renovate to update to Node.js 20 (example of this happening is with this pr https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3631/files)
> fix: don't have auto-updates running on app engine flex samples

- appengine/analytics/app.standard.yaml
- appengine/datastore/app.standard.yaml
- appengine/hello-world/standard/app.yaml
- appengine/memcached/app.standard.yaml
- appengine/metadata/standard/app.yaml
- appengine/pubsub/app.standard.yaml
- appengine/static-files/app.standard.yaml
- appengine/storage/standard/app.yaml
Node.js 10, 12, 14, and 16 have reached end of
support on January 30, 2024. Existing
applications using these versions will continue
to run and receive traffic. This update to
samples ensures new deploys will work as
expected.
Fixes #3645 
Fixes #3642 
Replaces #3643
> chore: Update runtimes for App Engine standard

- run/helloworld/Dockerfile
* update to use node:20-slim
* resolves warning that comes up  npm WARN config only Use `--omit=dev` https://docs.npmjs.com/cli/v9/commands/npm-ci#omit
I've tested locally and not making any major changes
> fix: resolve WARNs and Update version of Node.js used

- cloud-sql/mysql/mysql/Dockerfile
- cloud-sql/mysql/mysql2/Dockerfile
- cloud-sql/postgres/knex/Dockerfile
- cloud-sql/sqlserver/mssql/Dockerfile
- cloud-sql/sqlserver/tedious/Dockerfile
- cloud-tasks/snippets/Dockerfile
- eventarc/audit-storage/Dockerfile
- eventarc/generic/Dockerfile
- eventarc/pubsub/Dockerfile
- memorystore/redis/cloud_run_deployment/Dockerfile
- run/hello-broken/Dockerfile
- run/helloworld/Dockerfile
- run/image-processing/Dockerfile
- run/logging-manual/Dockerfile
- run/markdown-preview/editor/Dockerfile
- run/markdown-preview/renderer/Dockerfile
- run/pubsub/Dockerfile
* update to use node:20-slim
* resolves warning that comes up with npm WARN
* update comment to clarify difference between using ci (clean install) over install which isn't necessarily faster (and can be in fact slower) and the context of why production.
This PR intentionally does not resolve some other
remaining Docker issues as there are remaining
issues to resolve including appropriate fonts
with Alpine image use.
This does resolve a chunk of the Dockerfile
updates. Many of these are exactly the same
and there may be room to centralize and
standardize rather than having separate files.
I did go in and build docker images to verify these worked. 
- [X ] Please **merge** this PR for me once it is approved
> chore: update Dockerfiles to use modern images

- generative-ai/snippets/gemini-pdf.js
- generative-ai/snippets/test/gemini-pdf.test.js
Fixes b/330500909
Add PDF code sample for Gemini 1.5 Pro.
> feat(generative-ai): Add PDF sample for Gemini 1.5

- ai-platform/snippets/embedding-model-tuning.js
Copy of https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3699 but from a branch off the original repo instead of a fork.
BUG=b/340594864
> feat: Make embedding tuning sample reference new v1.1.3 tuning pipeline

- .github/workflows/dialogflow-cx.yaml
while the error (Invalid workflow file: .github/workflows/dialogflow-cx.yaml#L77 You have an error in your yaml syntax on line 77) is reporting on a different line, I think it's the indentation on this line causing a problem
also indicates that we should probably have a yaml lint checker on workflow changes
> fix: invalid yaml that was breaking this workflow dialogflow-cx.yaml

- package.json
This is a temporary pinning of gts version until we can decide how to handle CommonJS vs ESM for samples in this repository.
See: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/actions/runs/9600101597
https://github.com/google/gts/releases/tag/v5.3.1
> chore: pin gts version to fix errors in lint ci

- CODEOWNERS
This change adds the new GoogleCloudPlatform/cloud-samples-reviewers for all samples reviews, makes them a default owner on the repo to cover gaps, and then excludes it from ownership on repository infrastructure & common configuration files.
This is the first PR to add this team to a repo, and is being used to confirm the approach.
> chore(CODEOWNERS): Add cloud-samples-reviewers as a global sample owner

- package.json
Bump `engines.node` to `v18`. This allows `fetch` to be used (provides a web standard alternative to using third party request libraries). It's also the current *active* [Node.js version](https://nodejs.org/en/about/releases/) and aligns with the [gts/.eslintrc.json ecmaVersion](https://github.com/google/gts/blob/main/.eslintrc.json#L60C24-L60C28) we're using for the repo.
> chore: update node version

- .github/workflows/generative-ai-snippets.yaml
- generative-ai/snippets/grounding/groundingPublicDataBasic.js
- generative-ai/snippets/nonStreamingContent.js
- generative-ai/snippets/test/grounding/groundingPublicDataBasic.test.js
- generative-ai/snippets/test/nonStreamingContent.test.js
Fixes b/325521336
Streaming method was used incorrectly in a non streaming sample.
> fix(generative-ai): Use the non stream method instead

- .github/workflows/security-center-snippets.yaml
Pinning the path to v1 will make it easier to isolate and analyze v2 test failures related to #3722 (for example, see https://github.com/GoogleCloudPlatform/nodejs-docs-samples/actions/runs/9982328259/job/27587826930?pr=3743).
Note: #3722 adds [.github/workflows/security-center-snippets-v2.yaml](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3722/files#diff-b666080e3aae69df576b5d7312730719f7bf9a3f5a3918c6493365dc4740b593) to cover the security-center v2 snippets/tests.
> test: pin security center path to version (v1)

- .github/workflows/ai-platform-snippets.yaml
- .github/workflows/functions-env_vars.yaml
- .github/workflows/remove-label.yaml
- .github/workflows/utils/ci-matrix.yaml.njk
- .github/workflows/utils/ci-secrets.yaml.njk
- .github/workflows/utils/ci.yaml.njk
- CONTRIBUTING.md
This change is the start on removing `pull_request_target` from sample testing workflows.
1. Templates are updated to add the labeled type to the `pull_request` trigger, and remove the `pull_request_target`.
2. The ai-platform-snippets.yaml workflow is updated to match
3. The reused remove-label.yaml workflow is converted to a no-op echo statement providing maintainer guidance
4. CONTRIBUTING.md is updated to note this behavior around PR testing controls
Workshop the pattern and guidance here, then migrate remaining workflows to this trigger configuration in follow-up.
> ci: remove use of pull_request_target (part 1)

- .github/workflows/healthcare-consent.yaml
- .github/workflows/healthcare-datasets.yaml
- .github/workflows/healthcare-dicom.yaml
- .github/workflows/healthcare-fhir.yaml
- .github/workflows/healthcare-hl7v2.yaml
- .github/workflows/iam-deny.yaml
- .github/workflows/kms.yaml
Scoped to Samples workflows with file names starting with h, i, j, or k.
Implementation of https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3747, sibling of https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3748.
> ci: update h-k workflows to use labeled on pull_request trigger

- .github/workflows/media-livestream.yaml
- .github/workflows/media-transcoder.yaml
- .github/workflows/media-video-stitcher.yaml
- .github/workflows/mediatranslation.yaml
- .github/workflows/monitoring-opencensus.yaml
- .github/workflows/monitoring-prometheus.yaml
- .github/workflows/monitoring-snippets.yaml
- .github/workflows/opencensus.yaml
- .github/workflows/recaptcha-enterprise.yaml
- .github/workflows/retail.yaml
Scoped to Samples workflows with file names starting with m, n, o, p, q, r.
Implementation of https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3747, sibling of https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3748.
> ci: update m-r workflows to use labeled on pull_request trigger

- .github/workflows/scheduler.yaml
- .github/workflows/secret-manager.yaml
- .github/workflows/security-center-snippets.yaml
- .github/workflows/service-directory-snippets.yaml
- .github/workflows/speech.yaml
- .github/workflows/storagetransfer.yaml
- .github/workflows/talent.yaml
- .github/workflows/texttospeech.yaml
- .github/workflows/translate.yaml
- .github/workflows/video-intelligence.yaml
- .github/workflows/vision-productSearch.yaml
- .github/workflows/vision.yaml
- .github/workflows/workflows.yaml
Scoped to Samples workflows with file names starting with s-z.
Implementation of https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3747, sibling of https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3748.
> ci: update s-z workflows to use labeled on pull_request trigger

- ai-platform/snippets/embedding-model-tuning.js
- ai-platform/snippets/predict-chat-prompt.js
- ai-platform/snippets/predict-code-chat.js
- ai-platform/snippets/predict-code-completion-comment.js
- ai-platform/snippets/predict-code-generation-function.js
- ai-platform/snippets/predict-image-from-image-and-text.js
- ai-platform/snippets/predict-text-embeddings.js
- ai-platform/snippets/predict-text-prompt.js
- ai-platform/snippets/tuning.js
- generative-ai/snippets/function-calling/functionCallingStreamContent.js
- generative-ai/snippets/streamChat.js
- generative-ai/snippets/test/grounding/groundingPublicDataBasic.test.js
No code changes.
Adding `generativeaionvertexai_` region tags to replace old `aiplatform_`
In near future GenAI code samples, will only use `generativeaionvertexai_` region tag prefix.
> docs(generativeai): add region tags for code samples

- generative-ai/snippets/test/grounding/groundingPublicDataBasic.test.js
Fixes a failing test in #3756, which was merged after [I commented on it](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3756#issuecomment-2248938542), but before I was able to submit a working fix.
The test is updated to match the actual output (`["why is the sky blue"]`).
Note: the submitted prompt is `{text: 'Why is the sky blue?'}`.
> fix: failing groundingPublicDataBasic.test.js

- .github/workflows/datastore-functions.yaml
- .github/workflows/dialogflow-cx.yaml
- .github/workflows/dialogflow.yaml
- .github/workflows/discoveryengine.yaml
- .github/workflows/document-ai.yaml
- .github/workflows/document-warehouse.yaml
- .github/workflows/endpoints-getting-started-grpc.yaml
- .github/workflows/endpoints-getting-started.yaml
- .github/workflows/error-reporting.yaml
- .github/workflows/eventarc-generic.yaml
Implementation of #3747, sibling of #3748.
Scoped to Samples workflows with file names starting with d-e, like: datastore, dialogflow, discoveryengine, document-ai, document-warehouse, endpoints, error-reporting, & eventarc.
This batch is by github workflow filename.
> ci: update d-e workflows for labeled on pull_request trigger

- .github/workflows/asset-snippets.yaml
- .github/workflows/auth.yaml
- .github/workflows/batch.yaml
- .github/workflows/cloud-language.yaml
- .github/workflows/cloud-tasks-snippets.yaml
- .github/workflows/cloud-tasks-tutorial-gcf-app.yaml
- .github/workflows/cloud-tasks-tutorial-gcf-function.yaml
- .github/workflows/cloudbuild.yaml
- .github/workflows/composer-functions-composer-storage-trigger.yaml
- .github/workflows/composer.yaml
- .github/workflows/compute.yaml
- .github/workflows/contact-center-insights.yaml
- .github/workflows/container-analysis-snippets.yaml
- .github/workflows/container.yaml
Scoped to Samples workflows with file names starting with a-c.
Implementation of #3747, sibling of #3748. App Engine updates were handled in #3749.
---
> ci: Update a-c workflows for labeled on pull_request trigger

- batch/create/create_gpu_job.js
- batch/create/create_gpu_job_n1.js
- batch/test/create_gpu_job.test.js
- batch/test/create_gpu_job_n1.test.js
> feat: batch_create_gpu_job

- batch/create/create_persistent_disk_job.js
In #3778 new sample created but it's got an incorrect copyright header based on it being a new sample. 
> fix(batch): repair copyright year in header

- batch/create/create_batch_custom_events.js
- batch/create/create_batch_labels_allocation.js
- batch/create/create_batch_labels_job.js
- batch/create/create_batch_labels_runnable.js
- batch/create/create_batch_notifications.js
- batch/create/create_gpu_job.js
- batch/create/create_gpu_job_n1.js
- batch/create/create_local_ssd_job.js
- batch/create/create_nfs_job.js
- batch/create/create_using_secret_manager.js
- batch/test/create_batch_labels_runnable.test.js
> feat: batch_labels_runnable

- compute/disks/createComputeHyperdiskFromPool.js
- compute/disks/createComputeHyperdiskPool.js
- compute/reservations/createReservationFromProperties.js
- compute/test/createComputeHyperdiskFromPool.test.js
- compute/test/createReservationFromProperties.test.js
> feat: compute reservation create

- compute/reservations/reservationVmsUpdate.js
> feat: modify reservation

- .github/blunderbuss.yml
> chore: Remove torus-dpe team from blunderbuss routing

- CODEOWNERS
Fixes b/368475460
Add cloud-samples-infra team as a CODEOWNER of repo-level docs & configuration & CI configuration.
> chore(CODEOWNERS): Add cloud-samples-infra as a repo config owner

- CODEOWNERS
Removes teams that are no long in active use. Any rows that would then be limited to inherited rules were removed.
Fixes b/364335594 for nodejs-docs-samples.
> chore(CODEOWNERS): Remove unused teams

- .github/workflows/security-center-snippets.yaml
The original intention was that Security Center v1 and v2 directories could be independently tested. This was later changed so that the pull request workflow would get triggered for changes in either directory. This pull requests updates the path for merges to main to be consistent with that decision for PRs.
Ideally, this should be merged before #3835.
> chore(security-center): update workflow security center path (include v2)

- compute/disks/createComputeHyperdisk.js
- compute/disks/createComputeHyperdiskFromPool.js
- compute/disks/createComputeHyperdiskPool.js
- compute/reservations/createReservationFromProperties.js
- compute/reservations/createReservationInstanceTemplate.js
- compute/reservations/deleteReservation.js
- compute/reservations/getReservation.js
- compute/reservations/reservationVmsUpdate.js
- compute/test/createComputeHyperdisk.test.js
- compute/test/createComputeHyperdiskFromPool.test.js
- compute/test/createReservationGlobalInstanceTemplate.test.js
- compute/test/createReservationRegionalInstanceTemplate.test.js
- compute/test/reservations.test.js
> improvement: Refactor for compute samples and their tests

- compute/reservations/createInstanceToConsumeAnyReservation.js
- compute/reservations/createInstanceToConsumeSingleProjectReservation.js
- compute/reservations/createInstanceToNotConsumeReservation.js
- compute/reservations/createReservationFromProperties.js
- compute/reservations/createReservationInstanceTemplate.js
- compute/reservations/createTemplateToNotConsumeReservation.js
- compute/test/consumeReservations.test.js
- compute/test/reservations.test.js
- compute/test/util.js
> feat: consume reservations samples

- compute/disks/createComputeHyperdisk.js
- compute/disks/createComputeHyperdiskFromPool.js
- compute/package.json
- compute/reservations/createReservationFromVM.js
- compute/reservations/createSharedReservation.js
- compute/test/consumeReservations.test.js
- compute/test/createComputeHyperdisk.test.js
- compute/test/createComputeHyperdiskFromPool.test.js
- compute/test/createReservationFromVM.test.js
- compute/test/createReservationGlobalInstanceTemplate.test.js
- compute/test/createReservationRegionalInstanceTemplate.test.js
- compute/test/reservations.test.js
- compute/test/sharedReservation.test.js
- compute/test/util.js
> feat: compute_reservation_create_shared, compute_reservation_create_from_vm

- compute/create-instance-templates/createRegionalTemplate.js
- compute/create-instance-templates/deleteRegionalTemplate.js
- compute/create-instance-templates/getRegionalTemplate.js
- compute/test/regionalTemplate.test.js
> feat: add compute_regional_template_create/get/delete

- compute/disks/createComputeHyperdiskPool.js
> improvement: extend compute_hyperdisk_pool_create

- ai-platform/snippets/gemma2PredictGpu.js
Move the region tag to show to documentation users how to call the function.
Fixes cl/679437143
> chore: Update gemma2PredictGpu.js

- ai-platform/snippets/batch-prediction/batch-predict-bq.js
- ai-platform/snippets/batch-prediction/batch-predict-gcs.js
- ai-platform/snippets/test/batch-prediction-gemini.test.js
Add Gemini Batch Prediction samples for GCS and BigQuery.
> feat(genai): add Gemini batch prediction samples

- ai-platform/snippets/embedding-model-tuning.js
- ai-platform/snippets/predict-text-embeddings-preview.js
- ai-platform/snippets/predict-text-embeddings.js
Fixes: b/366507572: Getting embeddings using text-embedding-005
> fix: Getting embeddings using text-embedding-005.

- generative-ai/snippets/function-calling/functionCallingStreamContent.js
> fix: Use USER and ASSISTANT in functionCallingStreamContent.js

- functions/README.md
> Update README.md to reflect Cloud Run functions rebrand

- compute/disks/consistencyGroups/consistencyGroupAddDisk.js
- compute/disks/consistencyGroups/consistencyGroupDisksList.js
- compute/disks/consistencyGroups/consistencyGroupRemoveDisk.js
- compute/disks/consistencyGroups/createConsistencyGroup.js
- compute/disks/consistencyGroups/deleteConsistencyGroup.js
- compute/test/consistencyGroup.test.js
> feat: compute_consistency_group_create/delete/(add/remove)disk/list

- compute/disks/consistencyGroups/consistencyGroupClone.js
- compute/disks/consistencyGroups/stopReplication.js
- compute/test/consistencyGroupClone.test.js
- compute/test/stopReplication.test.js
> feat: compute_consistency_group_clone/stop_replication

- .github/cloud-samples-tools/cmd/main.go
The `git diff` tool appends an extra newline at the end. When the tool parses the diffs files, there's an extra "empty" diff, which is considered as a global change, so all the packages are marked as affected.
Trimming spaces before splitting the diffs into a list solves this.
> fix: testing-isolation trim spaces on diffs

- .github/cloud-samples-tools/cmd/main.go
- .github/cloud-samples-tools/pkg/config/config.go
- .github/cloud-samples-tools/pkg/config/config_test.go
Excluded packages were filtered before checking for global changes. If a package was excluded, then it looked like no packages were found so it was marked as a global change, affecting all packages.
Moving the excluded filtering after checking if a package were found solves this. Also added additional logging, more comments, and a unit test covering this case.
> fix: testing-isolation excluded packages

- .github/cloud-samples-tools/pkg/config/config.go
- .github/cloud-samples-tools/pkg/config/config_test.go
Currently, if all diff files are in the ignore list, it's considered as a global change. This is not necessary since a non-ignored file will return the "." package, which will correctly trigger all tests. If no packages were found that's because files should be ignored and no tests should be run. Added a test case to cover this.
> fix: testing-isolation do not force run all if no packages were found

- datacatalog/cloud-client/createEntryGroup.js
Migrate region "datacatalog_create_entry_group_tag" to "data_catalog_create_entry_group_tag"
Fixes [b/389693076](https://b/389693076)
> fix: (data_catalog) migrate region tag

- datacatalog/cloud-client/lookupEntry.js
Migrate region "datacatalog_delete_fileset_quickstart_tag" to "data_catalog_delete_fileset_quickstart_tag"
Fixes [b/390409205](http://b/390409205)
> fix: (data_catalog) update region tag in lookuptEntry.js

- datacatalog/quickstart/deleteFilesetEntry.js
Migrate region "datacatalog_delete_fileset_quickstart_tag" to "data_catalog_delete_fileset_quickstart_tag"
Fixes [b/389895440](http://b/389895440)
> fix: (data_catalog) migrate region tag in deleteFilesetEntry.js

- datacatalog/quickstart/deleteFilesetEntry.js
Remove region "datacatalog_delete_fileset_quickstart_tag"
Fixes [b/389895440](http://b/389895440)
> fix: (data_catalog) delete deprecated region tag in deleteFilesettEntry

- datacatalog/cloud-client/createEntryGroup.js
Remove region tag "datacatalog_create_entry_group_tag"
Fixes [b/389693076](https://b/389693076)
> fix: (data_catalog) delete deprecated region tag in createtEntryGroup.js

- datacatalog/cloud-client/createFilesetEntry.js
Migrate region "datacatalog_create_fileset_tag" to "data_catalog_create_fileset_tag"
Fixes [b/389810838](http://b/389810838)
> fix: (data_catalog) migrate region tag in createFilesetEntry.js

- appengine/building-an-app/build/server.js
- appengine/building-an-app/build/test/server.test.js
- appengine/building-an-app/update/server.js
- appengine/building-an-app/update/test/server.test.js
- datacatalog/cloud-client/createFilesetEntry.js
- datacatalog/quickstart/createFilesetEntry.js
Fixes 
- [b/391863712](http://b/391863712)
- [b/391865122](http://b/391865122)
> fix: (appengine) update region tag in appengine/building-an-app/build/server.js & appengine/building-an-app/update/server.js

- run/pubsub/Dockerfile
Remove unused "cloudrun_pubsub_dockerfile" region tag
Fixes [b/393605656](b/393605656)
> chore(cloudrun): remove older region tags

- .github/config/nodejs-dev.jsonc
- .github/config/nodejs-prod.jsonc
Ignore ".github/config/" so changes to the configs aren't considered global changes (which cause all packages to be tested)
> fix(ci): don't run all tests on exclusions change

- .github/workflows/ci-dev.yaml
- .github/workflows/ci-prod.yaml
Rename the diffing and ci-setup.json helper tool to `custard` to match name change in `cloud-samples-tools` repo.
> ci: rename testing diff tool to: custard

- .github/config/README.md
- .github/config/nodejs-dev.jsonc
- .github/config/nodejs-prod.jsonc
Document setup files options available for Node.
> docs: document setup files

- .github/config/nodejs-dev.jsonc
- .github/config/nodejs-prod.jsonc
- eventarc/pubsub/ci-setup.json
- eventarc/pubsub/test/deploy.sh
- eventarc/pubsub/test/runner.sh
Adds eventarc/pubsub to new testing infra
> ci(eventarc): onboard pubsub sample to testing isolation

- .github/workflows/ci-dev.yaml
- .github/workflows/ci-prod.yaml
For discoverability, since these workflows create a variable number of jobs. And to help folks find docs by searching on the name.
> ci: include custard name in job names

- .github/config/nodejs-dev.jsonc
- .github/config/nodejs-prod.jsonc
- run/markdown-preview/editor/ci-setup.json
- run/markdown-preview/editor/package.json
- run/markdown-preview/editor/render.js
- run/markdown-preview/editor/test/app.test.js
- run/markdown-preview/editor/test/e2e_test_cleanup.yaml
- run/markdown-preview/editor/test/e2e_test_setup.yaml
- run/markdown-preview/editor/test/system.test.js
- run/markdown-preview/renderer/ci-setup.json
- run/markdown-preview/renderer/package.json
- run/markdown-preview/renderer/test/e2e_test_cleanup.yaml
- run/markdown-preview/renderer/test/e2e_test_setup.yaml
- run/markdown-preview/renderer/test/system.test.js
Migrates the two Markdown Preview services to the new CI
Note: one unit test is marked Skipped and requires NodeJS/sinon expertise to correctly setup mocking etc (example.com does not respond to POST commands)
> ci(markdown): migrate renderer, editor to new CI

- .github/config/nodejs-dev.jsonc
- .github/config/nodejs-prod.jsonc
- recaptcha_enterprise/snippets/package.json
- recaptcha_enterprise/snippets/passwordLeakAssessment.js
- recaptcha_enterprise/snippets/tsconfig.json
> ci(recaptcha): migrate to new CI

- appengine/building-an-app/update/server.js
- appengine/building-an-app/update/test/server.test.js
> chore(gae): Remove older region tags

- endpoints/getting-started/openapi.yaml
Fixes [b/401223470](http://b/401223470)
> chore(endpoints): Update region tag

- CODEOWNERS
Replace outdated cloud-storage-dpe group
> chore: set gcs-sdk-team as CODEOWNERS

- tpu/createStartupScriptVM.js
- tpu/createTopologyVM.js
- tpu/createVM.js
- tpu/queuedResources/createQueuedResource.js
- tpu/queuedResources/deleteQueuedResource.js
- tpu/queuedResources/forceDeleteQueuedResource.js
- tpu/queuedResources/getQueuedResource.js
- tpu/queuedResources/getQueuedResourcesList.js
- tpu/test/forceDeleteQueuedResource.test.js
- tpu/test/queuedResource.test.js
> feat(tpu): Updating TPU samples to use TPUv5e

- run/image-processing/Dockerfile
Fixes [b/393178651](b/393178651)
> chore(cloudrun): migrate region tag "cloudrun_imageproc_dockerfile_imagemagick"

- appengine/building-an-app/build/app.yaml
- appengine/building-an-app/build/test/server.test.js
- appengine/building-an-app/update/app.yaml
Fixes:
- [b/401218453](http://b/401218453)
- [b/401222835](http://b/401222835)
> chore(gae): Migrate region tags from build-an-app

- compute/sendgrid.js
Fixes [b/386956777](http://b/386956777)
> chore(compute): Delete older region tag (compute_send)

- README.md
> chore: update the minimum language based on maintenance mode

- .github/workflows/custard-ci-dev.yaml
- .github/workflows/custard-ci.yaml
- .github/workflows/custard-run-dev.yaml
- .github/workflows/custard-run.yaml
> chore: update custard to v0.2.5

- translate/v3/translate_translate_text.js
Fixes Internal: b/410593527
- Rename region tag `translate_v3_translate_text_0`
- Remove unused region tags
- Add a link to supported MIME types as in the Python sample [translate_v3_translate_text.py#L45-L48](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/translate/samples/snippets/translate_v3_translate_text.py#L45-L48).
See also the [discussion](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/13255#discussion_r2015559062) about this link.
- Make consistent the use of periods at the end of a comment across the file
> chore(translate): rename region tag, delete unused region tags, and add link to supported MIME types.

- endpoints/getting-started-grpc/README.md
- endpoints/getting-started-grpc/client.js
- endpoints/getting-started-grpc/package.json
- endpoints/getting-started-grpc/server.js
> chore(grpc): migrate from grpc to @grpc/grpc-js in getting-started-grpc example

- .github/workflows/custard-ci-dev.yaml
- .github/workflows/custard-ci.yaml
- .github/workflows/custard-run-dev.yaml
- .github/workflows/custard-run.yaml
Updates custard to current latest version. 
Should correct tests to run from forks after approval from a maintainer.
> chore(deps): update custard to 0.3.2

- .github/workflows/custard-run-dev.yaml
- .github/workflows/custard-run.yaml
Cloud Run tests expect the service account variable be named `SERVICE_ACCOUNT`. The setup-custard action doesn't include an input to pass and re-export the variable, but that will go away with the self-contained runner. Renaming it to `SERVICE_ACCOUNT` is also what the self-contained runner expects.
> fix: rename service account env var

- .github/workflows/custard-run-dev.yaml
- .github/workflows/custard-run.yaml
It turns out that [`setup-custard`](https://github.com/GoogleCloudPlatform/cloud-samples-tools/blob/v0.3.2/actions/steps/setup-custard/action.yaml) overrides and clears up the SERVICE_ACCOUNT variable.
Even though the input is referenced, it's not defined and can't be passed.
This will no longer be an issue when https://github.com/GoogleCloudPlatform/cloud-samples-tools/pull/49 merges, and it will handle the environment variables as expected.
Once that merges, we can get rid of the `setup-custard` action altogether.
Instead of going through the whole cycle of fixing that action and releasing a new version, we pass the SERVICE_ACCOUNT directly to the step running the tests as a workaround.
This can go away once we use the TS runner.
> fix: pass service account directly to run step

- .github/workflows/custard-run-dev.yaml
- .github/workflows/custard-run.yaml
Since these run from workflow_run, the default checkout branch is main, not the PR commit.
Explicitly reference the commit SHA from the workflow_run event (the PR).
> fix: checkout correct commit on workflow_run jobs

- .github/workflows/custard-run.yaml
Follow up to https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/4091
Fixes `test` which was missed by the other PR.
> fix: checkout correct commit on tests

- genai/count-tokens/counttoken-with-txt.js
- genai/package.json
- genai/test/counttoken-with-txt.test.js
- genai/test/textgen-sys-instr-with-txt.test.js
- genai/test/textgen-with-multi-img.test.js
- genai/test/textgen-with-txt-img.test.js
- genai/test/textgen-with-txt-stream.test.js
- genai/test/textgen-with-txt.test.js
- genai/test/textgen-with-video.test.js
- genai/test/tools-func-desc-with-txt.test.js
- genai/text-generation/textgen-sys-instr-with-txt.js
- genai/text-generation/textgen-with-multi-img.js
- genai/text-generation/textgen-with-txt-img.js
- genai/text-generation/textgen-with-txt-stream.js
- genai/text-generation/textgen-with-txt.js
- genai/text-generation/textgen-with-video.js
- genai/tools/tools-func-desc-with-txt.js
Fixes b/415995543 - Add GenAI SDK samples (1)
- Text generation with text
- Text generation streaming
- Text generation with image
- Text generation with video
- System instructions
- Function calling
- Count tokens
> feat(genai): Add GenAI SDK samples (1)

- secret-manager/regional_samples/iamGrantAccessWithRegionalSecret.js
- secret-manager/regional_samples/iamRevokeAccessWithRegionalSecret.js
> **Note**: Any check with `(dev)`, `(experimental)`, or `(legacy)` can be ignored and should **not block** your PR from merging (see [CI testing](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md#ci-testing)).
> Style(secretmanager): Update the region tags to match other languages.

- genai/image-generation/imggen-mmflash-with-txt.js
- genai/test/imggen-mmflash-with-txt.test.js
- genai/test/tools-code-exec-with-txt.test.js
- genai/tools/tools-code-exec-with-txt.js
Add image generation and code execution examples.
For Quickstart.
> feat(genai): Add image generation and code execution examples

- secret-manager/getSecret.js
- secret-manager/test/secretmanager.test.js
Adds consistency; try/catch; 
> **Note**: Any check with `(dev)`, `(experimental)`, or `(legacy)` can be ignored and should **not block** your PR from merging (see [CI testing](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md#ci-testing)).
> fix: standardize getSecret sample

- genai/text-generation/textgen-with-txt-img.js
Update model used in image generation code sample
> docs: Update image understanding model

- secret-manager/bindTagsToSecret.js
- secret-manager/createSecretWithTags.js
- secret-manager/package.json
- secret-manager/regional_samples/bindTagsToRegionalSecret.js
- secret-manager/regional_samples/createRegionalSecretWithTags.js
- secret-manager/test/secretmanager.test.js
Created samples for Global and Regional Secret Manager API
1. Create Secret With Tags
2. Bind Tags to Secret
Ref: https://cloud.google.com/secret-manager/docs/create-and-manage-tags 
Additionally, in certain tests, some resources were not properly deleted; therefore, I have updated the tests accordingly.
> feat(secretmanager): Added samples for tags field

- retail/interactive-tutorials/search/search-with-ordering.js
Addresses introduced in in #4131
Change in https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/4131#discussion_r2206094099 introduced a new region tag that doesn't make the same sample in other repos. 
This PR reverts that change for consistency with other samples: 
* https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/retail/interactive-tutorials/search/search_with_ordering.py#L17
* https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/retail/interactive-tutorials/src/main/java/search/SearchWithOrdering.java#L24
* https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/main/retail/interactive-tutorial/RetailSearch.Samples/SearchWithOrderingSample.cs#L16
> **Note**: Any check with `(dev)`, `(experimental)`, or `(legacy)` can be ignored and …
> chore(retail): Correct region tag for consistency

- recaptcha_enterprise/demosite/app/package.json
The previous repo is deprecated. All of its content and history has been moved to google-cloud-node.
> fix: Update repository URL

- .github/config/nodejs-dev.jsonc
- .github/config/nodejs.jsonc
Follow up to #4145, removing Custard config references to flakybot.yaml, which is no longer in the repository.
Addresses b/434770885 (Complete flakybot deprecation) for this repo.
> **Note**: Any check with `(dev)`, `(experimental)`, or `(legacy)` can be ignored and should **not block** your PR from merging (see [CI testing](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md#ci-testing)).
> chore: remove Custard config references to flakybot.yaml

- genai/test/tools-vais-with-txt.test.js
> **Note**: Any check with `(dev)`, `(experimental)`, or `(legacy)` can be ignored and should **not block** your PR from merging (see [CI testing](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md#ci-testing)).
> feat(genai): Commenting out Vias Tools test
