GoogleCloudPlatform/nodejs-docs-samples

- appengine/bower/app.yaml
- appengine/express-memcached-session/app.yaml
- appengine/express/app.yaml
- appengine/geddy/app.yaml
- appengine/grunt/app.yaml
- appengine/hapi/app.yaml
- appengine/koa/app.yaml
- appengine/kraken/app.yaml
- appengine/loopback/app.yaml
- appengine/mailgun/app.yaml
- appengine/mongodb/app.yaml
- appengine/redis/app.yaml
- appengine/restify/app.yaml
- appengine/sails/app.yaml
- appengine/webpack/app.yaml
> Skip node_modules for better deployments.

- datastore/concepts.js
Making this code snippet consistent with the corresponding docs and all the rest of the instances of 'sampleTask' in this file.
> Change 'sampletask' to 'sampleTask' for consistency

- datastore/concepts.js
- datastore/package.json
- datastore/tasks.js
- test/datastore/entity.test.js
- test/datastore/index.yaml
- test/datastore/indexes.test.js
- test/datastore/metadata.test.js
- test/datastore/query.test.js
- test/datastore/transaction.test.js
- test/datastore/util.js
This can be merged to master when Datastore v1beta3 is released.
> Added back datastore v1beta3 samples.

- monitoring/list_resources.js
See https://github.com/GoogleCloudPlatform/python-docs-samples/issues/227
> Fix metric filter call

- containerengine/hello-world/server.js
> containerengine/hello-world: two spaces for indentation

- language/analyze.js
Also logs errors to the console.
> Adding missing error parameter to callback

- appengine/errorreporting/test/app.test.js
- bigquery/system-test/quickstart.test.js
- translate/system-test/translate.test.js
- translate/test/translate.test.js
- translate/translate.js
Same changes as the recent Cloud Storage PR.
> Simplify Translate samples and bring up to standard.

- monitoring/create_custom_metric.js
These samples will be replaced soon but in the meantime our docs are mixed up.
> Add region tags for writing timeseries

- functions/uuid/index.js
See cl/145830521 for explanations.
> Update the uuid sample for cross-product consistency

- package.json
> Update NL client library version

- package.json
- scripts/clean
- storage/README.md
- storage/acl.js
- storage/buckets.js
- storage/encryption.js
- storage/files.js
- storage/iam.js
- storage/package.json
- storage/quickstart.js
- storage/system-test/buckets.test.js
- storage/system-test/encryption.test.js
- storage/system-test/files.test.js
- storage/system-test/quickstart.test.js
- storage/yarn.lock
- yarn.lock
Also added a script for cleaning up orphaned test Cloud Storage buckets.
> Bring Storage samples up to standard.

- video/analyze.js
- video/quickstart.js
Per @frankyn, the faces API doesn't support this behavior - so this PR removes it.
> Remove "entire video" detection from faces

- speech/README.md
> Regenerate Speech README

- iot/README.md
1. gcloud alpha should be gcloud beta
2. --pubsub-topic should be --event-pubsub-topic
3. Updated the link to the docs
4. Added info about the Publisher role for the Pub/Sub topic
> Small fixes to README.md

- README.md
- circle.yml
- video/README.md
- video/analyze.js
- video/package.json
- video/quickstart.js
- video/system-test/analyze.test.js
- video/system-test/quickstart.test.js
Reverts GoogleCloudPlatform/nodejs-docs-samples#505
> Temporarily revert "Remove video samples which have moved."

- functions/datastore/README.md
- functions/gcs/README.md
- functions/imagemagick/README.md
- functions/pubsub/README.md
- functions/uuid/README.md
> Removed --stage-bucket param from README files

- functions/http/index.js
> GCF: clarify where 'name=John' example applies

- appengine/redis/package.json
This will enable us to run the auto-update script against this sample
> Add (smoke) test to GAE Redis sample

- appengine/pubsub/package.json
See https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/607 for more information.
> Fixed a bug introduced by pug 2.0.0.

- appengine/sendgrid/README.md
> fix: update sendgrid docs link

- .kokoro/functions-helloworld.sh
- functions/helloworld/package.json
Switch to `gcloud functions` after `gcloud` update on docker image.
> Export necessary environment variables

- .kokoro/functions-helloworld.sh
- circle.yml
- functions/background/package.json
- functions/datastore/package.json
- functions/gcs/package.json
- functions/helloworld/package.json
- functions/helloworld/test/sample.system.storage.test.js
- functions/helloworld/test/updateFunctions.sh
- functions/http/package.json
- functions/imagemagick/package.json
- functions/log/package.json
- functions/pubsub/package.json
- functions/sendgrid/package.json
- functions/spanner/package.json
- functions/tips/package.json
- functions/uuid/package.json
Drive-by fix: delete semistandard from global depenencies
Use correct bucket and region variable.
Do not merge - PR to see Kokoro failures.
> Fix error message, explicitly delete legacy formatted functions

- .kokoro/appengine/test-deployment/common.cfg
- .kokoro/appengine/test-deployment/hello-world-flex.cfg
- .kokoro/appengine/test-deployment/hello-world-standard.cfg
- .kokoro/appengine/test-deployment/metadata-flex.cfg
- .kokoro/appengine/test-deployment/metadata-standard.cfg
- .kokoro/appengine/test-deployment/storage-flex.cfg
- .kokoro/appengine/test-deployment/storage-standard.cfg
- .kokoro/build-with-appengine.sh
Use the correct PROJECT to `cd` into in the deployment tests.
> Fix Kokoro config

- .kokoro/build-with-appengine.sh
> Fix version string

- functions/helloworld/index.js
> Add ExpressJS links

- functions/firebase/index.js
(Self-merging, since this is a somewhat-urgent && fairly minor change.)
> Add license header

- appengine/analytics/package.json
- appengine/building-an-app/build/package.json
- appengine/building-an-app/update/package.json
- appengine/cloudsql/package.json
- appengine/cloudsql_postgresql/package.json
- appengine/datastore/package.json
- appengine/errorreporting/package.json
- appengine/hello-world/standard/package.json
- appengine/loopback/package.json
- appengine/mailjet/package.json
- appengine/memcached/package.json
- appengine/metadata/flexible/package.json
- appengine/metadata/standard/package.json
- appengine/mongodb/package.json
- appengine/parse-server/package.json
- appengine/pubsub/package.json
- appengine/redis/package.json
- appengine/sendgrid/package.json
- appengine/static-files/package.json
- appengine/storage/standard/package.json
- appengine/twilio/package.json
Users might be using a version higher than 8, we expect these samples to work.
> Use >=8 as Node.js version instead of 8.x.x

- functions/uuid/README.md
Function name in index.js is not consistent with Deploy command on README
> Updating deploy function script on README

- appengine/loopback/package.json
> Fix loopback test

- functions/node8/index.js
- functions/node8/test/index.test.js
> Add [region tags for] Node 8 background snippets

- functions/helloworld/package.json
functions/helloworld presubmit is failing. Disabling the tests to
finally get to a green CI.
> Skip unit and integration tests for broken functions/helloworld

- functions/ocr/app/config.default.json
- functions/ocr/app/test/index.test.js
Fixes: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/802
> Delete unused variable in ocr

- cloud-sql/postgres/knex/package.json
- iot/beta-features/gateway/package.json
- iot/http_example/package.json
- iot/mqtt_example/package.json
- memorystore/redis/package.json
- storage-transfer/package.json
Updat everything that is not in appengine or functions
Refs: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/996
Refs: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/995
> Delete unused dependencies

- functions/sendgrid/index.js
- functions/sendgrid/package.json
- functions/sendgrid/test/index.test.js
Fixes: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/949
Fixes: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/986
> fix(deps): update dependency @google-cloud/bigquery to v2

- iot/manager/manager.js
- iot/mqtt_example/cloudiot_mqtt_example_nodejs.js
This is to address [this issue](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1073).
> Adds comments clarifying subfolder requirements for commands

- functions/speech-to-speech/index.js
Hi,
This PR adds `[START tag]` and `[END tag`] markers to delimit the code to use in tutorial.
Let me know if you have any questions.
Thank you!
> Adds markers to use code snippets in tutorial.

- iot/mqtt_example/README.md
Updating the CLI broke the tutorial, so was asked to update the README.
> iot: update mqtt readme after the CLI update

- appengine/building-an-app/update/package.json
- appengine/building-an-app/update/test/server.test.js
> refactor(building-an-app):ava to mocha

- functions/slack/package.json
- functions/slack/test/index.test.js
> refactor(function-slack):ava to mocha

- appengine/cloudsql/package.json
- appengine/cloudsql/test/createTables.test.js
- appengine/cloudsql/test/server.test.js
> refactor(cloudsql):ava to mocha

- appengine/storage/flexible/package.json
- appengine/storage/flexible/system-test/app.test.js
- appengine/storage/standard/package.json
- appengine/storage/standard/system-test/app.test.js
> refactor(appengine-storage):ava to mocha

- appengine/cloudsql_postgresql/package.json
- appengine/cloudsql_postgresql/test/createTables.test.js
- appengine/cloudsql_postgresql/test/server.test.js
> refactor(cloudsql_postgresql):ava to mocha

- appengine/mongodb/README.md
Update the link to the community tutorial. The old link redirects to this sample.
> Update Readme for appengine/mongodb

- functions/background/package.json
- functions/composer-storage-trigger/package.json
- functions/datastore/package.json
- functions/env_vars/package.json
- functions/errorreporting/package.json
- functions/firebase/package.json
- functions/log/package.json
- functions/ocr/app/package.json
- functions/pubsub/package.json
- functions/scheduleinstance/package.json
- functions/slack/package.json
- functions/spanner/package.json
- functions/sql/package.json
- functions/tips/package.json
- functions/uuid/package.json
Reduce some of the churn caused by renovate bot by making dependency
versions more flexible.
> Allow minor and patch updates in functions/

- functions/sql/package.json
> Allow patches of dependencies in functions/sql

- .eslintrc.yml
- appengine/loopback/server/server.js
- appengine/mailjet/app.js
- cloud-sql/mysql/mysql/views/index.pug
- containerengine/hello-world/server.js
- functions/composer-storage-trigger/index.js
- functions/imagemagick/test/index.test.js
- iot/beta-features/gateway/gateway.js
- iot/http_example/cloudiot_http_example.js
- iot/mqtt_example/cloudiot_mqtt_example_nodejs.js
- storage-transfer/system-test/transfer.test.js
- storage-transfer/transfer.js
This PR includes a change to the `.eslint.yml` to enable `no-var`.  The only other changes are from running `eslint --fix`.
> refactor(lint): enable the `no-var` eslint rule

- .eslintrc.yml
- appengine/loopback/common/models/message.js
- appengine/loopback/server/server.js
- appengine/mailjet/app.js
- cloud-sql/mysql/mysql/server.js
- functions/composer-storage-trigger/index.js
- functions/dialogflow/functions/test/index.test.js
- functions/http/index.js
- functions/speech-to-speech/functions/index.js
- functions/speech-to-speech/functions/test/index.test.js
- functions/speech-to-speech/functions/test/sample.integration.http.test.js
- healthcare/dicom/dicomweb.js
- healthcare/fhir/fhir_resources.js
- iot/beta-features/gateway/gateway.js
- iot/http_example/cloudiot_http_example.js
- iot/manager/manager.js
- iot/mqtt_example/cloudiot_mqtt_example_nodejs.js
- opencensus/metrics-quickstart.js
- storage-transfer/transfer.js
Enables the `prefer-arrow-callback` rule in eslint, and runs `fix` to update all instances.
> refactor(lint): prefer arrow callbacks

- cloud-sql/mysql/mysql/package.json
- cloud-sql/mysql/mysql/test/server.test.js
Towards #1080
refactor cloud-sql/mysql tests to mocha
> refactor(cloud-sql/mysql):ava to mocha

- appengine/websockets/package.json
- appengine/websockets/test/index.test.js
towards #1080 
refactor appengine/websockets tests from ava to mocha
> refactor(appengine/websockets): ava to mocha

- appengine/endpoints/package.json
- appengine/endpoints/test/app.test.js
Towards #1080 
refactor appengine/endpointstests from ava to mocha.
> refactor(appengine/endpoints): ava to mocha

- appengine/building-an-app/build/package.json
- functions/composer-storage-trigger/package.json
towards #1080 
correct the test script in functions/composer-storage-trigger to use mocha 
also remove unused ava dev-dependancy from appengine/building-an-app/build
> refactor(fix test script in functions/composer-storage-trigger)

- appengine/memcached/app.js
- appengine/memcached/package.json
- Add test
- Use eslint
- Use `async`/`await`
> Update memcache sample

- appengine/sendgrid/app.js
(Self-merging, as this is a minor change.)
> Remove stray debug statement

- .kokoro/build.sh
- iot/manager/manager.js
- iot/manager/package.json
- iot/manager/system-test/manager.test.js
- iot/mqtt_example/system-test/cloudiot_mqtt_example.test.js
Switch `sendCommand` sample to use `nodejs-iot` library
> iot: fix commands related tests

- .kokoro/require-system-tests.cfg
- .kokoro/require-system-tests.sh
**Note:** I didn't fix any of the errors thrown by this script (they're mostly in the `functions` directory).
@fhinkel let me know if I should fix those in this PR or a separate one. My thoughts:
1. Merge this
2. Merge PR fixing this (or at least adding `kokoro-allow-mock` comments - though I can do that in this PR too)
3. Add to CI
> Add system test checker

- .kokoro/build.sh
- .kokoro/cloudsql-postgres.cfg
- cloud-sql/mysql/mysql/package.json
- cloud-sql/mysql/mysql/server.js
- cloud-sql/postgres/knex/.cloud-repo-tools.json
- cloud-sql/postgres/knex/createTable.js
- cloud-sql/postgres/knex/package.json
- cloud-sql/postgres/knex/server.js
- cloud-sql/postgres/knex/test/createTable.test.js
- cloud-sql/postgres/knex/test/server.test.js
(@kurtisvg as FYI. Please **do not review** before Monday morning.)
> Update Cloud SQL sample (Node 8 + system tests)

- appengine/memcached/README.md
> Memcached sample: add tutorial link

- functions/ocr/app/index.js
Fixes https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1316
> Fix outdated call to publisher.publish

- functions/helloworld/index.js
Changes were made in #1232; this reverts them (based on customer feedback).
> Revert changes to helloHttp

- appengine/endpoints/README.md
b/133157690
Fixes https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/851.
> Endpoints README 404

- functions/background/README.md
Fixes broken link (only 1 unique found).
Fixes #994.
> docs: Fix functions background tutorial link. Fixes #994

- functions/firebase/index.js
- functions/firebase/package.json
- functions/firebase/test/index.test.js
- functions/node8/index.js
- functions/node8/test/index.test.js
Note: I didn't update the `assert` styles here, since I'm planning to do that in a later PR. (And ideally, I'll find a lint rule for it. 🙂)
> Firebase: print params

- functions/pubsub/index.js
As requested by @labtopia; will merge if they LGTM.
> Remove stray alpha statement

- functions/ocr/README.md
Fixes https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1396
> Fix link in README.md

- functions/imagemagick/index.js
1. This specifically mentions Cloud Function, hindering reuse with other products
2. I do not believe this comment is enough to explain the approach you are trying to communicate, instead this seems like it should be a paragraph in the tutorial.
> Remove comment explaining blurred prefix approach

- CODEOWNERS
> Delete surferjeff from OWNERS as requested

- auth/auth.js
Fixes https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1442
> Fix typo in URL in auth.js

- run/pubsub/.envrc
Oops. I've added this to my .gitignore so it shouldn't happen again.
> Remove accidentally committed .envrc

- endpoints/getting-started-grpc/client.js
> Endpoints: add missing region tags

- iot/manager/system-test/manager.test.js
Skip these tests until the API change was rolled back (or the tests adapted). 
Refs: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1527
> Skip broken IoT tests

- CODEOWNERS
Updating since @santhoshvaddi no longer works on this team.
> Update {dialogflow -> tokenservice} functions CODEOWNERS

- .kokoro/build-with-appengine.sh
- .kokoro/build-with-run.sh
- .kokoro/build.sh
Fixes: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1681
> fix: use unique logfile names

- functions/ci_cd/cloudbuild.yaml
@labtopia FYI - this will require an update to the docs
(**Motivation:** we're adding [Java](https://github.com/GoogleCloudPlatform/java-docs-samples/pull/2615) and [Python](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/3324) versions of this sample.)
> GCF CI/CD: Use consistent region tags across languages

- functions/slack/index.js
- functions/slack/test/index.test.js
**Do not merge** until @labtopia updates the docs accordingly.
> functions/slack: config.json -> env vars

- cloud-sql/mysql/mysql/server.js
- cloud-sql/mysql/mysql/test/server.test.js
- cloud-sql/postgres/knex/server.js
- cloud-sql/sqlserver/mssql/server.js
> fix(#1781): Handle promise rejections in CloudSQL samples

- functions/log/package.json
- functions/log/test/index.test.js
> GCF logging: take 2 of #1734 (metrics sample deletion)

- .kokoro/appengine/common.cfg
- .kokoro/cloud-tasks/common.cfg
- .kokoro/functions/common.cfg
- .kokoro/iot/common.cfg
- .kokoro/run/common.cfg
Fixes https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1681
> fix: export xml test results

- auth/auth.js
we were following the old sample format, resulting in code that breaks when copy pasted.
> fix(samples): auth samples used top level await

- cloud-sql/mysql/mysql/server.js
- cloud-sql/sqlserver/mssql/server.js
> fix(cloud-sql): added return statements to fix 'http headers sent' error

- functions/tips/index.js
> Clarify infinite retries example

- functions/billing/index.js
Minor update to convert JSON object to string for sample code
> Update NodeJS billing sample code

- run/events-pubsub/app.js
- run/events-storage/app.js
Moves region tags to simplify sample to be used with docs.
> run: events region tags

- run/events-storage/README.md
Brushes up the readme for Run Events.
> run: events brushup

- healthcare/fhir/updateFhirResource.js
> healthcare API: add comment clarifying FHIR update resource

- functions/billing/index.js
Updating sample code based on Node 10 runtime environment variable changes: https://cloud.google.com/functions/docs/env-var#environment_variables_set_automatically
> Billing code sample function change

- endpoints/getting-started-grpc/README.md
https://cloud.google.com/sdk/gcloud/reference/builds/submit
> Fixing container build command in README.md

- .kokoro/build-with-run.sh
- run/hello-broken/package.json
- run/logging-manual/package.json
- run/markdown-preview/editor/package.json
> test(run)!: rename npm script e2e-test to system-test

- functions/helloworld/index.js
Use better naming of variables and make sure documentation is consistent with function definitions
> Improve cloud function example variable names and function documentation

- run/events-pubsub/app.js
Log message in addition to returning the response, as per the design doc.
> fix: update run_events_pubsub to also console log

- .kokoro/run/common.cfg
- run/events-pubsub/Dockerfile
- run/events-pubsub/package.json
- run/events-storage/Dockerfile
- run/events-storage/package.json
- run/hello-broken/Dockerfile
- run/helloworld/Dockerfile
- run/image-processing/Dockerfile
- run/image-processing/package.json
- run/logging-manual/Dockerfile
- run/pubsub/Dockerfile
- run/pubsub/package.json
Fixes #1917
Waiting on automated testing to confirm this is in working order.
Note this change does not include adjustments for idiomatic language updates, those are pending Node v14 updates.
> run: update to Node.js 12

- healthcare/fhir/importFhirResources.js
Fixes https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1947
Also error logs are no longer returned in the response proto, they are instead logged in Cloud Logging.
> healthcare API: increase sleep time for FHIR import LRO

- functions/firebase/index.js
Related to #1962 and b/162554971
(**Analytics sample update is blocked** due to backend issues; sent a ping to the product team via email.)
> chore(functions/firebase): use Node 12 function signatures

- .kokoro/functions/firebase.cfg
- functions/firebase/index.js
- functions/firebase/test/index.test.js
> chore(functions/firebase): fix samples + tests not running

- eventarc/audit-storage/app.js
- eventarc/audit-storage/test/app.test.js
Changes the log for CAL events.
> eventarc: cal event log

- cloud-sql/mysql/mysql/server.js
> chore: remove unmatched end region tag

- CONTRIBUTING.md
Clarify contributing guidelines for other repos and the `functions` folder.
> chore: clarify contributing guidelines

- package.json
ref: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/2030
> chore: remove unused dependency in top level

- .eslintignore
- run/idp-sql/.eslintrc.json
- run/idp-sql/handlebars.js
- run/idp-sql/test/system.test.js
Fixes https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/2030
> chore: turn on linting for run/idp-sql

- iot/http_example/cloudiot_http_example.js
- iot/http_example/package.json
Fixes: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/2001
internal b/171857357
> chore: use fetch instead of request

- appengine/metadata/flexible/package.json
- appengine/metadata/flexible/server.js
- appengine/metadata/standard/package.json
- appengine/metadata/standard/server.js
> chore: replace got with node-fetch

- .kokoro/build.sh
- CODEOWNERS
Ref: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/2082
> chore: cleanup leftover IoT references

- appengine/metadata/flexible/server.js
- appengine/metadata/standard/server.js
> test: fix appengine metadata tests

- .gitignore
- .kokoro/build.sh
- cloud-sql/mysql/mysql/package.json
- cloud-sql/mysql/mysql/server.js
- cloud-sql/mysql/mysql/test/server-unix.test.js
- cloud-sql/postgres/knex/createTable.js
- cloud-sql/postgres/knex/server.js
- cloud-sql/postgres/knex/test/createTable.test.js
- cloud-sql/postgres/knex/test/server.test.js
> Added unix socket connectivity tests to Cloud SQL

- endpoints/getting-started-grpc/client.js
- endpoints/getting-started-grpc/server.js
Chore: Update endpoints/getting-started-grpc to use @grpc/grpc-js 
Fixes https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/2076
> Chore: Update endpoints/getting-started-grpc to use @grpc/grpc-js

- composer/functions/composer-storage-trigger/index.js
- [Relevant tutorial](https://cloud.google.com/composer/docs/how-to/using/triggering-with-gcf#triggering-with-gcf-creating-a-function-nodejs)
- [Successful Dag run](https://screenshot.googleplex.com/4KjHbaeahSDWZeh)
- [Function that triggered dag run](https://screenshot.googleplex.com/7XhYYHVgZa4Qj4G)
- [Equivalent Python PR](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/5193/files)
> add replace_microseconds parameter

- run/idp-sql/setup.sh
* ~Cloud Run Invoker role required for new Service account~
* Fix Spelling of service account to match postcreate.sh value
* Fix sed command (lines 42-46 are correct, lines 24-25 aren't)
@averikitsch
> [run/idp-sql] Correct some issues when using Cloud Run button

- run/hello-broken/test/system.test.js
> fix(run): remove retries from bad request test

- functions/concepts/index.js
- functions/concepts/termination.js
> chore(functions): add node termination example

- run/logging-manual/package.json
- run/logging-manual/test/system.test.js
Fixes: #2169 #2170 #2171 #2172 #2173 #2174 #2175
> fix(run): Update Logging test with retries

- appengine/typescript/package.json
> fix: add production dependency for GAE app

- functions/concepts/termination.js
> feat(functions): add HTTP termination example

- appengine/typescript/package.json
- functions/scheduleinstance/index.js
- functions/scheduleinstance/test/index.test.js
> fix(functions/scheduledinstance): Update JSON parsing and sample tests

- eventarc/audit-storage/Dockerfile
- eventarc/audit-storage/app.js
- eventarc/audit-storage/index.js
Updates region tags to use `audit_storage`, not `gcs`.
These aren't in the docs, please merge this when approved.
> chore(eventarc): update region tags

- functions/firebase/index.js
- functions/firebase/test/index.test.js
> chore(functions): remove RTDB path params

- CODEOWNERS
> chore(appengine): update CODEOWNERS

- composer/composer_transform_csv_to_json.js
Dataflow doesn't like consts 😢  - https://screenshot.googleplex.com/48jminx5bg4KBhB https://screenshot.googleplex.com/6RhhCg2vSscqYNk
But Dataflow likes vars! https://screenshot.googleplex.com/BGBq8rrU8rV43E8
> fix: switch const to var to make dataflow happy

- functions/imagemagick/index.js
[docs](https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fspromises_unlink_path)
> refactor: use node's native promisified fs

- CODEOWNERS
Add @fhinkel and @sofisl explicitely as codeowners for all folders so
that we can turn on "Require review from Code Owners".
> Add repo-owners to code owners

- run/idp-sql/test/system.test.js
> Add retries to Run tests

- run/idp-sql/test/system.test.js
> fix(run): run test retries

- functions/tips/index.js
- functions/tips/test/index.test.js
> fix: function test updates

- CODEOWNERS
Grant has changed teams, so I'm removing him from the sample owners list (subject to his approval).
> chore(CODEOWNERS): Remove grant as functions owner

- .github/workflows/ci.yaml
- CONTRIBUTING.md
- README.md
- appengine/README.md
- appengine/endpoints/README.md
- functions/README.md
- linkinator.config.json
- monitoring/opencensus/README.md
- monitoring/prometheus/README.md
- run/idp-sql/README.md
- workflows/quickstart/README.md
Fixes #2258 and prevents it moving forward.
> build: perform 404 scanning on docs

- functions/v2/index.js
- functions/v2/package.json
- functions/v2/test/index.test.js
Similar to #2299, but for Cloud Storage
> feat(functions): {add GCS, refactor other} v2 sample

- cloud-sql/postgres/knex/server.js
> Update config settings inside pool.

- functions/helloworld/package.json
- functions/helloworld/test/sample.integration.pubsub.test.js
- functions/helloworld/test/sample.system.http.test.js
- functions/helloworld/test/sample.system.pubsub.test.js
- functions/helloworld/test/sample.system.storage.test.js
Motley bag of fixes that should unblock #2400
> chore(functions/helloworld): fix failing tests

- functions/v2/index.js
Requested by @labtopia 
@matthewrobertson FYI
> chore(functions/v2): fix region tags

- functions/helloworld/index.js
> chore(functions/helloworld): fix incorrectly documented error behavior

- functions/tips/index.js
> fix(functions/tips): document correct retry behavior

- functions/v2/package.json
- functions/v2/test/system.test.js
**Confirmed** the new library version works on Cloud Functions.
> chore(functions/gce-cal): update GCE library + fix typo

- functions/helloworld/test/sample.integration.storage.test.js
> fix(functions): keep ffProc code within sample

- functions/v2/index.js
> fix(functions/v2): add missing region tags

- functions/helloworld/index.js
- functions/helloworld/package.json
- functions/helloworld/test/sample.unit.http.test.js
This brings it into line with the rest of the v2 samples.
> feat(functions/helloworld): Use declarative syntax for http sample

- run/jobs/test/system.test.js
> chore: extend log polling

- datastore/functions/package.json
- functions/billing/package.json
- functions/helloworld/package.json
- functions/imagemagick/package.json
- functions/pubsub/package.json
- functions/speech-to-speech/functions/package.json
- functions/v2/package.json
- run/idp-sql/package.json
Have to upgrade dependencies manually to ensure that tests pass, since actions are failing from a fork currently.
> build: ugprade googleapis. winston, and functions/framework

- functions/helloworld/index.js
> chore(functions/storage): clarify comments

- run/jobs/index.js
- run/jobs/test/e2e_test_setup.yaml
- run/jobs/test/index.test.js
- run/jobs/test/retry.sh
- run/jobs/test/system.test.js
> chore(run/jobs): update number of tasks run

- cloud-sql/mysql/mysql/README.md
- cloud-sql/postgres/knex/README.md
> chore(cloudsql): update dir path for unix socket proxy launch command

- functions/ocr/app/package.json
> chore(functions/ocr): remove unused dependency

- functions/helloworld/index.js
> chore(functions/helloworld): update product name

- .github/workflows/functions-v2-autolabelinstance.yaml
- functions/v2/autoLabelInstance/index.js
- functions/v2/autoLabelInstance/package.json
- functions/v2/autoLabelInstance/test/index.test.js
- functions/v2/autoLabelInstance/test/system.test.js
Copied from samples in [this directory](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/main/functions/v2).
Those will be deleted once everything is moved over.
Part of b/229394231
> chore(functions): move autoLabelInstance to separate directory

- functions/helloworld/index.js
> fix(functions): update error reporting comments

- composer/composer_transform_csv_to_json.js
> build: update sample to use var

- run/idp-sql/test/system.test.js
Related Issue: #2670 
Flaky test failures linking to inconsistent presence of valid auth token.
Adding retry within api when token is originally fetched and additional assertions 
to be able to track if this error should happen again. 
related log: https://cloudbuild.googleapis.com/v1/projects/nodejs-docs-samples-tests/locations/global/builds/36d84062-6294-4e61-94f8-a772d6bfac5c
> fix(issue-2670): adding additional retries & asserts

- .kokoro/run/common.cfg
> feat!: upgrade Cloud Run tests to Node 14

- run/idp-sql/Dockerfile
- run/idp-sql/package.json
- run/idp-sql/test/system.test.js
Fixes #2706
(This required some refactoring to get tests passing. I also added error message print-outs, in case this code fails in the future.)
> fix(run/idp-sql): update Firebase Admin to v11 + fix tests

- CODEOWNERS
@iennae @grayside please LGTM.
> chore: update CODEOWNERS for serverless samples

- eventarc/audit-storage/package.json
- eventarc/audit-storage/test/system.test.js
> fix(issue-2719): upping timeout ms & adding try/catch

- .github/workflows/appengine-analytics.yaml
- .github/workflows/appengine-building-an-app-build.yaml
- .github/workflows/appengine-building-an-app-update.yaml
- .github/workflows/appengine-datastore.yaml
- .github/workflows/appengine-endpoints.yaml
- .github/workflows/appengine-hello-world-flexible.yaml
- .github/workflows/appengine-hello-world-standard.yaml
- .github/workflows/appengine-memcached.yaml
- .github/workflows/appengine-metadata-flexible.yaml
- .github/workflows/appengine-metadata-standard.yaml
- .github/workflows/appengine-pubsub.yaml
- .github/workflows/appengine-static-files.yaml
- .github/workflows/appengine-storage-flexible.yaml
- .github/workflows/appengine-storage-standard.yaml
- .github/workflows/appengine-twilio.yaml
- .github/workflows/appengine-typescript.yaml
- .github/workflows/appengine-websockets.yaml
- renovate.json
Reduce load on Actions minutes by not rebasing our renovate PRs.
> build: do not rebase renovate PRs

- healthcare/consent/README.md
- healthcare/consent/createConsentStore.js
- healthcare/consent/deleteConsentStore.js
- healthcare/consent/getConsentStore.js
- healthcare/consent/getConsentStoreIamPolicy.js
- healthcare/consent/listConsentStores.js
- healthcare/consent/package.json
- healthcare/consent/patchConsentStore.js
- healthcare/consent/setConsentStoreIamPolicy.js
- healthcare/consent/system-test/consent_stores.test.js
New directory and initial samples for Healthcare API consent modality. Part of b/224797364.
> samples(healthcare v1): initial consent store CRUD method samples

- datastore/functions/test/index.test.js
> docs: skip datastore test as they are taking long

- run/logging-manual/app.js
**Issue:** Fixing project ref comment in `logging-manual` sample
> fix(issue-247447686): fix project ref comment

- run/jobs/README.md
- run/jobs/test/e2e_test_cleanup.yaml
- run/jobs/test/e2e_test_setup.yaml
- run/jobs/test/system.test.js
> fix: flaky Cloud Run test

- functions/concepts/backgroundTermination/index.js
✅  This was tested **on my local machine**.
> fix(functions/background-termination): fix incorrect comments

- functions/helloworld/helloworldHttp/test/sample.integration.http.test.js
> Update region tag coverage

- run/logging-manual/package.json
- run/logging-manual/test/system.test.js
> chore: Revert logging manual test changes

- functions/http/parseXML/package.json
- functions/http/parseXML/test/index.test.js
> fix(functions): add tests for parseXML sample

- functions/concepts/stateless/index.js
- functions/concepts/stateless/package.json
Updated stateless sample using gen2 declarative signature
> chore(functions/concepts): Migrate stateless sample to gen2

- functions/http/parseXML/test/index.test.js
- functions/tips/scopeDemo/test/index.test.js
> fix(functions): fix CI failures

- functions/concepts/requests/index.js
- functions/concepts/requests/package.json
Migrate Send HTTP requests Sample to gen2
> chore(functions/concepts): Migrate Send HTTP requests Sample to gen2

- .github/auto-label.yaml
Updated coverage of products in each `nodejs-docs-samples`. Ensured they map to the [existing set](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/labels) of canonical API labels.
> ci: Update auto-label.yaml

- functions/concepts/afterTimeout/index.js
- functions/concepts/afterTimeout/package.json
Updated afterTimeout sample using gen2 declarative signature
> chore(functions/concepts): Migrate afterTimeout sample to gen2

- functions/concepts/httpTermination/index.js
- functions/concepts/httpTermination/package.json
Updated httpTermination sample using gen2 signature.
Successfully tested on GCP.
> chore(functions/concepts): Migrate httpTermination sample to gen2

- retail/package.json
> test: update mocha dependency in retail

- CODEOWNERS
Include functions-framework-google team as functions samples owner
> chore: include ff google team as functions samples owners

- recaptcha/demosite/docker-compose.yaml
This can be helpful such that files get created by the same user that is running docker
> Add an optional DOCKER_COMPOSE_USER environment variable.

- cloud-sql/mysql/mysql/README.md
- cloud-sql/postgres/knex/README.md
- cloud-sql/sqlserver/mssql/README.md
Fixes #2598 
Also fixes several Markdown lint violations
> fix: update Cloud SQL service account instructions

- .github/workflows/vision.yaml
- vision/detect.v1p1beta1.js
- vision/package.json
- vision/system-test/detect.v1p1beta1.test.js
- vision/system-test/productSearch.test.js
- vision/system-test/similarProducts.test.js
- vision/system-test/textDetection.test.js
- vision/textDetection.js
* Update to Redis 4
* Remove a couple tests for a beta API that no longer supports those features
* Fix and un-skip several tests
> fix: update vision tests

- .github/auto-label.yaml
- .github/blunderbuss.yml
Update auto-label and blunderbuss config for DLP.
> chore: update auto label and blunderbuss config for dlp

- recaptcha_enterprise/demosite/app/static/scripts/component.js
- recaptcha_enterprise/demosite/docker-compose.yaml
- Remove unhelpful invalidReason from the response.
- Specify a container_name to simplify docker operations.
> Restore changes lost to the merge into main

- recaptcha_enterprise/demosite/docker-compose.yaml
See https://nodejs.org/en/blog/release/v18.11.0
> Use --watch to restart the Node server upon source file change.

- cloud-tasks/snippets/app.yaml
- cloud-tasks/snippets/createHttpTask.js
- cloud-tasks/snippets/createHttpTaskWithToken.js
- cloud-tasks/snippets/createTask.js
- cloud-tasks/snippets/package.json
- cloud-tasks/snippets/server.js
> fix: update content type for Cloud Tasks samples

- functions/slack/test/integration.test.js
> fix: update function slack test

- media/transcoder/createJobWithAnimatedOverlay.js
- media/transcoder/createJobWithStaticOverlay.js
> samples: remove restriction of JPEGs only for overlay images

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
Adding issue and PR templates as preparation to upcoming Fix It (b/275440694)
> chore: Adding issue and PR templates

- CODEOWNERS
Fixes [b/275440264](http://b/275440264)
Updates after a cross-repo audit in preparations for the upcoming FixIt.
> chore: CODEOWNERS audit

- recaptcha_enterprise/demosite/app/static/demo-6df0841a.js
- recaptcha_enterprise/demosite/app/static/global-e680a49614fd8ff8.js
- recaptcha_enterprise/demosite/app/templates/comment.html
- recaptcha_enterprise/demosite/app/templates/home.html
- recaptcha_enterprise/demosite/app/templates/login.html
- recaptcha_enterprise/demosite/app/templates/signup.html
- recaptcha_enterprise/demosite/app/templates/store.html
Update to latest frontend code. The change fixes 2 bugs identified during bughunt. 
1. Fixes the tab navigation to blank page (b/278565964)
2. Button says "Play the game" after the results are obtained in the comment page. (b/278563766)
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3159
https://github.com/GoogleCloudPlatform/python-docs-samples/pull/9746
https://github.com/GoogleCloudPlatform/java-docs-samples/pull/7921
> feat: update recaptcha demosite front end

- recaptcha_enterprise/demosite/app/controllers/controller.js
- recaptcha_enterprise/demosite/app/static/demo-6df0841a.js
- recaptcha_enterprise/demosite/app/static/global-e680a49614fd8ff8.js
1. Update returned `response` from backend to include `reason` for "bad" actions.
2. Update client messaging to display the bad action messages.
3. Update client response to fetch 'Invalid token' value based on the reason returned.
> fix: update demosite to reflect error messages in client

- workflows/quickstart/index.js
- workflows/quickstart/index.ts
> fix: add execution argument to workflow sample

- dialogflow-cx/test/detect-intent-sentiment-analysis-test.js
> fix: Update detect-intent-sentiment-analysis-test.js

- .github/blunderbuss.yml
- CODEOWNERS
Update asset owners and blunderbuss
> chore: update asset owners and blunderbuss

- pubsub/README.md
**Issue:** Adding in base folder and readme to avoid  merge conflicts in future pubsub sample PRs.
> feat: adding pubsub base for future samples to be added in

- dialogflow-cx/configure-webhook-to-set-form-parameter-as-optional-or-required.js
- dialogflow-cx/package.json
- dialogflow-cx/test/configure-webhook-to-set-form-parameter-as-optional-or-required.js
- dialogflow-cx/test/webhook-configure-session-parameters.test.js
- dialogflow-cx/test/webhook-validate-form-parameter.test.js
- dialogflow-cx/test/webhook.test.js
- dialogflow-cx/webhook-configure-session-parameters.js
- dialogflow-cx/webhook-validate-form-parameter.js
- dialogflow-cx/webhooks.js
> chore(dialogflow-cx): update function samples to use http signature

- ai-platform/snippets/predict-code-generation-function.js
- ai-platform/snippets/test/predict-code-generation-function.test.js
Add a code sample for the code generation function for Vertex LLMs
> feat(aiplatform): code generation function sample for Vertex LLMs

- ai-platform/snippets/predict-code-completion-comment.js
- ai-platform/snippets/test/predict-code-completion-comment.test.js
Add a code completion comment sample for Vertex LLMs.
> feat(aiplatform): code completion comment sample for Vertex LLMs

- ai-platform/snippets/predict-code-chat.js
- ai-platform/snippets/predict-code-completion-comment.js
- ai-platform/snippets/predict-code-completion-test-function.js
- ai-platform/snippets/predict-code-generation-function.js
- ai-platform/snippets/predict-code-generation-unittest.js
Update model parameters and instances based on the public documentation.
> fix(aiplatform): update model parameters and instances

- CODEOWNERS
remove individuals from 2 of the functions samples
- [ x] Please **merge** this PR for me once it is approved
> fix: Update CODEOWNERS

- ai-platform/snippets/list-tuned-models.js
- ai-platform/snippets/test/list-tuned-models.test.js
LLM list models tests failing; this fixes the issue.
> fix(aiplatform): list tuned models test

- cloud-sql/postgres/knex/connect-connector-with-iam-authn.js
- cloud-sql/postgres/knex/index.js
Fixing region tags around IAM AuthN sample and adding Connector with IAM AuthN branch into app logic.
> fix(cloud-sql): update region tag and logic for IAM Authn

- .github/workflows/ai-platform-snippets.yaml
- .github/workflows/automl.yaml
- .github/workflows/ci.yaml
- .github/workflows/dialogflow-cx.yaml
- .github/workflows/functions-slack.yaml
- .github/workflows/iam-deny.yaml
- .github/workflows/security-center-snippets.yaml
- .github/workflows/storagetransfer.yaml
- .github/workflows/test.yaml
- .github/workflows/utils/ci-secrets.yaml.njk
- .github/workflows/vision.yaml
Various workflow updates and clean up.
> fix: various workflow updates

- security-center/snippets/v1/addDeleteSecurityMarks.js
- security-center/snippets/v1/addFindingSecurityMarks.js
- security-center/snippets/v1/addSecurityMarks.js
- security-center/snippets/v1/createNotificationConfig.js
- security-center/snippets/v1/deleteNotificationConfig.js
- security-center/snippets/v1/deleteSecurityMarks.js
- security-center/snippets/v1/getNotificationConfig.js
- security-center/snippets/v1/listAllAssets.js
- security-center/snippets/v1/listAllFindings.js
- security-center/snippets/v1/listAllSources.js
- security-center/snippets/v1/listAssetsAndChanges.js
- security-center/snippets/v1/listAssetsAtTime.js
- security-center/snippets/v1/listAssetsWithSecurityMarks.js
- security-center/snippets/v1/listFilteredAssets.js
- security-center/snippets/v1/listFilteredFindings.js
- security-center/snippets/v1/listFindingsAtTime.js
- security-center/snippets/v1/listFindingsWithSecurityMarks.js
- security-center/snippets/v1/listNotificationConfigs.js
- security-center/snippets/v1/updateNotificationConfig.js
Contains only comment updates to allow new parent types (b/263299056)
> chore(scc-samples): update comments to include new parent resources

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Clarifying contribution path to help future pull requests not get blocked by auth errors.
> chore: update pull request template and contributing docs

- .kokoro/run/websockets.cfg
- run/websockets/package.json
> chore: update puppeteer image to node 16

- .github/workflows/functions-v2-typed-googlechatbot.yaml
- .github/workflows/functions-v2-typed-greeting.yaml
- .github/workflows/utils/workflows.json
- functions/v2/typed/googlechatbot/index.js
- functions/v2/typed/googlechatbot/package.json
- functions/v2/typed/googlechatbot/test/unit.test.js
- functions/v2/typed/greeting/index.js
- functions/v2/typed/greeting/package.json
- functions/v2/typed/greeting/test/unit.test.js
Creates new samples for GCF nodejs strongly typed function signature. Samples added are
* greeting - a typed hello world (accepting JSON)
*  googlechatbot - a typed function that matches the functionality documented in https://developers.google.com/chat/quickstart/gcf-app
> feat(functions): create new samples for typed function signature

- ai-platform/snippets/tuning.js
Updates the Node.js sample for LLM tuning on Vertex AI.
> chore(aiplatform): update LLM tuning sample

- media/transcoder/createJobFromPresetBatchMode.js
- media/transcoder/package.json
- media/transcoder/test/transcoder.test.js
b:288111390
Please merge on approval.
> docs(samples): Add batch mode sample and test

- compute/instances/windows/creating-managing-windows-instances/createWindowsServerInstanceExternalIP.js
- compute/instances/windows/creating-managing-windows-instances/createWindowsServerInstanceInternalIP.js
- compute/test/creatingManagingWindows.test.js
> chore(windows-update): Updating Windows version to 2022

- media/livestream/createAsset.js
- media/livestream/deleteAsset.js
- media/livestream/getAsset.js
- media/livestream/getPool.js
- media/livestream/listAssets.js
- media/livestream/test/livestream.test.js
- media/livestream/updatePool.js
b:264616218
Please **merge** this PR for me once it is approved
> docs: add Live Stream assets and pools samples and tests

- functions/v2/helloGCS/test/unit.test.js
> chore: adding in region tag for cloud storage v2 unit test docs 

- workflows/quickstart/test/quickstart.test.ts
This PR adds an additional unit test that includes the optional `searchTerm` parameter added in #3386
> feat(workflows): add test to workflow quickstart for optional parameter

- dlp/inspectDataToHybridJobTrigger.js
- dlp/system-test/inspect.test.js
- dlp/system-test/mockdata.js
- dlp/system-test/triggers.test.js
Reference:- https://cloud.google.com/dlp/docs/how-to-hybrid-jobs#formatting
> DLP: Updated sample for inspect data to hybrid trigger using mock approach

- dlp/categoricalRiskAnalysis.js
- dlp/kAnonymityAnalysis.js
- dlp/kMapEstimationAnalysis.js
- dlp/lDiversityAnalysis.js
- dlp/numericalRiskAnalysis.js
- dlp/system-test/mockdata.js
- dlp/system-test/risk.test.js
Samples included are
-dlp_categorical_stats
-dlp_k_anonymity
-dlp_k_map
-dlp_l_diversity
-dlp_numerical_stats
References:- https://cloud.google.com/dlp/docs/samples/dlp-categorical-stats
https://cloud.google.com/dlp/docs/samples/dlp-k-anonymity
https://cloud.google.com/dlp/docs/samples/dlp-k-map
https://cloud.google.com/dlp/docs/samples/dlp-l-diversity
https://cloud.google.com/dlp/docs/samples/dlp-numerical-stats
> DLP: Updates test cases of risk job samples with mock approach

- dlp/inspectBigQuery.js
- dlp/inspectDatastore.js
- dlp/inspectGCSFile.js
- dlp/system-test/inspect.test.js
- dlp/system-test/mockdata.js
References:- https://cloud.google.com/dlp/docs/samples/dlp-inspect-gcs
https://cloud.google.com/dlp/docs/samples/dlp-inspect-bigquery
https://cloud.google.com/dlp/docs/samples/dlp-inspect-datastore
> DLP: Added test cases with mock implementation for inspect GCS, BigQuery and Datastore samples

- .github/blunderbuss.yml
- CODEOWNERS
Update sample repo code owners to infra-db-sdk
> chore: update code owners to infra-db-sdk

- error-reporting/quickstart.js
align code sample for error reporting with code in other languages (b/275730159):
* demonstrate the use of Error Reporting for reporting exceptions
* use the "fixed" error message
* delegate error context processing to Error Reporting backend
> fix: refactor error reporting code sample

- storagetransfer/event-driven-aws-transfer.js
- storagetransfer/event-driven-gcs-transfer.js
- storagetransfer/package.json
- storagetransfer/test/event-driven-aws-transfer.test.js
- storagetransfer/test/event-driven-gcs-transfer.test.js
- storagetransfer/test/utils/index.js
- storagetransfer/test/utils/queue.js
Adds event driven transfer samples and tests
> feat(storagetransfer): add event driven transfer samples and tests

- document-warehouse/quickstart.js
- document-warehouse/search-document.js
- document-warehouse/test/document.test.js
> feat: add search document sample code

- run/jobs/README.md
- run/jobs/test/e2e_test_cleanup.yaml
- run/jobs/test/e2e_test_setup.yaml
> chore: remove beta references from jobs

- workflows/list-workflows.js
- workflows/list-workflows.ts
Per b/296916003
Resubmit of #3480 on behalf of @camiekim
> docs(workflows): Clean up region tags for sample browser 

- batch/create/create_script_job_with_template.js
- batch/test/advanced_creation.js
> fix(batch): Fixing wrong parameter name

- run/README.md
Original: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3557
Adding for @sbleru. Appreciate the find!
> chore:  Fix --set-env-var to --set-env-vars

- .github/workflows/functions-slack.yaml
Extends changes from #3560 to include change to functions-slack GitHub action configs. This changed was previously blocked by failing tests resolved in #3564 
> chore(deps): update actions/checkout action to v4 (functions-slack)

- CONTRIBUTING.md
- README.md
The example sample in `README.md` and `CONTRIBUTING.md` does not exist. This PR will update the example to an existing working one.
> fix(docs): runnable example sample

- Makefile
- package.json
- run/logging-manual/app.js
This is a work in progress.
This is part of an ongoing experiment across GoogleCloudPlatform language repos.
> feat: add Makefile for consistent behavior across samples

- document-warehouse/create-document-schema.js
- document-warehouse/delete-document-schema.js
- document-warehouse/fetch-acl.js
- document-warehouse/get-document-schema.js
- document-warehouse/get-document.js
- document-warehouse/quickstart.js
- document-warehouse/search-document.js
- document-warehouse/set-acl.js
- Reported in:
- https://github.com/GoogleCloudPlatform/document-ai-samples/issues/676
- https://www.googlecloudcommunity.com/gc/AI-ML/Document-AI-Warehouse-API-Sample-Python-Code-location-eu-Issue/td-p/677608
- https://stackoverflow.com/a/77648118/6216983
Fixes https://github.com/GoogleCloudPlatform/document-ai-samples/issues/676
> fix: Add endpoint override for Document AI Warehouse samples

- generative-ai/snippets/nonStreamingMultipartContent.js
- generative-ai/snippets/sendMultiModalPromptWithImage.js
Ref: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3590
> fix: resolve typo in genai sample

- generative-ai/snippets/nonStreamingMultipartContent.js
- generative-ai/snippets/sendMultiModalPromptWithVideo.js
- generative-ai/snippets/streamMultipartContent.js
> chore: move image part before text part in vertex requests

- security-center/snippets/v1/createNotificationConfig.js
> fix(issue-3418): minor import fix for security center sample

- dialogflow-cx/test/detect-intent-sentiment-analysis-test.js
> fix(issue-3212): removing skip for detect-intent-sentiment-analysis-test test

- recaptcha_enterprise/demosite/app/package.json
Update recaptcha-enterprise client library dependency version
> chore(deps): update recaptcha-enterprise client to v5.5.0

- ai-platform/snippets/embedding-model-tuning.js
- ai-platform/snippets/test/embedding-model-tuning.test.js
> feat: Text-Embedding Model Tuning demo.

- README.md
we don't have an active presence in slack; we could consider looking at updating this to discord where there is a more active community as well
* Cleans up readme to remove slack links
* updates to minimum Node 14
> chore: cleanup README.md

- appengine/README.md
community samples were archived last year and this is an empty search.
> chore: remove community samples from README.md

- .github/workflows/generative-ai-snippets.yaml
- generative-ai/snippets/gemini-audio-summarization.js
- generative-ai/snippets/test/gemini-audio-summarization.test.js
Fixes b/330496475
Add audio summarization sample for Gemini 1.5 Pro.
> feat(generative-ai): Add audio summarization sample for Gemini 1.5

- generative-ai/snippets/gemini-system-instruction.js
- generative-ai/snippets/test/gemini-system-instruction.test.js
Fixes b/336400997
Add system instruction sample for Gemini 1.5 Pro.
> feat(generative-ai): Add system instruction sample for Gemini 1.5

- generative-ai/snippets/gemini-video-audio.js
- generative-ai/snippets/test/gemini-video-audio.test.js
Fixes b/330499342
Add video with audio code sample for Gemini 1.5 Pro.
> feat(generative-ai): Add video with audio sample for Gemini 1.5

- generative-ai/snippets/gemini-all-modalities.js
- generative-ai/snippets/test/gemini-all-modalities.test.js
Fixes b/330500166
Add all modalities code sample for Gemini 1.5 Pro.
> feat(generative-ai): Add all modalities sample for Gemini 1.5

- generative-ai/snippets/functionCallingStreamContent.js
- generative-ai/snippets/nonStreamingChat.js
- generative-ai/snippets/safetySettings.js
- generative-ai/snippets/test/functionCallingStreamContent.test.js
- generative-ai/snippets/test/nonStreamingChat.test.js
- generative-ai/snippets/test/safetySettings.test.js
Fixes b/337292079
Fix integration test errors:
- Function calling sample error
- Safety settings
- Non Streaming chat
- NonStreaming Multipart
> fix(generative-ai): Fix integration test errors

- generative-ai/snippets/countTokens.js
- generative-ai/snippets/functionCallingStreamChat.js
- generative-ai/snippets/functionCallingStreamContent.js
- generative-ai/snippets/inference/nonStreamTextBasic.js
- generative-ai/snippets/inference/streamTextBasic.js
- generative-ai/snippets/nonStreamingChat.js
- generative-ai/snippets/nonStreamingContent.js
- generative-ai/snippets/nonStreamingMultipartContent.js
- generative-ai/snippets/safetySettings.js
- generative-ai/snippets/sendMultiModalPromptWithImage.js
- generative-ai/snippets/sendMultiModalPromptWithVideo.js
- generative-ai/snippets/streamChat.js
- generative-ai/snippets/streamContent.js
- generative-ai/snippets/streamMultipartContent.js
- generative-ai/snippets/test/countTokens.test.js
- generative-ai/snippets/test/functionCallingStreamContent.test.js
- generative-ai/snippets/test/inference/nonStreamTextBasic.test.js
- generative-ai/snippets/test/inference/streamTextBasic.test.js
- generative-ai/snippets/test/nonStreamingChat.test.js
- generative-ai/snippets/test/nonStreamingContent.test.js
- generative-ai/snippets/test/nonStreamingMultipartContent.test.js
- generative-ai/snippets/test/safetySettings.test.js
- generative-ai/snippets/test/sendMultiModalPromptWithImage.test.js
- generative-ai/snippets/test/sendMultiModalPromptWithVideo.test.js
- generative-ai/snippets/test/streamChat.test.js
- generative-ai/snippets/test/streamContent.test.js
- generative-ai/snippets/test/streamMultipartContent.test.js
Update Gemini code samples to stable model versions:
gemini-1.0-pro -> gemini-1.0-pro-002
gemini-1.0-pro-vision -> gemini-1.0-pro-vision-001
> Update Gemini model versions

- run/hello-broken/index.js
- run/idp-sql/secrets.js
- run/image-processing/app.js
- run/image-processing/image.js
- run/image-processing/index.js
- run/logging-manual/app.js
- run/pubsub/app.js
- run/pubsub/index.js
Manually searched docs and confirmed no references remain. Only removed comments, no code changes.
Removed these tags:
run_user_auth_secrets
run_broken_service_upgrade
run_broken_service_problem
run_broken_service
run_pubsub_server
run_pubsub_server_setup
run_pubsub_handler
run_manual_logging
run_imageproc_handler_setup
run_imageproc_handler_blur
run_imageproc_handler_analyze
run_imageproc_controller
run_imageproc_server
> chore(fixit): remove redundant region tags

- cloud-sql/mysql/mysql/Dockerfile
- cloud-sql/mysql/mysql2/Dockerfile
- cloud-sql/postgres/knex/Dockerfile
- run/idp-sql/Dockerfile
- run/image-processing/Dockerfile
- run/logging-manual/Dockerfile
- run/logging-manual/index.js
- run/pubsub/Dockerfile
> fix: complete licence headers

- functions/tips/lazyGlobals/index.js
- functions/tips/scopeDemo/index.js
- functions/tips/scopeDemo/test/index.test.js
- run/helloworld/index.js
- run/idp-sql/cloud-sql.js
- run/idp-sql/middleware.js
- run/idp-sql/static/config.js
- run/idp-sql/static/firebase.js
- run/markdown-preview/editor/app.js
- run/markdown-preview/editor/render.js
- run/system-package/app.js
Removes redundant region tags from *.js files
run_end_user_firebase_config
run_end_user_firebase_sign_in
run_end_user_token
run_helloworld_service
run_secure_request
run_secure_request_do
run_system_package_exec
run_system_package_handler
run_tips_global_lazy
run_tips_global_scope
run_user_auth_jwt
run_user_auth_sql_connect
(Some tags in Dockerfiles and HTML files remain)
> fix: remove redundant run_ tags (fixit)

- generative-ai/snippets/functionCallingStreamChat.js
- generative-ai/snippets/functionCallingStreamContent.js
Internal: [b/326454024](http://b/326454024)
> chore: update to gemini ga calls

- generative-ai/snippets/safetySettings.js
- generative-ai/snippets/test/safetySettings.test.js
Change Gemini model version to 001 to fix issues occurring in the safety settings test.
> fix: update Gemini model version for safety settings sample

- generative-ai/snippets/gemini-text-input.js
> feat: update text-only input sample to use a generic review

- eventarc/generic/Dockerfile
- eventarc/pubsub/Dockerfile
Removes unused region tags: 
- eventarc_generic_dockerfile
- eventarc_pubsub_dockerfile
> fix: remove unused region tags

- CODEOWNERS
@skarukas and team have ownership of a slice of the samples in this area. I'm adding the team so that they can be notified of changes in this area. I've already added their team to have write privs on the repo.
> chore: add text-embedding team to CODEOWNERS

- generative-ai/snippets/gemini-video-audio.js
- generative-ai/snippets/nonStreamingMultipartContent.js
> feat: update quickstart samples to use the Gemini Flash model

- generative-ai/snippets/grounding/groundingPublicDataBasic.js
This streamlines the sample and better aligns it with other languages.
> chore: Remove extraneous safety settings in grounding sample

- ai-platform/snippets/predict-text-embeddings-preview.js
- ai-platform/snippets/predict-text-embeddings.js
Fixes: b/351419296: Should specify parameter **task_type**, not **taskType**.
> fix: Getting text-embeddings demo.

- ai-platform/snippets/predict-text-embeddings-preview.js
- ai-platform/snippets/predict-text-embeddings.js
> fix: Specify outputDimensionality properly.

- ai-platform/snippets/package.json
- ai-platform/snippets/predict-text-embeddings-preview.js
- ai-platform/snippets/predict-text-embeddings.js
- ai-platform/snippets/test/predict-text-embeddings.test.js
> fix: Validate embedding output dimensionality.

- generative-ai/snippets/nonStreamingMultipartContent.js
- generative-ai/snippets/streamMultipartContent.js
Also remove duplicate region tag to disambiguate correct sample
> fix: Update non-streaming example

- .github/workflows/appengine-analytics.yaml
- .github/workflows/appengine-building-an-app-build.yaml
- .github/workflows/appengine-building-an-app-update.yaml
- .github/workflows/appengine-datastore.yaml
- .github/workflows/appengine-endpoints.yaml
- .github/workflows/appengine-hello-world-flexible.yaml
- .github/workflows/appengine-hello-world-standard.yaml
- .github/workflows/appengine-memcached.yaml
- .github/workflows/appengine-metadata-flexible.yaml
- .github/workflows/appengine-metadata-standard.yaml
- .github/workflows/appengine-pubsub.yaml
- .github/workflows/appengine-static-files.yaml
- .github/workflows/appengine-storage-flexible.yaml
- .github/workflows/appengine-storage-standard.yaml
- .github/workflows/appengine-typescript.yaml
- .github/workflows/appengine-websockets.yaml
App Engine implementation of #3747, sibling of #3748.
> ci(appengine): update tests to use labeled on pull_request trigger

- .github/workflows/ai-platform-snippets.yaml
- .github/workflows/datacatalog-cloud-client.yaml
- .github/workflows/datacatalog-quickstart.yaml
- .github/workflows/datacatalog-snippets.yaml
- .github/workflows/datalabeling.yaml
- .github/workflows/dataproc.yaml
- .github/workflows/dlp.yaml
- .github/workflows/generative-ai-snippets.yaml
Scoped to Samples workflows for products in ai-platform, generativeai, dataproc, datalabeling, datacatalog, dlp.
This grouping is trying to find data-intensive tests that take a long time to process so remaining changes have more even test completion times.
Implementation of https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3747, sibling of https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3748.
> ci: Update workflows for ai/ml/data to use labeled on pull_request trigger

- ai-platform/snippets/predict-code-completion-comment.js
- ai-platform/snippets/predict-code-completion-test-function.js
- ai-platform/snippets/predict-text-prompt.js
- ai-platform/snippets/test/predict-code-completion-comment.test.js
- ai-platform/snippets/test/predict-code-completion-test-function.test.js
- ai-platform/snippets/test/predict-text-prompt.test.js
- generative-ai/snippets/inference/nonStreamMultiModalityBasic.js
- generative-ai/snippets/inference/nonStreamTextBasic.js
- generative-ai/snippets/inference/streamMultiModalityBasic.js
- generative-ai/snippets/inference/streamTextBasic.js
- generative-ai/snippets/safetySettings.js
- generative-ai/snippets/test/inference/nonStreamMultiModalityBasic.test.js
- generative-ai/snippets/test/inference/nonStreamTextBasic.test.js
- generative-ai/snippets/test/inference/streamMultiModalityBasic.test.js
- generative-ai/snippets/test/inference/streamTextBasic.test.js
> refactor: adjust samples to use global variables

- ai-platform/snippets/deploy-model.js
Please remove all mention of AutoML Vision, as it is deprecated. Thanks!
dianeolsen@google.com
> Update deploy-model.js to remove mention of deprecated AutoML Vision

- batch/create/create_local_ssd_job.js
- batch/test/create_local_ssd_job.test.js
> feat: batch_create_local_ssd_job

- .github/workflows/functions-slack.yaml
> fix(functions): fix invalid yaml on  functions-slack.yaml workflow

- .github/blunderbuss.yml
- CODEOWNERS
- routeoptimization/snippets/optimizeTours.js
- routeoptimization/snippets/package.json
- routeoptimization/snippets/test/optimizeTours.test.js
Note: **This PR originates from a fork; I don't have permission to edit this repository. This is self-service request - please advise**
- [] I have followed guidelines from [CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md) and [Samples Style Guide](https://googlecloudplatform.github.io/samples-style-guide/)
> feat: Add routeoptimization snippets

- batch/create/create_persistent_disk_job.js
- batch/test/create_persistent_disk_job.test.js
> feat: batch_create_persistent_job

- healthcare/fhir/patchFhirStore.js
> fix: update deprecated notificationConfig in healthcare API

- run/websockets/package.json
> chore(run/websockets): temporarily disable run/websockets on kokoro

- .github/blunderbuss.yml
Fixes b/369371010 for nodejs-docs-samples
> chore(blunderbuss): Update configuration to remove unused teams

- generative-ai/snippets/count-tokens/countTokens.js
- generative-ai/snippets/safetySettings.js
> improvement: generativeaionvertexai_gemini_safety_settings and generativeaionvertexai_gemini_token_count

- ai-platform/snippets/test/gemma2Prediction.test.js
> fix: typo in gemma2 samples

- ai-platform/snippets/batch-code-predict.js
- ai-platform/snippets/batch-text-predict.js
- ai-platform/snippets/test/batch-code-predict.test.js
- ai-platform/snippets/test/batch-text-predict.test.js
> feat: batch prediction samples

- functions/pubsub/publish/index.js
> fix(functions): remove invalid parameter for gcloud functions

- generative-ai/snippets/gemini-pdf.js
> fix(generative-ai): Fix field names

- compute/snapshotSchedule/createSnapshotSchedule.js
- compute/snapshotSchedule/deleteSnapshotSchedule.js
- compute/snapshotSchedule/editSnapshotSchedule.js
- compute/snapshotSchedule/getSnapshotSchedule.js
- compute/test/snapshotSchedule.test.js
> feat: compute_snapshot_schedule_create/delete/get/edit

- CODEOWNERS
> chore: add translate dev team for translate samples

- endpoints/getting-started/app.js
Fixes [b/392698287](http://b/392698287)
> chore(endpoints): remove older region tags

- speech/profanityFilter.js
Fixes [b/394819948](http://b/394819948)
> chore: (speech) update region tag setup in speech/profanityFilter.js

- endpoints/getting-started/app.js
Fixes [b/394798742](http://b/394798742)
> chore: (endpoints) update region tag in endpoints/getting-started/app.js

- .github/config/README.md
> docs: add new envvar/secret docs, incl ID_TOKEN usage

- .github/config/nodejs-dev.jsonc
- .github/config/nodejs-prod.jsonc
- eventarc/audit-storage/ci-setup.json
- eventarc/audit-storage/test/deploy.sh
- eventarc/audit-storage/test/runner.sh
Adding ci-setup.json to support running these tests under the new CI runner. No changes to tests themselves.
> ci(audit-storage): onboard to testing-isolation

- .github/config/nodejs-dev.jsonc
- .github/config/nodejs-prod.jsonc
- appengine/analytics/app.js
- appengine/analytics/package.json
- appengine/analytics/test/app.test.js
- appengine/metadata/flexible/package.json
- appengine/metadata/flexible/server.js
- appengine/metadata/flexible/test/server.test.js
> ci(metadata, analytics): migrate to new CI

- appengine/building-an-app/update/app.yaml
Fixes [b/401218453](http://b/401218453)
> chore(gae): Update region tag

- CODEOWNERS
Removing dee-infra from CODEOWNERS and Blunderbuss config files
> chore: Removing dee-infra from CODEOWNERS and Blunderbuss config files
